force-app/main/default/objects/Case/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(IsClosed, ClosedDate - CreatedDate, NOW() - CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (Days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <formula>if (IsClosed, 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FCR__c.field-meta.xml
<CustomField>
    <fullName>FCR__c</fullName>
    <defaultValue>true</defaultValue>
    <description>By default is checked as long as the process can be done directly.
In case of any raise ticketing (request/complaint), it will be unchecked</description>
    <label>FCR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/FCR_Count__c.field-meta.xml
<CustomField>
    <fullName>FCR_Count__c</fullName>
    <description>IF(FCR2__c, 1, 0)</description>
    <formula>IF( ISBLANK(ParentId),
IF(ISBLANK(Last_Child_Case__c), 1, 0),
IF(((Parent.CreatedDate + 30) &lt; CreatedDate), 1, 0)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FCR Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Interaction__c.field-meta.xml
<CustomField>
    <fullName>First_Interaction__c</fullName>
    <description>IF(  ISBLANK(ParentId), 1, 0)</description>
    <formula>IF( ISBLANK(ParentId),
1,
IF(((Parent.CreatedDate + 30) &lt; CreatedDate), 1, 0)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Interaction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/No_Need_To_Reply_New__c.field-meta.xml
<CustomField>
    <fullName>No_Need_To_Reply_New__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Need To Reply</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <formula>if (IsClosed, 0, 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Open</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Repeat_Call__c.field-meta.xml
<CustomField>
    <fullName>Repeat_Call__c</fullName>
    <description>IF( ISBLANK(ParentId), 0, 1)</description>
    <formula>IF( ISBLANK(ParentId),
0,
IF(((Parent.CreatedDate + 30) &lt; CreatedDate), 0, 1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Repeat Call</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer AFI</fullName>
            </value>
            <value>
                <fullName>Helpline</fullName>
            </value>
            <value>
                <fullName>Customer_AGI</fullName>
                <label>Customer AGI</label>
            </value>
            <value>
                <fullName>Non Customer AGI</fullName>
            </value>
            <value>
                <fullName>HNW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchCaseSnapshotFCR_MAGI.cls
// Sch SnapShot FCR
Global class SchCaseSnapshotFCR_MAGI implements Schedulable {

  public static String CRON_EXP = '0 0 0 3 9 ? 2022';

    Global void execute(SchedulableContext ctx) {

        date thisday = date.today();
        date lastday = date.today();
        //if (lastday.day() == 1) lastday = date.today()-1;
        //&& thisday.month() == lastday.month())  lastday = date.today();
        
        date datesnap = date.newInstance(lastday.Year(), lastday.month(), 1);
        date Lastdate = datesnap - 1;
        date Firstdate = date.newInstance(Lastdate.Year(), Lastdate.month(), 1);
        
        List <Case_Snapshot__c> delCS = [SELECT id FROM Case_Snapshot__c WHERE Entity__c = 'MAGI' and Date__c = Last_Month ]; //Date__c >=: Firstdate and Date__c <=: Lastdate
        delete delCS;
        
        List <Case_Snapshot__c> listcs = new List<Case_Snapshot__c>();

        // MAGI        
        AggregateResult[] groupedResults;
        if (test.isrunningtest()) {
        groupedResults = [SELECT CreatedById, Service_Type__c ServiceType, SUM(Age__c) age, SUM(Open__c) open, sum(Closed__c) closed, 
            sum(FCR_Count__c) fcr, sum(First_Interaction__c) f1, sum(Repeat_Call__c) repeatcall
            FROM Case
//            WHERE Entity__c = 'MAGI' and CreatedDate <=: lastday and CreatedDate >= :datesnap and No_Need_To_Reply_New__c = FALSE
            WHERE Entity__c = 'MAGI' and CreatedDate = TODAY and No_Need_To_Reply_New__c = FALSE //CreatedDate >=: Firstdate and CreatedDate <: datesnap 
                GROUP BY CreatedById, Service_Type__c ];        
        }else {
        groupedResults = [SELECT CreatedById, Service_Type__c ServiceType, SUM(Age__c) age, SUM(Open__c) open, sum(Closed__c) closed, 
            sum(FCR_Count__c) fcr, sum(First_Interaction__c) f1, sum(Repeat_Call__c) repeatcall
            FROM Case
//            WHERE Entity__c = 'MAGI' and CreatedDate <=: lastday and CreatedDate >= :datesnap and No_Need_To_Reply_New__c = FALSE
            WHERE Entity__c = 'MAGI' and CreatedDate = Last_Month and No_Need_To_Reply_New__c = FALSE //CreatedDate >=: Firstdate and CreatedDate <: datesnap 
                GROUP BY CreatedById, Service_Type__c ];
        }
                
        for (AggregateResult ar : groupedResults)  {
            id ownercase = string.valueof(ar.get('CreatedById'));
            
            Case_Snapshot__c newcs = new Case_Snapshot__c (
                Age_Days__c = integer.valueof(ar.get('age')) * 24,
                Age_Hours__c = integer.valueof(ar.get('age')),
                Closed__c = integer.valueof(ar.get('closed')),
                Date__c = Lastdate, //datesnap,
                Service_Type__c = String.valueof(ar.get('ServiceType')),
                Entity__c = 'MAGI', //string.valueof(ar.get('Entity__c')),
                FCR__c = integer.valueof(ar.get('fcr')),
                First_Interaction__c = integer.valueof(ar.get('f1')),
                Open__c = integer.valueof(ar.get('open')),
                Owner_Case__c = ownercase,
                Repeat_Call__c = integer.valueof(ar.get('repeatcall'))
            );
            listcs.add(newcs);
        }
        if (listcs.size() > 0) insert listcs;
        
    } // end execute
    
    public static string isNull(String sKata)
    {
        if(sKata == null) sKata = '';
        return sKata;
    }
} // end class