force-app/main/default/objects/Case/fields/Agent_Queue_ID_Log_Notification__c.field-meta.xml
<CustomField>
    <fullName>Agent_Queue_ID_Log_Notification__c</fullName>
    <formula>IF(Owner:User.Agent__c == TRUE,  Owner:User.Agent_Queue_ID_Log_Notification__c, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Queue ID (Log Notification)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <label>Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unread</fullName>
                <default>true</default>
                <label>Unread</label>
            </value>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Forwarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Entity_Backup__c.field-meta.xml
<CustomField>
    <fullName>Entity_Backup__c</fullName>
    <label>Entity Backup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/First_Queue__c.field-meta.xml
<CustomField>
    <fullName>First_Queue__c</fullName>
    <label>First Queue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_Queue_ID__c.field-meta.xml
<CustomField>
    <fullName>First_Queue_ID__c</fullName>
    <label>First Queue ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Non_Active_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Non_Active_Queue_Name__c</fullName>
    <formula>IF(First_Queue_ID__c != &apos;&apos; &amp;&amp; First_Queue_ID__c == &apos;00G0K000004ggVBUAY&apos;, &apos;AFI - Email Non Active Agent VIP Queue&apos;, 
IF(First_Queue_ID__c != &apos;&apos; &amp;&amp; First_Queue_ID__c == &apos;00G0K000004ggW4UAI&apos;, &apos;AFI - Email Non Active Standart Queue&apos;, 
IF(First_Queue_ID__c != &apos;&apos; &amp;&amp; First_Queue_ID__c == &apos;00G0K000004ggUwUAI&apos;, &apos;AFI - Email NonActive Customer VIP Queue&apos;, 
IF(First_Queue_ID__c != &apos;&apos; &amp;&amp; First_Queue_ID__c == &apos;00G0K000004ggVuUAI&apos;, &apos;AFI - Email Non Active Priority Queue&apos;,  
IF(First_Queue_ID__c != &apos;&apos; &amp;&amp; First_Queue_ID__c == &apos;00G0K000004ggVkUAI&apos;, &apos;AFI - Email Non Active Regular Queue&apos;,  
IF(First_Queue_ID__c != &apos;&apos; &amp;&amp; First_Queue_ID__c == &apos;00G0K000004ggVQUAY&apos;, &apos;AFI - Email Non Active Other Queue&apos;,  
IF(First_Queue_ID__c != &apos;&apos; &amp;&amp; First_Queue_ID__c == &apos;00G0K000004ggVaUAI&apos;, &apos;AFI - Email Non Active Combine Queue&apos;, 
IF(First_Queue_ID__c != &apos;&apos; &amp;&amp; First_Queue_ID__c == &apos;00G0K000004ggW9UAI&apos;, &apos;AFI - Email Non Active Blacklist Queue&apos;, &apos;Have not Non Active Queue&apos;) ) ) ) ) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Active Queue Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SchPopUpEmailNotReply.cls
global class SchPopUpEmailNotReply implements Database.Batchable<sObject>,Database.Stateful {
	global List<Case> start(Database.BatchableContext BC) {
    	/**** QUERY CASE ****/
        List<Case> scope = new List<Case>();
        scope.addAll([SELECT Id, CaseNumber, Entity_Backup__c, First_Queue__c, First_Queue_ID__c, Non_Active_Queue_Name__c, Agent_Queue_ID_Log_Notification__c, Owner.Name, OwnerId, CreatedDate FROM Case 
                      WHERE isClosed = FALSE AND (Entity_Backup__c = 'AFI' OR Entity_Backup__c = 'ALI' ) AND Origin = 'Email' AND Type = 'Inquiry' AND Email_Status__c != 'Replied' AND (NOT Owner.Name LIKE '%Queue%') AND OwnerId IN (SELECT Id FROM User WHERE Agent__c = TRUE AND is_Backoffice__c = FALSE) AND Agent_Queue_ID_Log_Notification__c != null AND HOUR_IN_DAY(LastModifiedDate) > 3 ORDER BY CreatedDate ASC LIMIT 50000]);
        system.debug('scope: '+scope);
        
        return scope; 
    }
    
    
    global void execute(Database.BatchableContext BC, List<Case> scope) {
        /* ***** OLD *****
         * 
         *List<Log_Notification__c> newLogNotification = new List<Log_Notification__c>();
        List<Case> listCase = (List<Case>) scope;
        
        //Group l_group = [SELECT Id, Name, DeveloperName, Type from GROUP WHERE Type = 'Queue' AND Name = 'AFI - CCC Queue'];
        system.debug('listCase (Size): '+listCase.size());
        
        List<String> OwnerCaseEmailNoReply_list = new List<String>();
        for(Case cs : listCase){
            OwnerCaseEmailNoReply_list.add('%'+cs.Owner.Name+'%');
        }
        
        List<Group> l_group = [SELECT Id FROM Group WHERE Type = 'Queue' AND NAME LIKE: OwnerCaseEmailNoReply_list];
        System.debug('l_group: '+l_group);
        
        if(listCase.size() > 0 && listCase != null){
            for(Case cs : listCase){ // this is the loop
                for(Group gr : l_group){
                    system.debug('=====ADA listCase=====');
                    Log_Notification__c logNotif = new Log_Notification__c();
                    logNotif.Size__c = listCase.size();
                    logNotif.Name__c = 'Email Not Reply with-in 3 hours';
                    logNotif.OwnerId = gr.Id;
                    
                    newLogNotification.add(logNotif);
                }
            }
        }
        system.debug('newLogNotification: '+newLogNotification);
        system.debug('newLogNotification (Size): '+newLogNotification.size());
        
        if(!newLogNotification.isEmpty()){
            insert newLogNotification;
            system.debug('=======INSERT DONE=======');
        }*/
        
        
        //----------------------------------------------------------------------------------------------------------------------
        //----------------------------------------------------------------------------------------------------------------------
        //----------------------------------------------------------------------------------------------------------------------
        
        
        /* ***** NEW *****
         *
		 */
        List<Log_Notification__c> newLogNotification = new List<Log_Notification__c>();
        List<Case> listCase = (List<Case>) scope;
        
        //LEADER CCC in Custom Label
        String LEADER_CCC = Label.LEADER_CCC;
        System.debug('LEADER_CCC (custom label): '+LEADER_CCC);
        List<String> leaderCCCList = LEADER_CCC.split(';');
        System.debug('leaderCCCList: '+leaderCCCList);
        Integer manyRecord = 0;
        List<String> OwnerCaseEmailNoReply_list = new List<String>();
        
        if(listCase.size() > 0 && listCase != null){
            for(String str : leaderCCCList){
                //OwnerCaseEmailNoReply_list.add('%'+str.trim()+'%');
                OwnerCaseEmailNoReply_list.add(str.trim());
            }
            System.debug('LeadCCC_list: '+OwnerCaseEmailNoReply_list);
            
            //Add Owner Name (backoffice) in Case
            for(Case cs : listCase){
                //OwnerCaseEmailNoReply_list.add('%'+cs.Owner.Name+'%');
                OwnerCaseEmailNoReply_list.add(cs.Agent_Queue_ID_Log_Notification__c);
            }
            System.debug('OwnerCaseEmailNoReply_list: '+OwnerCaseEmailNoReply_list);
        }
        
        Set<String> AddOwnerLogNotification_list = new Set<String>();
        if(OwnerCaseEmailNoReply_list.size() > 0 && OwnerCaseEmailNoReply_list != null){
            AddOwnerLogNotification_list.addAll(OwnerCaseEmailNoReply_list);
        }
        System.debug('AddOwnerLogNotification_list: '+AddOwnerLogNotification_list);
        
        /*List<Group> l_group = [SELECT Id FROM Group WHERE Type = 'Queue' AND NAME LIKE: AddOwnerLogNotification_list];
        System.debug('l_group: '+l_group);
        
        if(listCase.size() > 0 && listCase != null){
            if(l_group.size() > 0 && l_group != null){
                for(Group gr : l_group){
                    system.debug('=====ADA listCase=====');
                    Log_Notification__c logNotif = new Log_Notification__c();
                    logNotif.Size__c = listCase.size();
                    logNotif.Type__c = 'Email No Reply with-in 3 hours';
                    logNotif.OwnerId = gr.Id;
                    
                    newLogNotification.add(logNotif);
                }
            }
        }
        system.debug('newLogNotification: '+newLogNotification);*/
        
        if(listCase.size() > 0 && listCase != null){
            for(String ownerLogNotif : AddOwnerLogNotification_list){
                system.debug('=====ADA listCase=====');
                Log_Notification__c logNotif = new Log_Notification__c();
                logNotif.Size__c = listCase.size();
                logNotif.Type__c = 'Email No Reply with-in 3 hours';
                logNotif.OwnerId = ownerLogNotif;
                
                newLogNotification.add(logNotif);
            }
        }
        system.debug('newLogNotification: '+newLogNotification);
        
        if(!newLogNotification.isEmpty()){
            insert newLogNotification;
            system.debug('=======INSERT DONE=======');
        }
    }
    
    
    global void finish(Database.BatchableContext BC) {
          
    }
}