force-app/main/default/objects/Case/fields/Agent_Queue_ID_Log_Notification__c.field-meta.xml
<CustomField>
    <fullName>Agent_Queue_ID_Log_Notification__c</fullName>
    <formula>IF(Owner:User.Agent__c == TRUE,  Owner:User.Agent_Queue_ID_Log_Notification__c, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Queue ID (Log Notification)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <label>Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unread</fullName>
                <default>true</default>
                <label>Unread</label>
            </value>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Forwarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Entity_Backup__c.field-meta.xml
<CustomField>
    <fullName>Entity_Backup__c</fullName>
    <label>Entity Backup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PIC_Department_LU__c.field-meta.xml
<CustomField>
    <fullName>PIC_Department_LU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>user to assign (especially for request)</inlineHelpText>
    <label>PIC Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>notContain</operation>
            <value>Admin</value>
        </filterItems>
        <filterItems>
            <field>User.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CasesDNMP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/SchPopUpEmailNotReply_Test.cls
@isTest()
public class SchPopUpEmailNotReply_Test {
	static testmethod void schedulerTest(){
        Test.StartTest();
        
        Group gr = new Group();
        gr.Name='Group Name Agent AFI Queue';
        gr.Type='Queue';
        insert gr;
        
        Profile agentProfileAFI = [SELECT Id FROM Profile WHERE Name like 'Inbound Agent%AFI' limit 1];
        
        User userAgentAFI = new User();
        userAgentAFI.Alias = 'spv1';
        userAgentAFI.Email='agentAfi@axa.co.id';
        userAgentAFI.EmailEncodingKey='UTF-8';
        userAgentAFI.LastName='agentAfi';
        userAgentAFI.LanguageLocaleKey='en_US';
        userAgentAFI.LocaleSidKey='en_US';
        userAgentAFI.ProfileId = agentProfileAFI.Id;
        userAgentAFI.Entity__c = 'AFI';
        userAgentAFI.TimeZoneSidKey='Asia/Jakarta';
        userAgentAFI.UserName='agentAfi@axa.co.id';
        userAgentAFI.isActive = TRUE;
        userAgentAFI.Agent__c = TRUE;
        userAgentAFI.Is_Backoffice__c = FALSE;
        //userAgentAFI.Agent_Queue_ID_Log_Notification__c = '00G0k000009bOms';	//to CRM2
        userAgentAFI.Agent_Queue_ID_Log_Notification__c = '00GN0000006TgMq';	//to FullSB
        //userAgentAFI.Agent_Queue_ID_Log_Notification__c = '00G0k000009bOms';	//to Production
        insert userAgentAFI;
        system.debug('userAgentAFI: '+userAgentAFI);
        
        
        Contact con1 = new Contact();
        con1.FirstName = 'Hamfry';
        con1.LastName = 'Lantu';
        con1.Policy_No__c = '1234-56781';
        insert con1;
        
        Case cs1 = new Case();
        cs1.Status = 'New';
        cs1.Entity_Backup__c = 'AFI';
        cs1.Origin = 'Email';
        cs1.Type = 'Inquiry';
        //cs1.OwnerId = userAgentAFI.Id;
        cs1.OwnerId = '0056F000007cd8E';
        cs1.PIC_Department_LU__c = userAgentAFI.Id;
        cs1.Subject = 'ILCCYS';
        cs1.Email_Status__c = 'Unread';
        cs1.CreatedDate = DateTime.newInstance(2019,2,1);
        cs1.LastModifiedDate = DateTime.newInstance(2019,2,1);
        insert cs1;
        system.debug('cs1 (SchPopUpEmailNotReply_Test): '+cs1);
        
        
        SchEmailNotReply m = new SchEmailNotReply();
        String sch = '0 0 10-16/3 * * ?';
        String jobID = system.schedule('SCHEDULE JOB SchPopUpEmailNotReply 2', sch, m);
        Test.stopTest();
    }
}