force-app/main/default/objects/Case/fields/Agent_Code__c.field-meta.xml
<CustomField>
    <fullName>Agent_Code__c</fullName>
    <formula>Contact.Agent_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Name__c</fullName>
    <formula>Contact.Agent_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agent_Status__c.field-meta.xml
<CustomField>
    <fullName>Agent_Status__c</fullName>
    <formula>Contact.Agent_Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <formula>Contact.Branch_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Chronological__c.field-meta.xml
<CustomField>
    <fullName>Chronological__c</fullName>
    <label>Chronological</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <label>Demand</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Complaint Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Lost__c.field-meta.xml
<CustomField>
    <fullName>Financial_Lost__c</fullName>
    <label>Financial Lost*</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Lost_Currency__c.field-meta.xml
<CustomField>
    <fullName>Financial_Lost_Currency__c</fullName>
    <label>Financial Lost Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IDR</fullName>
                <default>true</default>
                <label>IDR</label>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>Insured_Name__c</fullName>
    <formula>Contact.Insured_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insured Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lampiran__c.field-meta.xml
<CustomField>
    <fullName>Lampiran__c</fullName>
    <description>To be used in Memo Approval</description>
    <label>Attachment</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <formula>Contact.Policy_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Policy_Numbers__c</fullName>
    <formula>Contact.Policy_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <formula>Contact.Policy_Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <formula>Contact.Premium__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MV</fullName>
            </value>
            <value>
                <fullName>Non MV</fullName>
            </value>
            <value>
                <fullName>GC1040</fullName>
            </value>
            <value>
                <fullName>GC1060</fullName>
            </value>
            <value>
                <fullName>GC3020</fullName>
            </value>
            <value>
                <fullName>GC3040</fullName>
            </value>
            <value>
                <fullName>GC3060</fullName>
            </value>
            <value>
                <fullName>GC5020</fullName>
            </value>
            <value>
                <fullName>GC5040</fullName>
            </value>
            <value>
                <fullName>GC5060</fullName>
            </value>
            <value>
                <fullName>GC1020</fullName>
            </value>
            <value>
                <fullName>HONAR</fullName>
            </value>
            <value>
                <fullName>HONBR</fullName>
            </value>
            <value>
                <fullName>HONMCR</fullName>
            </value>
            <value>
                <fullName>HONMDR</fullName>
            </value>
            <value>
                <fullName>HONMAR</fullName>
            </value>
            <value>
                <fullName>HONMBR</fullName>
            </value>
            <value>
                <fullName>HONMS</fullName>
            </value>
            <value>
                <fullName>HONSPA</fullName>
            </value>
            <value>
                <fullName>NYT</fullName>
            </value>
            <value>
                <fullName>NT05</fullName>
            </value>
            <value>
                <fullName>NT10</fullName>
            </value>
            <value>
                <fullName>MEC</fullName>
            </value>
            <value>
                <fullName>MHP</fullName>
            </value>
            <value>
                <fullName>FFH</fullName>
            </value>
            <value>
                <fullName>MPP</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>TM</fullName>
            </value>
            <value>
                <fullName>Conventional</fullName>
            </value>
            <value>
                <fullName>Corporate Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <label>Recommendation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGIONAL 1</fullName>
            </value>
            <value>
                <fullName>REGIONAL 2</fullName>
            </value>
            <value>
                <fullName>REGIONAL 3</fullName>
            </value>
            <value>
                <fullName>REGIONAL 4</fullName>
            </value>
            <value>
                <fullName>REGIONAL 5</fullName>
            </value>
            <value>
                <fullName>REGIONAL 6</fullName>
            </value>
            <value>
                <fullName>REGIONAL 7</fullName>
            </value>
            <value>
                <fullName>REGIONAL 8</fullName>
            </value>
            <value>
                <fullName>REGIONAL 9</fullName>
            </value>
            <value>
                <fullName>REGIONAL 10</fullName>
            </value>
            <value>
                <fullName>REGIONAL 11</fullName>
            </value>
            <value>
                <fullName>REGIONAL 12</fullName>
            </value>
            <value>
                <fullName>BSM REG. 2</fullName>
            </value>
            <value>
                <fullName>BSM REG. 3</fullName>
            </value>
            <value>
                <fullName>BSM REG. 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <formula>Contact.Segment_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Agent_Status__c.field-meta.xml
<CustomField>
    <fullName>Agent_Status__c</fullName>
    <label>Agent Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <label>Branch Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>Insured_Name__c</fullName>
    <label>Insured Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Individu - Local (ESC)</fullName>
            </value>
            <value>
                <fullName>Health Individu - International (IE - Promedicare AB- Promedicare CDE)</fullName>
            </value>
            <value>
                <fullName>Health Group - Local (GSC)</fullName>
            </value>
            <value>
                <fullName>Health Group - International (IE)</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Liability - Commercial</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>MV - Commercial</fullName>
            </value>
            <value>
                <fullName>MV - Retail</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Property - Commercial</fullName>
            </value>
            <value>
                <fullName>Domestic Travel</fullName>
            </value>
            <value>
                <fullName>International Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <label>Segment Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/MemoApprovalController.cls
public without sharing class MemoApprovalController {
    public Case chsCase {get;set;}
    public String numberCounter {get;set;}
    public Integer month {get;set;}
    public Integer year {get;set;}
    public String entitas {get;set;}
    //public String estimatedLoss {get;set;}
    public String Manager {get;set;}
    public String DeputyCOO {get;set;}
    public String CFO {get;set;}
    public String Dirut {get;set;}
 	         
    public String getPrintView(){
        return
        '<!--[if gte mso 9]>' +
            '<xml>' +
            '<w:WordDocument>' +
            '<w:View>Print</w:View>' +
            '<w:Zoom>100</w:Zoom>' +
            '<w:DoNotOptimizeForBrowser/>' +
            '</w:WordDocument>' +
            '</xml>' +
        '<![endif]>';
    }
             
    public MemoApprovalController(ApexPages.StandardController stdCtrl) {
        chsCase = new Case();

        try{
	        Case complaintCase = (Case)stdCtrl.getRecord();
	        month = Date.Today().Month();
	        year = Date.Today().Year();
	        
	        chsCase = [SELECT CreatedDate, Lampiran__c, Subject, ContactId, Contact.Name, Entity__c, Insured_Name__c, Policy_Numbers__c, Policy_Effective_Date__c,
						Policy_Status__c, Premium__c, Product__c, Agent_Name__c, Agent_Code__c, Agent_Status__c, Region__c, Segment_Name__c, Recommendation__c,
						Branch_Name__c, Description__c, Demand__c, Chronological__c, Financial_Lost__c, Financial_Lost_Currency__c 
			            FROM Case WHERE Id = :complaintCase.Id];
	        
	        entitas = chsCase.Entity__c;
	        
	        //estimatedLoss = chsCase.Financial_Lost_Currency__c+ ' ' +chsCase.Financial_Lost__c;
	        
	        //Query for MAGI memo approval
	       	List<User> usrManager =  [SELECT id, name, UserRole.name FROM User WHERE userRole.name = 'CCC Manager MAGI' AND entity__c = 'MAGI'];
	        if(usrManager.size() > 0){
	        	Manager = usrManager[0].Name;
	        }
	        else{
	        	Manager = '...............';
	        }
	        
	       	List<User> usrDeputy =  [SELECT id, name, UserRole.name FROM User WHERE userRole.name = 'Deputy COO MAGI' AND entity__c = 'MAGI'];
	        if(usrDeputy.size() > 0){
	        	DeputyCOO = usrDeputy[0].Name;
	        }
	        else{
	        	DeputyCOO = '...............';
	        }
	        /*
	        List<User> usrCFO =  [SELECT id, name, UserRole.name FROM User WHERE userRole.name = 'Finance Head MAGI' AND entity__c = 'MAGI'];
	        if(usrCFO.size() > 0){
	        	CFO = usrCFO[0].Name;
	        }
	        else{
	        	CFO = '...............';
	        }
	        
	        List<User> usrDirut =  [SELECT id, name, UserRole.name FROM User WHERE userRole.name = 'CEO MAGI' AND entity__c = 'MAGI'];
	        if(usrDirut.size() > 0){
	        	Dirut = usrDirut[0].Name;
	        }
	        else{
	        	Dirut = '...............';
	        }
	        */
	        CFO = system.label.CFO_Magi;
	        Dirut = system.label.CEO_Magi;
	    }catch(Exception e){
	    	system.debug('Error message: ' + e.getMessage());
	    }
    }
    
    public void dmlOperation() {
        
        if(entitas=='AMFS'){
        	NumberGenerator numGen = new NumberGenerator();
        	numberCounter = numGen.getNumber('AMFS');
        }
        if(entitas=='AFI'){
        	NumberGenerator numGen = new NumberGenerator();
        	numberCounter = numGen.getNumber('AFI');
        }      
    }
    
    public void dmlOperationMAGI() {
        NumberGenerator numGen = new NumberGenerator();
        numberCounter = numGen.getNumber('MAGI');      
    }
}