force-app/main/default/objects/Case/fields/Business_channel__c.field-meta.xml
<CustomField>
    <fullName>Business_channel__c</fullName>
    <label>Business channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leasing</fullName>
            </value>
            <value>
                <fullName>Bancassurance</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Direct Online</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>TM</fullName>
            </value>
            <value>
                <fullName>Conventional</fullName>
            </value>
            <value>
                <fullName>Corporate Solution</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Agency Online</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Direct - Travel Agent</fullName>
            </value>
            <value>
                <fullName>Direct - Corp. Partner</fullName>
            </value>
            <value>
                <fullName>Fullerton</fullName>
            </value>
            <value>
                <fullName>Inbranch</fullName>
            </value>
            <value>
                <fullName>DPLK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Category_Config__c.field-meta.xml
<CustomField>
    <fullName>Category_Config__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Nature_Config__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Others - Others</fullName>
            </value>
            <value>
                <fullName>Courier Delivery - Delivery</fullName>
            </value>
            <value>
                <fullName>Courier Delivery - Inquiry Delivery</fullName>
            </value>
            <value>
                <fullName>Courier Delivery - Inquiry Receipt</fullName>
            </value>
            <value>
                <fullName>Claim Decision</fullName>
            </value>
            <value>
                <fullName>Claim Delay</fullName>
            </value>
            <value>
                <fullName>Financial Advisor Service</fullName>
            </value>
            <value>
                <fullName>Forgery</fullName>
            </value>
            <value>
                <fullName>Misappropriation</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - Lack of Professional Knowledge</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - Misrepresentation</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - Premium Holiday</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - TM</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Non Disclosure</fullName>
            </value>
            <value>
                <fullName>Facility Service</fullName>
            </value>
            <value>
                <fullName>Collector</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Employee Training</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hardware Problem - IT</fullName>
            </value>
            <value>
                <fullName>Information - Marketing</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>No Follow Up</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Service - Activity Support</fullName>
            </value>
            <value>
                <fullName>Service Facility</fullName>
            </value>
            <value>
                <fullName>Skill/Product Knowledge</fullName>
            </value>
            <value>
                <fullName>Soft ware Problem - IT</fullName>
            </value>
            <value>
                <fullName>CS-Missing document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Verbal (Call)</fullName>
            </value>
            <value>
                <fullName>Walk-In</fullName>
            </value>
            <value>
                <fullName>Written</fullName>
            </value>
            <value>
                <fullName>Solicitor/Lawyer</fullName>
            </value>
            <value>
                <fullName>Regulator</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Print media</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Livechat</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Bank Mandiri - CCG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/General_Attitude__c.field-meta.xml
<CustomField>
    <fullName>General_Attitude__c</fullName>
    <label>Customer Mood</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NonPP__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Happy</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Angry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nature_Config__c.field-meta.xml
<CustomField>
    <fullName>Nature_Config__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative procedures</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claim Decision</fullName>
            </value>
            <value>
                <fullName>Comben</fullName>
            </value>
            <value>
                <fullName>Courier Delivery</fullName>
            </value>
            <value>
                <fullName>Courier Investigation</fullName>
            </value>
            <value>
                <fullName>Financial Advisor Service</fullName>
            </value>
            <value>
                <fullName>Forgery</fullName>
            </value>
            <value>
                <fullName>Misappropriation</fullName>
            </value>
            <value>
                <fullName>Misrepresentation</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Non Disclosure</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Policy Duplicate</fullName>
            </value>
            <value>
                <fullName>Policy Retur</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>TM Service</fullName>
            </value>
            <value>
                <fullName>Twisting/Chunning</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>Without Consent</fullName>
            </value>
            <value>
                <fullName>Processing Error</fullName>
            </value>
            <value>
                <fullName>Agent Services</fullName>
            </value>
            <value>
                <fullName>Human Error</fullName>
            </value>
            <value>
                <fullName>Processing Times</fullName>
            </value>
            <value>
                <fullName>Service provided by 3rd parties</fullName>
            </value>
            <value>
                <fullName>Service provided by the internal Staff</fullName>
            </value>
            <value>
                <fullName>Service provided by the Distributors</fullName>
            </value>
            <value>
                <fullName>CS-Missing document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NonPP__c.field-meta.xml
<CustomField>
    <fullName>NonPP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>non pp</description>
    <inlineHelpText>Non Pemegang Polis</inlineHelpText>
    <label>NonPP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MV</fullName>
            </value>
            <value>
                <fullName>Non MV</fullName>
            </value>
            <value>
                <fullName>GC1040</fullName>
            </value>
            <value>
                <fullName>GC1060</fullName>
            </value>
            <value>
                <fullName>GC3020</fullName>
            </value>
            <value>
                <fullName>GC3040</fullName>
            </value>
            <value>
                <fullName>GC3060</fullName>
            </value>
            <value>
                <fullName>GC5020</fullName>
            </value>
            <value>
                <fullName>GC5040</fullName>
            </value>
            <value>
                <fullName>GC5060</fullName>
            </value>
            <value>
                <fullName>GC1020</fullName>
            </value>
            <value>
                <fullName>HONAR</fullName>
            </value>
            <value>
                <fullName>HONBR</fullName>
            </value>
            <value>
                <fullName>HONMCR</fullName>
            </value>
            <value>
                <fullName>HONMDR</fullName>
            </value>
            <value>
                <fullName>HONMAR</fullName>
            </value>
            <value>
                <fullName>HONMBR</fullName>
            </value>
            <value>
                <fullName>HONMS</fullName>
            </value>
            <value>
                <fullName>HONSPA</fullName>
            </value>
            <value>
                <fullName>NYT</fullName>
            </value>
            <value>
                <fullName>NT05</fullName>
            </value>
            <value>
                <fullName>NT10</fullName>
            </value>
            <value>
                <fullName>MEC</fullName>
            </value>
            <value>
                <fullName>MHP</fullName>
            </value>
            <value>
                <fullName>FFH</fullName>
            </value>
            <value>
                <fullName>MPP</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
            <value>
                <fullName>TM</fullName>
            </value>
            <value>
                <fullName>Conventional</fullName>
            </value>
            <value>
                <fullName>Corporate Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/AMFSComplaintCase.recordType-meta.xml
<RecordType>
    <fullName>AMFSComplaintCase</fullName>
    <active>true</active>
    <businessProcess>Complaint</businessProcess>
    <label>AMFSComplaintCase</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Individu - Local (ESC)</fullName>
            </value>
            <value>
                <fullName>Health Individu - International (IE - Promedicare AB- Promedicare CDE)</fullName>
            </value>
            <value>
                <fullName>Health Group - Local (GSC)</fullName>
            </value>
            <value>
                <fullName>Health Group - International (IE)</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Liability - Commercial</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>MV - Commercial</fullName>
            </value>
            <value>
                <fullName>MV - Retail</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Property - Commercial</fullName>
            </value>
            <value>
                <fullName>Domestic Travel</fullName>
            </value>
            <value>
                <fullName>International Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CaseServiceController_Test.cls
@isTest
public class CaseServiceController_Test {
    private final static String RECORD_TYPE_REQUEST_CASE = 'RequestAMFSCase';
    private final static String RECORD_TYPE_INQUIRY_CASE = 'InquiryAMFSCase';
    private final static String RECORD_TYPE_COMPLAINT_CASE = 'AMFSComplaintCase';
    
	@testSetup static void setup() {
        List<Contact> contList = new List<Contact>();
        Contact cont = new Contact();
        cont.Policy_No__c = '100-000-1110001';
        cont.FirstName = 'DUMMY';
        cont.LastName = 'LOOKUP DMTM';
        contList.add(cont);
        
        cont = new Contact();
        cont.Policy_No__c = '500-1110001';
        cont.FirstName = 'DUMMY';
        cont.LastName = 'LOOKUP KONV';
        contList.add(cont);
        
        cont = new Contact();
        cont.Policy_No__c = '300-1110001';
        cont.FirstName = 'DUMMY';
        cont.LastName = 'LOOKUP SYA';
        contList.add(cont);
        
        cont = new Contact();
        cont.Policy_No__c = '801-1110001';
        cont.FirstName = 'DUMMY';
        cont.LastName = 'LOOKUP CORP';
        contList.add(cont);
        Insert contList;
    }
    
    static testmethod void testCreateTypeInquiry(){
        Case cs = new Case();
        cs.recordTypeId = getRecordTypeCaseId(RECORD_TYPE_INQUIRY_CASE);
        cs.ContactId = getContactIDbyPolicyNo('500-1110001');
        cs.Subject = 'Subject Dummy Inquiry';
        cs.Origin = 'Walk-In';
        cs.NonPP__c = false;
        cs.General_Attitude__c = 'Normal';
        cs.Case_Type__c = cs.Case_Type_Config__c = '';
        cs.Type = 'Inquiry';
        cs.Description = 'Description Dummy Inquiry';
        
        CaseServiceController caseService = new CaseServiceController();
        List<Case> resultSave = caseService.processInquirySaveWithClosedStatus(cs, new String[]{''});
        for(Integer i=0; i<resultSave.size(); i++){
            Case resultCase = resultSave[i];
            System.assertEquals(true, resultSave != null);
        }
    }
    
    static testmethod void testCreateTypeRequest(){
        Case cs = new Case();
        cs.recordTypeId = getRecordTypeCaseId(RECORD_TYPE_REQUEST_CASE);
        cs.ContactId = getContactIDbyPolicyNo('500-1110001');
        cs.Subject = 'Subject Dummy Request';
        cs.Origin = 'Walk-In';
        cs.NonPP__c = false;
        cs.General_Attitude__c = 'Normal';
        cs.Case_Type__c = cs.Case_Type_Config__c = '';
        cs.Type = 'Request';
        cs.Description = 'Description Dummy Request';
        cs.Status = 'Closed';
        
        CaseServiceController caseService = new CaseServiceController();
        caseService.getCekCourierCase(cs);
        Case resultSave = caseService.processRequestSave(cs, 'AMFS');
        if(resultSave != null){
            System.assertEquals(true,resultSave.id != null);
        }
	}
    
    static testmethod void testCreateTypeComplaint(){
        Case cs = new Case();
        cs.recordTypeId = getRecordTypeCaseId(RECORD_TYPE_COMPLAINT_CASE);
        cs.ContactId = getContactIDbyPolicyNo('100-000-1110001');
        cs.Subject = 'Subject Dummy Complaint';
        cs.Origin = cs.Channel__c = 'Walk-In';
        cs.NonPP__c = false;
        cs.General_Attitude__c = 'Normal';
        cs.Case_Type__c = cs.Case_Type_Config__c = '';
        cs.Type = 'Complaint';
        cs.Nature_Config__c = 'Administrative procedures';
        cs.Category_Config__c = 'CS-Missing document';
        cs.Business_channel__c = cs.Product__c = 'TM';
        cs.Customer__c = cs.Complainant__c = 'Customer';
        cs.Customer_type__c = 'Regular';
        cs.Complaint_type__c = 'Simple';
        cs.Priority = 'Medium';
        cs.Description__c = 'Description Dummy Complaint';
        cs.Received_date__c = Date.today();
        
        CaseServiceController caseService = new CaseServiceController();
        caseService.getCekCourierCase(cs);
        Case resultSave = caseService.processComplaintSave(cs, 'AMFS');
        if(resultSave != null){
            System.assertEquals(true,resultSave.id != null);
        }
	}
    
    private static ID getContactIDbyPolicyNo(String policyNo){
        id contId = null;
        Contact[] resultContact = [SELECT id FROM Contact WHERE Policy_No__c = :policyNo LIMIT 1];
        if(resultContact.size() > 0){
            contId = resultContact[0].id;
        }
        
        return contId;
    }
    
    private static ID getRecordTypeCaseId(String Recordtype){
        return Schema.SObjectType.Case.getRecordTypeInfosByName().get(Recordtype).getRecordTypeId();
    }
}