force-app/main/default/objects/Case/fields/Case_Id_External__c.field-meta.xml
<CustomField>
    <fullName>Case_Id_External__c</fullName>
    <externalId>true</externalId>
    <label>Case Id (External)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_No_External__c.field-meta.xml
<CustomField>
    <fullName>Case_No_External__c</fullName>
    <externalId>true</externalId>
    <label>Case No (External)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Sensitive_Customer__c.field-meta.xml
<CustomField>
    <fullName>Case_Sensitive_Customer__c</fullName>
    <label>Case Sensitive Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CHS_Status__c.field-meta.xml
<CustomField>
    <fullName>CHS_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>In Progress CMU</fullName>
            </value>
            <value>
                <fullName>Assigned to Back Office</fullName>
            </value>
            <value>
                <fullName>In Progress Back Office</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Escalation Rejected</fullName>
            </value>
            <value>
                <fullName>Escalation Approved</fullName>
            </value>
            <value>
                <fullName>BOD Approval</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid</fullName>
            </value>
            <value>
                <fullName>Closed - Valid</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Document_Request_Revise__c.field-meta.xml
<CustomField>
    <fullName>Document_Request_Revise__c</fullName>
    <label>Document Request Revise</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>CHS_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>KTP</fullName>
            </value>
            <value>
                <fullName>Surat Kuasa Policy Holder</fullName>
            </value>
            <value>
                <fullName>KTP Penerima Kuasa</fullName>
            </value>
            <value>
                <fullName>Surat Kuasa</fullName>
            </value>
            <value>
                <fullName>Form Complaint</fullName>
            </value>
            <value>
                <fullName>Other1</fullName>
            </value>
            <value>
                <fullName>Other2</fullName>
            </value>
            <value>
                <fullName>Other3</fullName>
            </value>
            <value>
                <fullName>Other4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCC</fullName>
            </value>
            <value>
                <fullName>Back Office</fullName>
            </value>
            <value>
                <fullName>HL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <label>Pending Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CHS_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Proceed by CMU</fullName>
            </value>
            <value>
                <fullName>Customer Non Contacted</fullName>
            </value>
            <value>
                <fullName>Customer Contacted But No Response</fullName>
            </value>
            <value>
                <fullName>Not Yet Submit Complaint Report</fullName>
            </value>
            <value>
                <fullName>Need More Document</fullName>
            </value>
            <value>
                <fullName>Investigated by FCO</fullName>
            </value>
            <value>
                <fullName>Waiting For Confirmation From Related Dept</fullName>
            </value>
            <value>
                <fullName>Memo Circulation</fullName>
            </value>
            <value>
                <fullName>Appeal</fullName>
            </value>
            <value>
                <fullName>SQ</fullName>
            </value>
            <value>
                <fullName>Call Nasabah Info Hasil Memo</fullName>
            </value>
            <value>
                <fullName>Call Nasabah (1)</fullName>
            </value>
            <value>
                <fullName>Call Nasabah (2)</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>W/F Meeting Coordination</fullName>
            </value>
            <value>
                <fullName>Surat Penyelesaian/Pencabutan FA</fullName>
            </value>
            <value>
                <fullName>Memo on Progress</fullName>
            </value>
            <value>
                <fullName>W/F Memo FCO</fullName>
            </value>
            <value>
                <fullName>TC/Int FA</fullName>
            </value>
            <value>
                <fullName>Pending Litigation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CHS_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Validation</fullName>
            </value>
            <value>
                <fullName>Document Completion</fullName>
            </value>
            <value>
                <fullName>Courtesy Call (Unsuccessfull)</fullName>
            </value>
            <value>
                <fullName>Courtesy Call (Success)</fullName>
            </value>
            <value>
                <fullName>Follow Up To Backoffice</fullName>
            </value>
            <value>
                <fullName>Closing Call (Unsuccessfull)</fullName>
            </value>
            <value>
                <fullName>Closing Call (Success)</fullName>
            </value>
            <value>
                <fullName>Waiting Document Completion</fullName>
            </value>
            <value>
                <fullName>Waiting For Approval</fullName>
            </value>
            <value>
                <fullName>On Process</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Invalid Paid</fullName>
            </value>
            <value>
                <fullName>Approved Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseComplaintService.cls
public class CaseComplaintService {
    public static HttpCalloutMock mock{get;set;}
    public static String estr {get;set;}
    public static String rstr {get;set;}
    public static String mstr {get;set;}
    public static String errMessage {get;set;}

    private static final String AMFS = 'AMFS';
    private static final String COMPLAINT = 'Complaint';

    public static CaseComplaintAPI.CaseResponse callUpdateFACase(Case caseObj) {
        FA_Integration__mdt config = getConfig('Update_Case');
        mstr = '';
        estr = '';
        rstr = '';
        String endpoint = 'callout:' + config.Named_Credential__c + config.Endpoint__c;
        Http httpObj = new Http();
        HttpRequest requestObj = new HttpRequest();
        HttpResponse responseObj;
        CaseComplaintAPI.CaseRequest cReq = new CaseComplaintAPI.CaseRequest();
        cReq.existing_case = generateCaseExtFromCase(caseObj);
        requestObj.setMethod(config.HTTP_Method__c);
        requestObj.setEndpoint(endpoint);
        requestObj.setHeader('Content-Type','application/json');
        requestObj.setBody(JSON.serialize(cReq, true));
        requestObj.setTimeout(120000);
        mstr = requestObj.getMethod();
        estr = requestObj.getEndpoint();
        if (Test.isRunningTest() && mock != null) {
            responseObj = mock.respond(requestObj);
        }
        else {
            responseObj = httpObj.send(requestObj);
        }
        rstr = responseObj.getBody();
        CaseComplaintAPI.CaseResponse cr = (CaseComplaintAPI.CaseResponse) JSON.deserialize(responseObj.getBody(), CaseComplaintAPI.CaseResponse.class);
        return cr;
    }

    public static List<Attachment> callGetAttachments(String caseExtId) {
        FA_Integration__mdt config = getConfig('Get_Attachments');
        mstr = '';
        estr = '';
        rstr = '';
        String param1 = '?parent_id=';
        String endpoint = 'callout:' + config.Named_Credential__c + config.Endpoint__c;
        Http httpObj = new Http();
        HttpRequest requestObj = new HttpRequest();
        HttpResponse responseObj;
        requestObj.setMethod(config.HTTP_Method__c);
        requestObj.setEndpoint(endpoint + param1 + caseExtId);
        requestObj.setHeader('Content-Type','application/json');
        requestObj.setTimeout(120000);
        mstr = requestObj.getMethod();
        estr = requestObj.getEndpoint();
        if (Test.isRunningTest() && mock != null) {
            responseObj = mock.respond(requestObj);
        }
        else {
            responseObj = httpObj.send(requestObj);
        }
        rstr = responseObj.getBody();
        List<Attachment> resultList = (List<Attachment>) JSON.deserialize(responseObj.getBody(), List<Attachment>.class);
        return resultList;
    }

    public static CaseComplaintAPI.SyncAttachmentResponse callSyncAttachments(String caseExtId) {
        FA_Integration__mdt config = getConfig('Sync_Attachments');
        mstr = '';
        estr = '';
        rstr = '';
        String endpoint = 'callout:' + config.Named_Credential__c + config.Endpoint__c;
        Http httpObj = new Http();
        HttpRequest requestObj = new HttpRequest();
        HttpResponse responseObj;
        CaseComplaintAPI.SyncAttachmentRequest saReq = new CaseComplaintAPI.SyncAttachmentRequest();
        saReq.parent_id = caseExtId;
        requestObj.setMethod(config.HTTP_Method__c);
        requestObj.setEndpoint(endpoint);
        requestObj.setHeader('Content-Type','application/json');
        requestObj.setBody(JSON.serialize(saReq, true));
        requestObj.setTimeout(120000);
        mstr = requestObj.getMethod();
        estr = requestObj.getEndpoint();
        if (Test.isRunningTest() && mock != null) {
            responseObj = mock.respond(requestObj);
        }
        else {
            responseObj = httpObj.send(requestObj);
        }
        rstr = responseObj.getBody();
        CaseComplaintAPI.SyncAttachmentResponse saRes = (CaseComplaintAPI.SyncAttachmentResponse) JSON.deserialize(responseObj.getBody(), CaseComplaintAPI.SyncAttachmentResponse.class);
        return saRes;
    }

    public static void syncFACase(List<Case> caseList, Map<Id, SObject> oldMap) {
        List<String> caseIdList = new List<String>();
        Map<String, String> caseIdMap = new Map<String, String>();
        for (Case caseObj : caseList) {
            Case oldCase = (Case) oldMap.get(caseObj.Id);
            Boolean diffStatus = oldCase.CHS_Status__c == caseObj.CHS_Status__c ? false : true;
            System.debug('***CaseComplaintService syncFACase diffStatus: ' + diffStatus);
            if (diffStatus) {
                FA_Integration__mdt config = getConfig('Update_Case');
                List<String> criteriaList = config.Criteria__c.replaceAll('\r\n|\n|\r','').split('\\s*;\\s*');
                System.debug('***CaseComplaintService syncFACase case values CHS_Status__c: ' + caseObj.CHS_Status__c);
                System.debug('***CaseComplaintService syncFACase case values Entity__c: ' + caseObj.Entity__c);
                System.debug('***CaseComplaintService syncFACase case values Type: ' + caseObj.Type);
                System.debug('***CaseComplaintService syncFACase case values Origin: ' + caseObj.Origin);
                System.debug('***CaseComplaintService syncFACase config values criteriaList: ' + criteriaList);
                System.debug('***CaseComplaintService syncFACase config values Entity__c: ' + config.Entity__c);
                System.debug('***CaseComplaintService syncFACase config values Type__c: ' + config.Type__c);
                System.debug('***CaseComplaintService syncFACase config values Origin__c: ' + config.Origin__c);
                if (criteriaList.contains(caseObj.CHS_Status__c) && caseObj.Entity__c == config.Entity__c && caseObj.Type == config.Type__c && caseObj.Origin == config.Origin__c) {
                    caseIdMap.put(caseObj.Id, caseObj.Id);
                }
            }
        }
        caseIdList.addAll(caseIdMap.values());
        syncFACaseFuture(caseIdList);
    }

    @future(callout=true)
    public static void syncFACaseFuture(List<String> caseIdList) {
        System.debug('***CaseComplaintService syncFACaseFuture caseIdListc: ' + caseIdList);
        DescribeSObjectResult dr = Case.getSObjectType().getDescribe();
        List<String> fieldList = new List<String>(dr.fields.getMap().keySet());
        String fields = String.join(fieldList, ',');
        String q = 'SELECT ' + fields + ' FROM Case WHERE Id IN :caseIdList';
        for (Case caseObj : Database.query(q)) {
            try {
                CaseComplaintAPI.CaseResponse cr = callUpdateFACase(caseObj);
                if (cr != null && cr.success) {
                    // do nothing
                }
                else {
                    errMessage = String.isNotBlank(errMessage) ? errMessage + '. ' + cr.errors.toString() : cr.errors.toString();
                    System.debug('***CaseComplaintService syncFACaseFuture FAILED TO UPDATE CASE: ' + errMessage);
                    throw new CaseComplaintServiceException('FAILED TO UPDATE CASE: ' + errMessage);
                }
            }
            catch (Exception e) {
                String rBodyStr = rstr, methodStr = mstr, endpointStr = estr;
                errMessage = String.isNotBlank(errMessage) ? errMessage + '. ' + e.getMessage() + '. ' + e.getStackTraceString() : e.getMessage() + '. ' + e.getStackTraceString();
                errMessage = String.isNotBlank(errMessage) ? errMessage + '. Endpoint: ' + methodStr + ' ' + endpointStr : 'Endpoint: ' + methodStr + ' ' + endpointStr;
                errMessage = String.isNotBlank(errMessage) ? errMessage + '. Response Body: ' + rBodyStr : 'Response Body: ' + rBodyStr;
                System.debug('***CaseComplaintService syncFACaseFuture FAILED TO UPDATE CASE: ' + errMessage);
                throw new CaseComplaintServiceException('FAILED TO UPDATE CASE: ' + errMessage);
            }
        }
    }

    public static FA_Integration__mdt getConfig(String operationName) {
        DescribeSObjectResult dr = FA_Integration__mdt.getSObjectType().getDescribe();
        List<String> fieldList = new List<String>(dr.fields.getMap().keySet());
        String fields = String.join(fieldList, ',');
        String q = 'SELECT ' + fields + ' FROM FA_Integration__mdt WHERE DeveloperName = :operationName';
        return Database.query(q);
    }

    public static Map<String, Object> generateCaseExtFromCase(Case caseObj) {
        Map<String, Object> result;
        if (caseObj != null) {
            Datetime todayDt = System.now();
            result = new Map<String, Object>();
            result.put('Id', caseObj.Case_Id_External__c);
            result.put('Name', caseObj.Case_No_External__c);
            result.put('Last_Sync__c', todayDt);
            result.put('Status__c', caseObj.Status);
            result.put('Request_Status__c', caseObj.CHS_Status__c);
            result.put('Sub_Status__c', caseObj.Sub_Status__c);
            result.put('Pending_Status__c', caseObj.Pending_Status__c);
            result.put('Occupation__c', caseObj.Occupation__c);
            result.put('Case_Sensitive_Customer__c', caseObj.Case_Sensitive_Customer__c);
            result.put('Policy_No__c', caseObj.Policy_Number__c);
            result.put('Document_Request_Revise__c', caseObj.Document_Request_Revise__c);
        }
        return result;
    }

    public static Case getCaseById(String caseId) {
        Case caseObj;
        DescribeSObjectResult dr = Case.getSObjectType().getDescribe();
        List<String> fieldList = new List<String>(dr.fields.getMap().keySet());
        String fields = String.join(fieldList, ',');
        String q = 'SELECT ' + fields + ' FROM Case WHERE Id = :caseId ORDER BY CreatedDate DESC';
        List<Case> caseList = Database.query(q);
        if (caseList != null && caseList.size() > 0) caseObj = caseList.get(0);
        return caseObj;
    }

    public class CaseComplaintServiceException extends Exception {}
}