force-app/main/default/objects/Case/fields/Case_Owner_CCC__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_CCC__c</fullName>
    <formula>IF (CreatedBy.Profile.Name != &apos;System Administrator&apos;, 
CreatedBy.FirstName &amp; &apos; &apos;&amp; CreatedBy.LastName, 
Owner:User.FirstName &amp; &apos; &apos;&amp; Owner:User.LastName 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Owner CCC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>Unit department kerja</description>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADS</fullName>
            </value>
            <value>
                <fullName>CCC</fullName>
            </value>
            <value>
                <fullName>CLAIM</fullName>
            </value>
            <value>
                <fullName>CMU</fullName>
            </value>
            <value>
                <fullName>Collection &amp; CR</fullName>
            </value>
            <value>
                <fullName>DMU</fullName>
            </value>
            <value>
                <fullName>DPLK</fullName>
            </value>
            <value>
                <fullName>NB / UW</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Tele Services</fullName>
            </value>
            <value>
                <fullName>Walk In/RO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Policy_Numbers__c</fullName>
    <formula>Contact.Policy_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/InvokeCaseServiceQueueable.cls
public class InvokeCaseServiceQueueable {

    @InvocableMethod(label='Invoke Cases' description='Assessment Cases to Core System.')
    public static void invokeCases(List<String> recordIds){
        
        List<Case> cases = SOQL.of(Case.SObjectType)
            .with('Id, Policy_Numbers__c, Case_Owner_CCC__c, Department__c, Origin, Status, Contact.PolicyApp__c')
            .whereAre(SOQL.Filter.with(Case.Id).isIn(recordIds))
            .toList();
        system.debug('flow nya kepanggil kah?');
        system.debug('recordIds: '+recordIds);
        //System.enqueueJob(new SubmitCaseServiceQueueable(cases));
        system.debug('cases: '+cases);
    }
}