force-app/main/default/objects/Case/fields/Case_Sensitive_Customer__c.field-meta.xml
<CustomField>
    <fullName>Case_Sensitive_Customer__c</fullName>
    <label>Case Sensitive Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CHS_Status__c.field-meta.xml
<CustomField>
    <fullName>CHS_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>In Progress CMU</fullName>
            </value>
            <value>
                <fullName>Assigned to Back Office</fullName>
            </value>
            <value>
                <fullName>In Progress Back Office</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Escalation Rejected</fullName>
            </value>
            <value>
                <fullName>Escalation Approved</fullName>
            </value>
            <value>
                <fullName>BOD Approval</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid</fullName>
            </value>
            <value>
                <fullName>Closed - Valid</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Cust_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Cust_Segmentation__c</fullName>
    <inlineHelpText>Customer Segmentation for AMFS Only</inlineHelpText>
    <label>Cust Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cust_Segmentation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>MTF</fullName>
            </value>
            <value>
                <fullName>Bank Mandiri</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Other Financial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>Insured_Name__c</fullName>
    <formula>Contact.Insured_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insured Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nature_Config__c.field-meta.xml
<CustomField>
    <fullName>Nature_Config__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative procedures</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claim Decision</fullName>
            </value>
            <value>
                <fullName>Comben</fullName>
            </value>
            <value>
                <fullName>Courier Delivery</fullName>
            </value>
            <value>
                <fullName>Courier Investigation</fullName>
            </value>
            <value>
                <fullName>Financial Advisor Service</fullName>
            </value>
            <value>
                <fullName>Forgery</fullName>
            </value>
            <value>
                <fullName>Misappropriation</fullName>
            </value>
            <value>
                <fullName>Misrepresentation</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Non Disclosure</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Policy Duplicate</fullName>
            </value>
            <value>
                <fullName>Policy Retur</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>TM Service</fullName>
            </value>
            <value>
                <fullName>Twisting/Chunning</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>Without Consent</fullName>
            </value>
            <value>
                <fullName>Processing Error</fullName>
            </value>
            <value>
                <fullName>Agent Services</fullName>
            </value>
            <value>
                <fullName>Human Error</fullName>
            </value>
            <value>
                <fullName>Processing Times</fullName>
            </value>
            <value>
                <fullName>Service provided by 3rd parties</fullName>
            </value>
            <value>
                <fullName>Service provided by the internal Staff</fullName>
            </value>
            <value>
                <fullName>Service provided by the Distributors</fullName>
            </value>
            <value>
                <fullName>CS-3rd parties related</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <formula>Contact.Policy_Effective_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Priority_Customer__c.field-meta.xml
<CustomField>
    <fullName>Priority_Customer__c</fullName>
    <formula>Text(Contact.Priority_Customer__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Priority Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sensitive_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sensitive_Customer__c</fullName>
    <formula>Contact.Sensitive_Customer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sensitive Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/AMFSComplaintCase.recordType-meta.xml
<RecordType>
    <fullName>AMFSComplaintCase</fullName>
    <active>true</active>
    <businessProcess>Complaint</businessProcess>
    <label>AMFSComplaintCase</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Cust_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Cust_Segmentation__c</fullName>
    <inlineHelpText>Customer Segmentation for AMFS Only</inlineHelpText>
    <label>Cust Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Regular, Nasabah Aceh</fullName>
            </value>
            <value>
                <fullName>Priority, Nasabah Aceh</fullName>
            </value>
            <value>
                <fullName>Private, Nasabah Aceh</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>Priorit</fullName>
                <isActive>false</isActive>
                <label>Priorit</label>
            </value>
            <value>
                <fullName>Privaate</fullName>
                <isActive>false</isActive>
                <label>Privaate</label>
            </value>
            <value>
                <fullName>Privat</fullName>
                <isActive>false</isActive>
                <label>Privat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>Insured_Name__c</fullName>
    <label>Insured Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Priority_Customer__c.field-meta.xml
<CustomField>
    <fullName>Priority_Customer__c</fullName>
    <label>Priority Customer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sensitive_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sensitive_Customer__c</fullName>
    <label>Sensitive Customer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CaseComplaintViewAttachment_Test.cls
@IsTest
private class CaseComplaintViewAttachment_Test {

    public class MockGetAttachments implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();

            Account accObj = new Account();
            accObj.Name = 'Account AMFS';
            accObj.Entity__c = 'AMFS';
            insert accObj;
            
            Contact contactObj = new Contact();
            contactObj.AccountId = accObj.Id;
            contactObj.LastName = 'Person B';
            contactObj.Phone = '+6281000000014';
            contactObj.Email = 'personb@email.test';
            contactObj.Policy_No__c = '520-1877778';
            contactObj.Insured_Name__c = 'Person B';
            contactObj.Priority_Customer__c = 'No';
            contactObj.Policy_Effective_Date__c = Date.today().addDays(-10);
            contactObj.Cust_Segmentation__c = 'Regular';
            contactObj.MobilePhone = '+6281000000014';
            contactObj.Entity__c = 'AMFS';
            contactObj.Sensitive_Customer__c = 'YES';
            insert contactObj;
            
            /*
            Id entitlementProcessId = [SELECT Id FROM SlaProcess WHERE SObjectType = 'Case' AND Name LIKE '%Entitlement%' ORDER BY CreatedDate DESC LIMIT 1].Id;

            Entitlement ent = new Entitlement();
            ent.AccountId = accObj.Id;
            ent.SLAProcessId = entitlementProcessId;
            ent.Name = 'Entitlement AMFS';
            insert ent;
			*/

            Case caseObj = new Case();
            caseObj.ContactId = contactObj.Id;
            caseObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('AMFSComplaintCase').getRecordTypeId();
            caseObj.CHS_Status__c = 'Revised';
            caseObj.Status = 'Escalated';
            caseObj.Origin = 'SMART FA';
            caseObj.Type = 'Complaint';
            caseObj.Cust_Segmentation__c = 'Regular';
            caseObj.Case_Sensitive_Customer__c = 'YES';
            caseObj.Occupation__c = 'PNS';
            //caseObj.EntitlementId = ent.Id;
            caseObj.Nature_Config__c = 'Service Provide By 3rd Parties';
            caseObj.Category_Config__c = 'CS-3rd parties related';
            caseObj.Business_channel__c = 'TM';
            caseObj.Channel__c = 'Verbal (Call)';
            caseObj.Priority = 'High';
            caseObj.Customer_Signature_Date__c = Date.today();
            caseObj.Delivery_Tracking__c = 'Policy';
            caseObj.Customer__c = 'Customer';
            caseObj.Customer_type__c = 'Regular';
            caseObj.Complainant__c = 'Customer';
            caseObj.Received_date__c = Date.today();
            caseObj.Complaint_type__c = 'Complex Case';
            caseObj.Product__c = 'TM';
            caseObj.Policy_Number__c = '520-1877777';
            insert caseObj;
            
            List<Attachment> attList = new List<Attachment>();
            Attachment attObj = new Attachment();
            attObj.Name = '[v]_KTP_513-8049944_20210507141201.jpg';
            attObj.ParentId = caseObj.Id;
            attObj.IsPrivate = false;
            attObj.ContentType = 'image/jpeg';
            attObj.Body = Blob.valueOf('file-content');
            attObj.Description = 'KTP';
            attList.add(attObj);
            insert attList;

            List<Attachment> attCheckList = [SELECT Id, ParentId, Name, IsPrivate, ContentType, Description, LastModifiedDate, Parent.Name, LastModifiedBy.Name FROM Attachment WHERE ParentId = :caseObj.id ORDER BY CreatedDate ASC];
            String jsonBody = JSON.serialize(attCheckList);
            //String jsonBody = JSON.serialize(attList);
            System.debug('***MockGetAttachments: jsonBody : ' + jsonBody);
            res.setBody(jsonBody);
            res.setStatus('OK');
            res.setStatusCode(200);
            res.setHeader('cache-control', 'no-cache');
            return res;
        }
    }

    public class MockSyncAttachments implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            CaseComplaintAPI.SyncAttachmentResponse saRes = new CaseComplaintAPI.SyncAttachmentResponse();
            saRes.success = true;
            saRes.errors = null;
            saRes.parent_id = '5000k00000DF085';
            String jsonBody = JSON.serialize(saRes);
            res.setBody(jsonBody);
            res.setStatus('OK');
            res.setStatusCode(200);
            res.setHeader('cache-control', 'no-cache');
            return res;
        }
    }

    static testmethod void testLoadViewAttachmentPage() {
        Test.startTest();
        Account accObj = new Account();
        accObj.Name = 'Account AMFS';
        accObj.Entity__c = 'AMFS';
        insert accObj;
        
        Contact contactObj = new Contact();
        contactObj.AccountId = accObj.Id;
        contactObj.LastName = 'Person A';
        contactObj.Phone = '+6281000000013';
        contactObj.Email = 'persona@email.test';
        contactObj.Policy_No__c = '520-1877777';
        contactObj.Insured_Name__c = 'Person A';
        contactObj.Priority_Customer__c = 'No';
        contactObj.Policy_Effective_Date__c = Date.today().addDays(-10);
        contactObj.Cust_Segmentation__c = 'Regular';
        contactObj.MobilePhone = '+6281000000013';
        contactObj.Entity__c = 'AMFS';
        contactObj.Sensitive_Customer__c = 'YES';
        insert contactObj;
        
        /*
        Id entitlementProcessId = [SELECT Id FROM SlaProcess WHERE SObjectType = 'Case' AND Name LIKE '%Entitlement%' ORDER BY CreatedDate DESC LIMIT 1].Id;

        Entitlement ent = new Entitlement();
        ent.AccountId = accObj.Id;
        ent.SLAProcessId = entitlementProcessId;
        ent.Name = 'Entitlement AMFS';
        insert ent;
		*/

        Case caseObj = new Case();
        caseObj.ContactId = contactObj.Id;
        caseObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('AMFSComplaintCase').getRecordTypeId();
        caseObj.CHS_Status__c = 'Revised';
        caseObj.Status = 'Escalated';
        caseObj.Origin = 'SMART FA';
        caseObj.Type = 'Complaint';
        caseObj.Cust_Segmentation__c = 'Regular';
        caseObj.Case_Sensitive_Customer__c = 'YES';
        caseObj.Occupation__c = 'PNS';
        //caseObj.EntitlementId = ent.Id;
        caseObj.Nature_Config__c = 'Service Provide By 3rd Parties';
        caseObj.Category_Config__c = 'CS-3rd parties related';
        caseObj.Business_channel__c = 'TM';
        caseObj.Channel__c = 'Verbal (Call)';
        caseObj.Priority = 'High';
        caseObj.Customer_Signature_Date__c = Date.today();
        caseObj.Delivery_Tracking__c = 'Policy';
        caseObj.Customer__c = 'Customer';
        caseObj.Customer_type__c = 'Regular';
        caseObj.Complainant__c = 'Customer';
        caseObj.Received_date__c = Date.today();
        caseObj.Complaint_type__c = 'Complex Case';
        caseObj.Product__c = 'TM';
        caseObj.Policy_Number__c = '520-1877777';
        insert caseObj;

        String attFilename = CaseComplaintAttachmentService.ATT_SUBMITTED.replaceAll(CaseComplaintAttachmentService.DELIMITER, '');
        attFilename += CaseComplaintAttachmentService.DELIMITER + 'KTP'.replaceAll(CaseComplaintAttachmentService.DELIMITER, '');
        attFilename += CaseComplaintAttachmentService.DELIMITER + '520-1877777'.replaceAll(CaseComplaintAttachmentService.DELIMITER, '');
        String timestampStr1 = System.now().format('yyyyMMddHHmmss');
        String filename1 = attFilename + CaseComplaintAttachmentService.DELIMITER + timestampStr1 + '.jpg';

        Attachment attObj = new Attachment();
        attObj.ParentId = caseObj.Id;
        attObj.Name = filename1;
        attObj.IsPrivate = false;
        attObj.ContentType = 'image/jpeg';
        attObj.Body = Blob.valueOf('blob-contents-of-ktp');
        attObj.Description = 'KTP';
        insert attObj;

        CaseComplaintService.mock = new MockGetAttachments();
        PageReference pageRef = Page.CaseComplaintViewAttachment;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(caseObj.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
        CaseComplaintViewAttachmentController ccvac = new CaseComplaintViewAttachmentController(sc);

        ccvac.retrieveAttachment();
        Double offset = ccvac.offset;
        System.assert(String.isNotBlank(ccvac.attListStr));
        System.assert(offset != null);
        Test.stopTest();
    }

    static testMethod void testSyncAttachments() {
        Test.startTest();
        Account accObj = new Account();
        accObj.Name = 'Account AMFS';
        accObj.Entity__c = 'AMFS';
        insert accObj;
        
        Contact contactObj = new Contact();
        contactObj.AccountId = accObj.Id;
        contactObj.LastName = 'Person A';
        contactObj.Phone = '+6281000000013';
        contactObj.Email = 'persona@email.test';
        contactObj.Policy_No__c = '520-1877777';
        contactObj.Insured_Name__c = 'Person A';
        contactObj.Priority_Customer__c = 'No';
        contactObj.Policy_Effective_Date__c = Date.today().addDays(-10);
        contactObj.Cust_Segmentation__c = 'Regular';
        contactObj.MobilePhone = '+6281000000013';
        contactObj.Entity__c = 'AMFS';
        contactObj.Sensitive_Customer__c = 'YES';
        insert contactObj;
        
        /*
        Id entitlementProcessId = [SELECT Id FROM SlaProcess WHERE SObjectType = 'Case' AND Name LIKE '%Entitlement%' ORDER BY CreatedDate DESC LIMIT 1].Id;

        Entitlement ent = new Entitlement();
        ent.AccountId = accObj.Id;
        ent.SLAProcessId = entitlementProcessId;
        ent.Name = 'Entitlement AMFS';
        insert ent;
		*/

        Case caseObj = new Case();
        caseObj.ContactId = contactObj.Id;
        caseObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('AMFSComplaintCase').getRecordTypeId();
        caseObj.CHS_Status__c = 'Revised';
        caseObj.Status = 'Escalated';
        caseObj.Origin = 'SMART FA';
        caseObj.Type = 'Complaint';
        caseObj.Cust_Segmentation__c = 'Regular';
        caseObj.Case_Sensitive_Customer__c = 'YES';
        caseObj.Occupation__c = 'PNS';
        //caseObj.EntitlementId = ent.Id;
        caseObj.Nature_Config__c = 'Service Provide By 3rd Parties';
        caseObj.Category_Config__c = 'CS-3rd parties related';
        caseObj.Business_channel__c = 'TM';
        caseObj.Channel__c = 'Verbal (Call)';
        caseObj.Priority = 'High';
        caseObj.Customer_Signature_Date__c = Date.today();
        caseObj.Delivery_Tracking__c = 'Policy';
        caseObj.Customer__c = 'Customer';
        caseObj.Customer_type__c = 'Regular';
        caseObj.Complainant__c = 'Customer';
        caseObj.Received_date__c = Date.today();
        caseObj.Complaint_type__c = 'Complex Case';
        caseObj.Product__c = 'TM';
        caseObj.Policy_Number__c = '520-1877777';
        insert caseObj;

        PageReference pageRef = Page.CaseComplaintViewAttachment;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(caseObj.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
        CaseComplaintViewAttachmentController ccvac = new CaseComplaintViewAttachmentController(sc);

        PageReference pr = ccvac.syncAttachments();
        System.assert(pr == null);
        CaseComplaintService.mock = new MockSyncAttachments();
        pr = ccvac.syncAttachments();
        System.assert(pr == null);
        Test.stopTest();
    }
}