force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Nature__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Others - Others</fullName>
            </value>
            <value>
                <fullName>Courier Delivery - Delivery</fullName>
            </value>
            <value>
                <fullName>Courier Delivery - Inquiry Delivery</fullName>
            </value>
            <value>
                <fullName>Courier Delivery - Inquiry Receipt</fullName>
            </value>
            <value>
                <fullName>Claim Decision</fullName>
            </value>
            <value>
                <fullName>Claim Delay</fullName>
            </value>
            <value>
                <fullName>Financial Advisor Service</fullName>
            </value>
            <value>
                <fullName>Forgery</fullName>
            </value>
            <value>
                <fullName>Misappropriation</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - Lack of Professional Knowledge</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - Misrepresentation</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - Premium Holiday</fullName>
            </value>
            <value>
                <fullName>Misrepresentation - TM</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Non Disclosure</fullName>
            </value>
            <value>
                <fullName>Facility Service</fullName>
            </value>
            <value>
                <fullName>Collector</fullName>
            </value>
            <value>
                <fullName>Courtesy</fullName>
            </value>
            <value>
                <fullName>Employee Training</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hardware Problem - IT</fullName>
            </value>
            <value>
                <fullName>Information - Marketing</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>No Follow Up</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Service - Activity Support</fullName>
            </value>
            <value>
                <fullName>Service Facility</fullName>
            </value>
            <value>
                <fullName>Skill/Product Knowledge</fullName>
            </value>
            <value>
                <fullName>Soft ware Problem - IT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Email_Text_Holiday_Weekend__c.field-meta.xml
<CustomField>
    <fullName>Email_Text_Holiday_Weekend__c</fullName>
    <label>Email Text Holiday/Weekend</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Entity_Backup__c.field-meta.xml
<CustomField>
    <fullName>Entity_Backup__c</fullName>
    <label>Entity Backup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailAutoReply.cls
public class EmailAutoReply {   
  //capture the user id
    public ID caseID {get; set;}
    //public Email_SMS_Template__c emailTemplate = new Email_SMS_Template__c();
    public Case emailTemplate = new Case();

    public Case getEmailTemplate() {
        //emailTemplate = [SELECT Id, Name, Email_Header__c, Email_Body__c, Email_Footer__c, Category__c, Entity__c, CreatedDate FROM Case WHERE Id =: idEmailTemplate];        
        emailTemplate = [SELECT Id, CaseNumber, Email_Text_Holiday_Weekend__c, Entity_Backup__c, CreatedDate FROM Case WHERE Id =: caseID];        
        return emailTemplate;
    }
}