force-app/main/default/objects/Case/fields/CHS_Status__c.field-meta.xml
<CustomField>
    <fullName>CHS_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>In Progress CMU</fullName>
            </value>
            <value>
                <fullName>Assigned to Back Office</fullName>
            </value>
            <value>
                <fullName>In Progress Back Office</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Escalation Rejected</fullName>
            </value>
            <value>
                <fullName>Escalation Approved</fullName>
            </value>
            <value>
                <fullName>BOD Approval</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid</fullName>
            </value>
            <value>
                <fullName>Closed - Valid</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ComplaintRequestStatusController.cls
public class ComplaintRequestStatusController {
	public Case chsCase {get;set;}
	public List <String> requestStatusList {get; set;}
	public List <String> StatusList {get; set;}
	public String requestStatus {get; set;}
	public String Status {get; set;} 
	public String requestStatusListJSON {get; set;}
	public String StatusListJSON {get; set;}
	
    public ComplaintRequestStatusController(ApexPages.StandardController controller) {
    	
    	//caseId = controller.getID();
    	chsCase = new Case();
    	Case complaintCase = (Case)controller.getRecord();
    	
    	try {
    	chsCase = [SELECT CHS_Status__c, Entity__c, Status FROM Case WHERE Id = :complaintCase.Id];
			            
    	requestStatus = chsCase.CHS_Status__c;
    	status = chsCase.Status;
    	
    	Schema.DescribeFieldResult fieldResult = Case.CHS_Status__c.getDescribe();    
        List<Schema.picklistEntry> ple = fieldResult.getPicklistValues();    
        
        requestStatusList = new List <String>();
        for(Schema.picklistEntry f:ple)    
        {    
            //options.add(new selectOption(f.getLabel(),f.getValue()));  
            requestStatusList.add (f.getValue()) ;
        }
        
        requestStatusListJSON = JSON.serialize(requestStatusList);
        
        //Get alll Status picklist for Case Request (added by Hamfry)
        Schema.DescribeFieldResult fieldResult2 = Case.Status.getDescribe();    
        List<Schema.picklistEntry> plEntry = fieldResult2.getPicklistValues();    
        
        StatusList = new List <String>();
        
        for(Schema.picklistEntry f: plEntry){    
            StatusList.add (f.getValue()) ;
        }
        
        StatusListJSON = JSON.serialize(StatusList);
        
        system.debug('============ requestStatusList : ' + requestStatusList);
    	}
    	catch (Exception e) {
    		system.debug('============ errorMessage : ' + e.getMessage());
    	}
    	system.debug('============ requestStatus : ' + requestStatus);
    }
    
}