force-app/main/default/objects/Case/fields/CHS_Status__c.field-meta.xml
<CustomField>
    <fullName>CHS_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Incomplete Information</fullName>
            </value>
            <value>
                <fullName>Revised</fullName>
            </value>
            <value>
                <fullName>In Progress CMU</fullName>
            </value>
            <value>
                <fullName>Assigned to Back Office</fullName>
            </value>
            <value>
                <fullName>In Progress Back Office</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Escalation Rejected</fullName>
            </value>
            <value>
                <fullName>Escalation Approved</fullName>
            </value>
            <value>
                <fullName>BOD Approval</fullName>
            </value>
            <value>
                <fullName>Closed - Invalid</fullName>
            </value>
            <value>
                <fullName>Closed - Valid</fullName>
            </value>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Entity_Backup__c.field-meta.xml
<CustomField>
    <fullName>Entity_Backup__c</fullName>
    <label>Entity Backup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/General_Attitude__c.field-meta.xml
<CustomField>
    <fullName>General_Attitude__c</fullName>
    <label>Customer Mood</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NonPP__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Happy</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Angry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PIC_Department_LU__c.field-meta.xml
<CustomField>
    <fullName>PIC_Department_LU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>user to assign (especially for request)</inlineHelpText>
    <label>PIC Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>notContain</operation>
            <value>Admin</value>
        </filterItems>
        <filterItems>
            <field>User.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CasesDNMP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Root_Cause__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause__c</fullName>
    <label>Root Cause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISASTER</fullName>
            </value>
            <value>
                <fullName>FA</fullName>
            </value>
            <value>
                <fullName>MP CLM</fullName>
            </value>
            <value>
                <fullName>MP POS</fullName>
            </value>
            <value>
                <fullName>SALAH SMS</fullName>
            </value>
            <value>
                <fullName>E-DOCS ERROR</fullName>
            </value>
            <value>
                <fullName>OTHER APPS ERROR</fullName>
            </value>
            <value>
                <fullName>OTHER CASES</fullName>
            </value>
            <value>
                <fullName>NO ERROR</fullName>
            </value>
            <value>
                <fullName>DIRECT GIFT</fullName>
            </value>
            <value>
                <fullName>AXA MANDIRI TELEKONSULTASI</fullName>
            </value>
            <value>
                <fullName>HALODOC</fullName>
            </value>
            <value>
                <fullName>PERFECT PARTNER [Customer Portal]</fullName>
            </value>
            <value>
                <fullName>PERFECT REWARD [Loyalty Point]</fullName>
            </value>
            <value>
                <fullName>MP QCTM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/MassUploadCases_Test.cls
@isTest(SeeAllData=true)
public class MassUploadCases_Test {

    private static UserRole userRole = [SELECT Id FROM UserRole WHERE Name = 'DMU Manager AMFS' LIMIT 1];
    private static User user = [SELECT Id FROM User WHERE UserRoleId =: userRole.id and isActive = true LIMIT 1];

    private static List<Case> caseRequests = [SELECT Id, CaseNumber FROM Case WHERE Type = 'Request' AND Status = 'New' AND Entity__c = 'AMFS' LIMIT 2];
    private static String caseNumberRequest1 = caseRequests[0].CaseNumber;
    private static String caseNumberRequest = caseRequests[1].CaseNumber;
    private static String caseNumberRequest2 = caseNumberRequest.substring(1);

    private static List<Case> caseComplaints = [SELECT Id, CaseNumber FROM Case WHERE Type = 'Complaint' AND CHS_Status__c = 'New' AND Entity__c = 'AMFS' LIMIT 2];
    private static String caseNumberComplaint1 = caseComplaints[0].CaseNumber;
    private static String caseNumberComplaint = caseComplaints[1].CaseNumber;
    private static String caseNumberComplaint2 = caseNumberComplaint.substring(1);
    
    private static String policyNo = '519-0123123';

    static testMethod void initPage() {
        System.runAs(user) {
            Case cs = new Case();
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            MassUploadCasesController controller = new MassUploadCasesController(sc);
            Test.setCurrentPage(Page.MassUploadCases);
            controller.getEntityList();
            controller.getStatusList();
            controller.getTypeList();
            controller.getCaseTypeList();
            controller.getPriorityList();
            controller.getGeneralAttitudeList();
            controller.getRootCauseList();
            controller.getDepartmentList();
            controller.getOriginList();
        }
    }
    
    static void insertContact(){
        Contact con = new Contact(LastName='Just Test 6',
                                   Policy_No__c ='519-0123123');
        insert con;
    }
    
    // RES NEW REQUEST
    static testMethod void massInquiryUpload() {
        
        System.runAs(user) {
            System.debug('Current User: ' + UserInfo.getUserName());
            // run as DMU Supervisor
            Case cs = new Case();
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            MassUploadCasesController controller = new MassUploadCasesController(sc);
            insertContact();
            controller.csDepartment = 'CCC';
            controller.cs.Entity_Backup__c = 'AMFS';
            controller.cs.Type = 'Inquiry';
            controller.cs.Status = 'New';
            controller.cs.Origin = 'Email';
            controller.cs.General_Attitude__c = 'Happy';
            controller.cs.Priority = 'High';
            controller.cs.Root_Cause__c = 'DISASTER';
            controller.checkRecordType();

            controller.massInqUploadfileSize = 1;
            controller.massInqUploadfileName = 'test_case1.csv';
            controller.massInqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+ policyNo +',nasabah req duplicate policy ke alamat DSN PONCO RT004/RW001 DESA SUCIHARJO KEC. PARENGAN KAB. TUBAN 62366 (DEKAT MASJID TONANG BONANG) UP. BPK. MOCH. MAKIN dan nomor yang dapat di hubungi 082330530593,Test');
            controller.massCaseUpload();

            // negative test file size
            controller.massInqUploadfileSize = 0;
            controller.massInqUploadfileName = 'test_case1.csv';
            controller.massInqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+ policyNo +',nasabah req duplicate policy ke alamat DSN PONCO RT004/RW001 DESA SUCIHARJO KEC. PARENGAN KAB. TUBAN 62366 (DEKAT MASJID TONANG BONANG) UP. BPK. MOCH. MAKIN dan nomor yang dapat di hubungi 082330530593,Test');
            controller.massCaseUpload();

            // negative test file name
            controller.massInqUploadfileSize = 1;
            controller.massInqUploadfileName = 'test_case1.xlsx';
            controller.massInqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+ policyNo +',nasabah req duplicate policy ke alamat DSN PONCO RT004/RW001 DESA SUCIHARJO KEC. PARENGAN KAB. TUBAN 62366 (DEKAT MASJID TONANG BONANG) UP. BPK. MOCH. MAKIN dan nomor yang dapat di hubungi 082330530593,Test');
            controller.massCaseUpload();

            // negative test data case number is not numeric
            controller.massInqUploadfileSize = 1;
            controller.massInqUploadfileName = 'test_case1.csv';
            controller.massInqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+policyNo+',nasabah req duplicate policy ke alamat DSN PONCO RT004/RW001 DESA SUCIHARJO KEC. PARENGAN KAB. TUBAN 62366 (DEKAT MASJID TONANG BONANG) UP. BPK. MOCH. MAKIN dan nomor yang dapat di hubungi 082330530593,Test');
            controller.massCaseUpload();

            // negative test data case number is empty
            controller.massInqUploadfileSize = 1;
            controller.massInqUploadfileName = 'test_case1.csv';
            controller.massInqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+policyNo+',nasabah req duplicate policy 082330530593,Test');
            controller.massCaseUpload();

            // negative test data case number is not found
            controller.massInqUploadfileSize = 1;
            controller.massInqUploadfileName = 'test_case1.csv';
            controller.massInqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+policyNo+',nasabah req duplicate policy 082330530593\n'+ policyNo +',nasabah req duplicate policy di hubungi 082330530593\n02551822,BANJAR KEBILBIL PACUNG DESA BELALANG KEC. KEDIRI KAB. TABANAN - BALI 82171 (085237471985),Test');
            controller.massCaseUpload();

            // postive test
            controller.massInqUploadfileSize = 1;
            controller.massInqUploadfileName = 'test_case1.csv';
            controller.massInqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+ policyNo +',nasabah req duplicate policy ke alamat DSN PONCO RT004/RW001 DESA SUCIHARJO KEC. PARENGAN KAB. TUBAN 62366 (DEKAT MASJID TONANG BONANG) UP. BPK. MOCH. MAKIN dan nomor yang dapat di hubungi 082330530593,Test');
            controller.massCaseUpload();
        }
    }

    static testMethod void massCHSUpload() {
        System.runAs(user) {
            Case cs = new Case();
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            MassUploadCasesController controller = new MassUploadCasesController(sc);
            Test.setCurrentPage(Page.MassUploadCases);
            insertContact();
            controller.csDepartment = 'CCC';
            controller.cs.Entity_Backup__c = 'AFI';
            controller.cs.Type = 'Complaint';
            controller.cs.Status = 'New';
            controller.cs.Origin = 'Email';
            controller.cs.General_Attitude__c = 'Happy';
            controller.cs.Priority = 'High';
            controller.cs.Root_Cause__c = 'DISASTER';
            controller.isDisplayAFI = true;
            controller.AFIRequired = true;
            controller.AMFS_AFIRequired = true;
            controller.AMFSRequired = false;
            controller.checkRecordType();
            
            // catch
            controller.massCompUploadfileSize = 1;
            controller.massCompUploadFileName = 'test_case2.csv';
            controller.massCompUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            controller.massCaseUpload();

            // invalid file
            controller.massCompUploadfileSize = 0;
            controller.massCompUploadFileName = 'test_case2.xlxs';
            controller.massCompUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            controller.massCaseUpload();

            // invalid data
            controller.massCompUploadfileSize = 1;
            controller.massCompUploadFileName = 'test_case2.csv';
            controller.massCompUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            controller.massCaseUpload();

            // positive
            controller.massCompUploadfileSize = 1;
            controller.massCompUploadFileName = 'test_case2.csv';
            controller.massCompUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+ policyNo +',req speed up to NCS Test 7,Test');
            controller.massCaseUpload();
        }
    }
    
    static testMethod void massRequestUpload() {
        System.runAs(user) {
            Case cs = new Case();
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            MassUploadCasesController controller = new MassUploadCasesController(sc);
            Test.setCurrentPage(Page.MassUploadCases);
            insertContact();
            controller.csDepartment = 'CCC';
            controller.cs.Entity_Backup__c = 'AMFS';
            controller.cs.Type = 'Request';
            controller.cs.Status = 'New';
            controller.cs.Origin = 'Email';
            controller.cs.General_Attitude__c = 'Happy';
            controller.cs.Priority = 'High';
            controller.cs.Root_Cause__c = 'DISASTER';
            controller.cs.Case_Type__c = 'Request_CCC_Call Back DMU';
            controller.cs.Case_Type_Config__c = 'Request_CCC_Call Back DMU';
            controller.cs.PIC_Department_LU__c = UserInfo.getUserId();
            controller.checkRecordType();
            
            // catch
            controller.massReqUploadfileSize = 1;
            controller.massReqUploadFileName = 'test_case2.csv';
            controller.massReqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            controller.massCaseUpload();

            // invalid file
            controller.massReqUploadfileSize = 0;
            controller.massReqUploadFileName = 'test_case2.xlxs';
            controller.massReqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            controller.massCaseUpload();

            // invalid data
            controller.massReqUploadfileSize = 1;
            controller.massReqUploadFileName = 'test_case2.csv';
            controller.massReqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            controller.massCaseUpload();

            // positive
            controller.massReqUploadfileSize = 1;
            controller.massReqUploadFileName = 'test_case2.csv';
            controller.massReqUploadFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+ policyNo +',req speed up to NCS Test 7,Test');
            controller.massCaseUpload();
        }
    }
    
    static testMethod void reqCloseUpload() {
        System.runAs(user) {
            Case cs = new Case();
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            MassUploadCasesController controller = new MassUploadCasesController(sc);
            Test.setCurrentPage(Page.MassUploadCases);
            insertContact();
            controller.csDepartment = 'CCC';
            controller.cs.Entity_Backup__c = 'AMFS';
            controller.cs.Type = 'Request';
            controller.cs.Status = 'Closed';
            controller.cs.Origin = 'Email';
            controller.cs.General_Attitude__c = 'Happy';
            controller.cs.Priority = 'High';
            controller.cs.Root_Cause__c = 'DISASTER';
            controller.checkRecordType();
            
            // catch
            controller.reqCloseFileSize = 1;
            controller.reqCloseFileName = 'test_case2.csv';
            controller.reqCloseFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            //controller.reqCloseUpload();

            // invalid file
            controller.reqCloseFileSize = 0;
            controller.reqCloseFileName = 'test_case2.xlxs';
            controller.reqCloseFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            //controller.reqCloseUpload();

            // invalid data
            controller.reqCloseFileSize = 1;
            controller.reqCloseFileName = 'test_case2.csv';
            controller.reqCloseFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n' + policyNo + ',"REQ SPEED UP TO KURIR KE Dr. TOM layanan 119 gedung adhyatma, lantai 5 KEMENKES republik indonesia jl. hr rasuna said blok. X5, kav.4-9 jakarta selatan.12950",Test');
            //controller.reqCloseUpload();

            // positive
            controller.reqCloseFileSize = 1;
            controller.reqCloseFileName = 'test_case2.csv';
            controller.reqCloseFileBody = Blob.valueOf('REQUEST_NO,Subject,Description\n'+ policyNo +',req speed up to NCS Test 7,Test');
            //controller.reqCloseUpload();
        }
    }
}