force-app/main/default/objects/Case/fields/Complaint_type__c.field-meta.xml
<CustomField>
    <fullName>Complaint_type__c</fullName>
    <label>Complaint type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complex Case</fullName>
            </value>
            <value>
                <fullName>Simple</fullName>
            </value>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Potensial Complaint (MAGI)</fullName>
            </value>
            <value>
                <fullName>Potential Complaint</fullName>
            </value>
            <value>
                <fullName>Soft Complaint</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_type__c.field-meta.xml
<CustomField>
    <fullName>Customer_type__c</fullName>
    <label>Customer type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Priority Banking Customer</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Mandiri Visa</fullName>
            </value>
            <value>
                <fullName>Sensitive Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Nature_Config__c.field-meta.xml
<CustomField>
    <fullName>Nature_Config__c</fullName>
    <label>Nature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative procedures</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Claim Decision</fullName>
            </value>
            <value>
                <fullName>Comben</fullName>
            </value>
            <value>
                <fullName>Courier Delivery</fullName>
            </value>
            <value>
                <fullName>Courier Investigation</fullName>
            </value>
            <value>
                <fullName>Financial Advisor Service</fullName>
            </value>
            <value>
                <fullName>Forgery</fullName>
            </value>
            <value>
                <fullName>Misappropriation</fullName>
            </value>
            <value>
                <fullName>Misrepresentation</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Non Disclosure</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Policy Duplicate</fullName>
            </value>
            <value>
                <fullName>Policy Retur</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>TM Service</fullName>
            </value>
            <value>
                <fullName>Twisting/Chunning</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>Without Consent</fullName>
            </value>
            <value>
                <fullName>Processing Error</fullName>
            </value>
            <value>
                <fullName>Agent Services</fullName>
            </value>
            <value>
                <fullName>Human Error</fullName>
            </value>
            <value>
                <fullName>Processing Times</fullName>
            </value>
            <value>
                <fullName>Service provided by 3rd parties</fullName>
            </value>
            <value>
                <fullName>Service provided by the internal Staff</fullName>
            </value>
            <value>
                <fullName>Service provided by the Distributors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchCMUReminderNotification_Test.cls
@isTest(seeAllData = true)
public class SchCMUReminderNotification_Test {
    public static testMethod void test1(){
        SchCMUReminderNotification runner = new SchCMUReminderNotification();
        runner.execute(null);
    }
    public static testmethod void testInsert(){
        Test.startTest();
        
        
        Case cs = new Case();
        cs.Status='New';
        cs.Complaint_type__c='Priority';
        cs.Nature_Config__c='Processing Times';
        cs.ContactId='0030K00002CKOYjQAP';
        cs.Customer_type__c='Priority Banking Customer';
        insert cs;
        
        String jobId = System.schedule('SchSendWhatsappLog Test', Label.SchSendWhatssapLog_Cron, new SchCMUReminderNotification());

        Test.stopTest();
    }
    
}