force-app/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>Unit department kerja</description>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADS</fullName>
            </value>
            <value>
                <fullName>CCC</fullName>
            </value>
            <value>
                <fullName>CLAIM</fullName>
            </value>
            <value>
                <fullName>CMU</fullName>
            </value>
            <value>
                <fullName>Collection &amp; CR</fullName>
            </value>
            <value>
                <fullName>DMU</fullName>
            </value>
            <value>
                <fullName>DPLK</fullName>
            </value>
            <value>
                <fullName>NB / UW</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Tele Services</fullName>
            </value>
            <value>
                <fullName>Walk In/RO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <defaultValue>&quot;CS&quot;</defaultValue>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Named_User__c.field-meta.xml
<CustomField>
    <fullName>Named_User__c</fullName>
    <label>Named User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/popupUserOnCaseClassTest.cls
@isTest
public class popupUserOnCaseClassTest {
    public static testMethod void clickButton() {
        Case cs = new Case();
        cs.Subject = 'Subject Test Case';
        cs.Division__c = 'CCC';
        cs.Named_User__c = 'test';
        insert cs;
        
        Department__c d = new Department__c();
        d.name = 'test1';
        insert d;
        
        //Case_Internal_Comment__c cic = new Case_Internal_Comment__c();
        Named_User__c nu = new Named_User__c();
        nu.Name = 'test';
        nu.Department__c = d.id;
        insert nu;
        
        Test.setCurrentPage(Page.popupUserOnCase);
        ApexPages.StandardController stdController = new ApexPages.StandardController(cs);
        popupUserOnCaseClass popCls = new popupUserOnCaseClass(stdController);
		popCls.cic.Named_User__c = nu.id;
        popCls.updateCase();
    }
}