force-app/main/default/objects/Case/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <defaultValue>&quot;CS&quot;</defaultValue>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Entity_Backup__c.field-meta.xml
<CustomField>
    <fullName>Entity_Backup__c</fullName>
    <label>Entity Backup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated_Flow__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Flow__c</fullName>
    <inlineHelpText>Flow Escalation by Department</inlineHelpText>
    <label>Escalated Flow</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated_Flow_TAT__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Flow_TAT__c</fullName>
    <label>Escalated Flow TAT</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated_Step__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Step__c</fullName>
    <label>Escalated Step</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated_to_History__c.field-meta.xml
<CustomField>
    <fullName>Escalated_to_History__c</fullName>
    <label>Escalated to - History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Internal_Comment__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comment__c</fullName>
    <label>Internal Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Comment__c.field-meta.xml
<CustomField>
    <fullName>Last_Comment__c</fullName>
    <label>Last Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Named_User__c.field-meta.xml
<CustomField>
    <fullName>Last_Named_User__c</fullName>
    <label>Last Named User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Named_User__c.field-meta.xml
<CustomField>
    <fullName>Named_User__c</fullName>
    <label>Named User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TAT__c.field-meta.xml
<CustomField>
    <fullName>TAT__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Value based on Master Case Type Regional</description>
    <label>TAT</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CIC_InitialTest.cls
@isTest
public class CIC_InitialTest {
    public static testMethod void initRecord() {
        Case cs = new Case();
        cs.Case_Type__c = 'MV Claim Report 2';
        cs.Internal_Comment__c = 'Internal Comment';
        cs.Last_Comment__c = null;
        cs.OwnerId = UserInfo.getUserId();
        cs.Escalated_to_History__c = 'Escalated';
        cs.IsEscalated = true;
        cs.Division__c = 'CS';
        cs.Escalated_Step__c = 1;
        cs.named_user__c ='Taufik';
        cs.last_named_user__c ='Taufik';
        cs.Status = 'New';
        cs.Entity_Backup__c = 'AFI';
        cs.Escalated_Flow__c = '{"1":"Agency","2":"null","3":"null","4":"null","5":"null"}';
        cs.Escalated_Flow_TAT__c = '{"1":"3","2":"0","3":"0","4":"0","5":"0"}';
        insert cs;
        
        Case_Internal_Comment__c cic = new Case_Internal_Comment__c();
        cic.Case__c = cs.Id;
		cic.Division__c = 'CS';
        cic.Internal_Comment__c = 'CIC Internal Comment';
        cic.Escalated_Step__c = 2;
        cic.Auto_Next_Step__c = true;
        cic.TAT__c = 3;
        
        insert cic;
    }
}