force-app/main/default/objects/Case/fields/Entity_Backup__c.field-meta.xml
<CustomField>
    <fullName>Entity_Backup__c</fullName>
    <label>Entity Backup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/MOT__c.field-meta.xml
<CustomField>
    <fullName>MOT__c</fullName>
    <label>MOT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PIC_Department_LU__c.field-meta.xml
<CustomField>
    <fullName>PIC_Department_LU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>user to assign (especially for request)</inlineHelpText>
    <label>PIC Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>notContain</operation>
            <value>Admin</value>
        </filterItems>
        <filterItems>
            <field>User.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CasesDNMP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Policy_Numbers__c</fullName>
    <formula>Contact.Policy_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Policy Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Product_Code_Plan__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Product_Code_Plan__c</fullName>
    <label>Product Code Plan</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/WS_TransferStatusFlips.cls
@RestResource(urlMapping='/TransferStatus/*')
global class WS_TransferStatusFlips {
    @HttpPOST
    global static void UpdateTransferStatus(String policy_number, String claim_number, String transfer_status, String transfer_date){
        String status = '';
        String codeReturn = '';
        String messageReturn = '';
        
        String optyId = '';
        String bodyReq = ''; 
        String jsonHeader= '';
        String jsonParam= '';
        
        try {  
            RestRequest req = RestContext.request;
            Map<String, Object> getHeaders = req.headers;
            jsonHeader = JSON.serialize(getHeaders);
            
            
            List<Contact> cc = [select id, name, PolicyApp__c, Policy_No__c, WelcomeCall_Product_Code_Plan__c from contact where Policy_No__c =: policy_number limit 1];
                        
            if (string.isBlank(policy_number)) {
                codeReturn = '400';
                status = 'Error';
                messageReturn = 'policy number cannont be blank!';
                
            }else if (string.isBlank(claim_number)) {
                codeReturn = '400';
                status = 'Error';
                messageReturn = 'claim number cannont be blank!';
            } else {
                if(cc.size() == 0){
                    codeReturn = '400';
                    status = 'Error';
                    messageReturn = 'Contact Not Found';
                }else{
                    String product =  cc[0].WelcomeCall_Product_Code_Plan__c;
                    List<ICF_Parameter__c> icfParams = [select id, name, Exclude_Product_Plan_Code__c, RecordType.Name from ICF_Parameter__c where RecordType.Name = 'Master - qualtrics' and Exclude_Product_Plan_Code__c includes (:product)];
                    
                    List<Case> cs_old = [select id, Status, Subject, MOT__c, Description from Case where Policy_Numbers__c =:policy_number and Case_Type__c = 'Request_Claim_Payment' and status != 'Closed' limit 1];
                    if(icfParams.size() != 0){
                        //case not created excluded product
                    }
                    else{
                        if(cs_old.size() > 0){
                            for(Case c:cs_old){
                                c.Status = 'Closed';
                                c.Subject = c.Subject + ' / ICF for Claim No '+ claim_number;
                                c.MOT__c = 'I Claim';
                                c.Case_Type__c = 'Request_Claim_Payment';
                                c.Case_Type_Config__c = 'Request_Claim_Payment';
                                if(c.Description !=null){ c.Description = c.Description + '/ Transfer Status: ' + transfer_status + ' / Transfer Date: ' + transfer_date;}
                                else{ c.Description = 'Transfer Status: ' + transfer_status + ' / Transfer Date: ' + transfer_date;}
                                
                                if(!System.test.isrunningtest()) update c;
                            }
                        }else{
                            RecordType rt = [select Id, Name from RecordType where sObjectType='Case' and name = 'RequestAMFSCase' limit 1];
                            User usr = [select id, name from user where name = 'Claim' limit 1];
                            Case cs = new Case();
                            cs.Policy_Number__c = cc[0].Policy_No__c;
                            cs.ContactId = cc[0].id;
                            cs.Type = 'Request';
                            cs.Status = 'Closed';
                            cs.MOT__c = 'I Claim';
                            cs.Subject = 'ICF for Claim No '+ claim_number;
                            cs.Entity_Backup__c = 'AMFS';
                            cs.RecordTypeId = rt.Id;
                            cs.Case_Type__c = 'Request_Claim_Payment';
                            cs.Case_Type_Config__c = 'Request_Claim_Payment' ;
                            cs.Description = 'Transfer Status: ' + transfer_status + ' / Transfer Date: ' + transfer_date;
                            cs.PIC_Department_LU__c = usr.Id;
                            if(!System.test.isrunningtest()) insert cs;
                        }
                    }
                    
                    
                    codeReturn = '200';
                    status = 'Success';
                    messageReturn = 'Success add new data case';
                }
                
            }
			System.debug('messageReturn: ' +messageReturn);
            
        } catch(Exception ex) { 
            status = 'Internal Error';
            codeReturn = '500';
            messageReturn = ex.getMessage();
            System.debug('Get message:'+ex.getMessage());
            System.debug('Get Line:'+ex.getLineNumber());
        } 
        
        String setReturn = returnError(status,codeReturn, messageReturn);
        if(!System.Test.isRunningTest()) {
            // return response code
            RestResponse cb = RestContext.response;
            cb.addHeader('Content-Type', 'application/json');
            cb.statusCode = integer.valueOf(codeReturn);
            cb.responseBody = Blob.valueOf(setReturn);
        }
    }
    
    Public Static String returnError(String sts, String errcode, String err){
        String return_json='';
        JSONGenerator gentoken = JSON.createGenerator(true);
        gentoken.writeStartObject();
        gentoken.writeStringField('code', errcode);
        gentoken.writeStringField('status', sts);
        gentoken.writeStringField('description', err);
        gentoken.writeEndObject();
        return_json = gentoken.getAsString();
        return_json = return_json.normalizeSpace().trim();
        system.debug('*return_json*'+return_json);
        return return_json;
    }
}