force-app/main/default/objects/Case/fields/Entity_Backup__c.field-meta.xml
<CustomField>
    <fullName>Entity_Backup__c</fullName>
    <label>Entity Backup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/isMassUpload__c.field-meta.xml
<CustomField>
    <fullName>isMassUpload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMassUpload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/MOT__c.field-meta.xml
<CustomField>
    <fullName>MOT__c</fullName>
    <label>MOT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PIC_Department_LU__c.field-meta.xml
<CustomField>
    <fullName>PIC_Department_LU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>user to assign (especially for request)</inlineHelpText>
    <label>PIC Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>notContain</operation>
            <value>Admin</value>
        </filterItems>
        <filterItems>
            <field>User.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CasesDNMP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/ClaimApproveSch.cls
global with sharing class ClaimApproveSch implements Schedulable, Database.Batchable<sObject>{
    global void execute(SchedulableContext sc) { 
        // To start the batch job: 
        Database.executeBatch(new ClaimApproveSch(), 1);
    }
    
    global Iterable<sObject> start(Database.BatchableContext bc){
        String filter = System.Label.ICF_I_Claim_Approve;
        List<ICF_Claim_Approve__c> data = new List<ICF_Claim_Approve__c> ();
        
        String query = ' SELECT Id, Policy_Number__c, Claim_Number__c, Proceed_ICF__c from ICF_Claim_Approve__c where ' + filter;
        data = Database.query(query);
        return data;
    }
    
    global void execute(Database.BatchableContext BC, List<ICF_Claim_Approve__c> list_data){ 
        List<Case> Listcase = new List<Case>();
        List<ICF_Claim_Approve__c> data_update = new List<ICF_Claim_Approve__c>();
        if(list_data.size() > 0){
            for(ICF_Claim_Approve__c data:list_data){
                try{
                    List<Contact> cc = [select id, Policy_No__c from Contact where Policy_No__c =: data.Policy_Number__c limit 1];
                    if(cc.size() > 0){
                        Case cs = new Case();
                        RecordType rt = [select Id, Name from RecordType where sObjectType='Case' and name = 'RequestAMFSCase' limit 1];
                        User usr = [select id, name from user where name = 'Claim' limit 1];
                        cs.Policy_Number__c = cc[0].Policy_No__c;
                        cs.ContactId = cc[0].id;
                        cs.Type = 'Request';
                        cs.Status = 'Closed';
                        cs.MOT__c = 'I Claim';
                        cs.Subject = 'ICF for Claim No '+ data.Claim_Number__c;
                        cs.Entity_Backup__c = 'AMFS';
                        cs.RecordTypeId = rt.Id;
                        cs.Case_Type__c = 'Request_Claim_Payment';
                        cs.Case_Type_Config__c = 'Request_Claim_Payment' ;
                        cs.Description = 'Claim Status: Cashless';
                        cs.PIC_Department_LU__c = usr.Id;
                        cs.isMassUpload__c = true;
                        insert cs;
                        String caseId = cs.Id;
                        DescribeSObjectResult describeResult = Case.getSObjectType().getDescribe();
                        List<String> fieldList = new List<String>(describeResult.fields.getMap().keySet());
                        String fieldStr = String.join(fieldList, ',');
                        String query = ' SELECT ' + fieldStr + ' FROM Case WHERE Id = :caseId ';
                        
                        Case log = Database.query(query); 
                        CreateEmailSmsLogQueue caseQueue = new CreateEmailSmsLogQueue(log);
                        System.enqueueJob(caseQueue);
                    }
                    data.Proceed_ICF__c = true;
                    data_update.add(data);                    
                    
                    insert Listcase;
                }
                catch(Exception e){
                    System.debug('Exception occurred: ' + e.getMessage());
                }
                data.Proceed_ICF__c = true;
                update data;
            }
        }

                
    }
    
    global void finish(Database.BatchableContext bc){
        
    }
    
}