force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CustomCaseLookupController_Test.cls
@isTest(seeAllData = true)
public class CustomCaseLookupController_Test {
    public static testmethod void createCustomCaseLookupControllerTest() {
        
        
        Test.startTest();
        Account ac1 = new Account();
        ac1.Name = 'AccountTest10';
        ac1.Entity__c = 'MAGI';
        insert ac1;
        
        Contact contact1 = new Contact();
        contact1.FirstName = 'Bill';
        contact1.LastName = 'Gates';
        contact1.Email = 'billgates@email.com';
        contact1.MobilePhone = '0891667363';
        contact1.Policy_No__c = '100000015';
        contact1.Entity__c = 'MAGI';
        contact1.AccountId = ac1.Id;
        insert contact1;
        
        String frm = 'Form';
        String txt = 'Text';
        
        String oppCustomLookupVF = '/apex/CustomCaseLookupLayout';
        PageReference pageRef = new PageReference(oppCustomLookupVF);
        pageRef.getParameters().put('lksrch', '');
        pageRef.getParameters().put('contactId', contact1.Id);
        pageRef.getParameters().put('frm', frm);
        pageRef.getParameters().put('txt', txt);
        Test.setCurrentPage(pageRef);
        
        CustomCaseLookupController copl = new CustomCaseLookupController();
        
        //init search
        PageReference initSearchResult = copl.search();
        System.assertEquals(null, initSearchResult);
        
        //perform search with param
        List<Case> searchResult = copl.performSearch('1');
        System.assertNotEquals(null, searchResult);
        
        //test formtag
        String formTag = copl.getFormTag();
        System.assertNotEquals(null, formTag);
        
        //test textbox
        String textBox = copl.getTextBox();
        System.assertNotEquals(null, textBox);
        
        Test.stopTest();
    }
}