force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Conservation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Survey Feedback</fullName>
            </value>
            <value>
                <fullName>Complaint Case</fullName>
            </value>
            <value>
                <fullName>Customer Segmentation</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Teleservices</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Call_Line_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Call_Line_RecordTypeID__c</fullName>
    <formula>IF(ISPICKVAL(Entity__c, &apos;AGI&apos;),
IF(ISPICKVAL(Case_Type__c , &apos;Welcome Call&apos;),&apos;0126F0000026h5gQAA&apos;,
IF(ISPICKVAL(Case_Type__c, &apos;Complaint Follow Up&apos;),&apos;0126F0000026h5YQAQ&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;SMS Pull Confirmation&apos;),&apos;0126F0000026h5bQAA&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Claim&apos;),&apos;0126F0000026h5XQAQ&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Update Data&apos;),&apos;0126F0000026h5fQAA&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Renewal&apos;),&apos;0126F0000026h5aQAA&apos;,
IF(ISPICKVAL(Activity__c , &apos;Survey - I Ask&apos;),&apos;0126F0000026h5cQAA&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Survey - I Buy&apos;),&apos;0126F0000026h5dQAA&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Survey - I Claim&apos;),&apos;0126F0000026h5eQAA&apos;,
&apos;0126F0000026h5ZQAQ&apos;))))))))),
IF(ISPICKVAL(Entity__c, &apos;ALI&apos;),
IF(ISPICKVAL(Case_Type__c , &apos;Welcome Call&apos;),&apos;0126F000001MIGAQA4&apos;,
IF(ISPICKVAL(Case_Type__c, &apos;Reinstate&apos;),&apos;0126F000001MIGBQA4&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Premium FU&apos;),&apos;0126F000001MIGCQA4&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Claim&apos;),&apos;0126F000001MIGDQA4&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Update Data&apos;),&apos;0126F000001MIGEQA4&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;NCB&apos;),&apos;0126F000001MIGFQA4&apos;,
IF(ISPICKVAL(Activity__c , &apos;Survey Feedback&apos;),&apos;0126F000001MIGGQA4&apos;,
IF(ISPICKVAL(Case_Type__c , &apos;Collection Task&apos;),&apos;0126F000001MIGHQA4&apos;,
&apos;0126F000001MIG8QAO&apos;)))))))),
IF(ISPICKVAL(Entity__c, &apos;AMFS&apos;),
IF(ISPICKVAL(Case_Type__c, &apos;Renewal Reminder&apos;) || ISPICKVAL(Case_Type__c, &apos;TRO Project&apos;) || CONTAINS(TEXT(Case_Type__c),&apos;Others&apos;),&apos;0120K000000q1QNQAY&apos;,
IF(ISPICKVAL(Case_Type__c, &apos;Lapse Konven&apos;),&apos;0120K000000q1QOQAY&apos;,
IF(ISPICKVAL(Case_Type__c, &apos;MKP&apos;),&apos;0120K000000q1QPQAY&apos;,
IF(ISPICKVAL(Case_Type__c, &apos;Cuti Premi&apos;),&apos;0120K000000q1QQQAY&apos;,
IF(ISPICKVAL(Case_Type__c, &apos;RTU&apos;),&apos;0120K000000q1QRQAY&apos;,
IF(ISPICKVAL(Case_Type__c, &apos;Redemption Konven&apos;) || ISPICKVAL(Case_Type__c, &apos;Withdrawal&apos;),&apos;0120K000000q1QSQAY&apos;,
IF(ISPICKVAL(Case_Type__c, &apos;Lapse TM&apos;),&apos;0120K000000q1QTQAY&apos;,&apos;0120K000000q1QUQAY&apos;))))))),
&apos;0126F000001MIG8QAO&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Call Line RecordTypeID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Collection Task</fullName>
            </value>
            <value>
                <fullName>Reinstate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Case_Type_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Type_Config__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Collection Task</fullName>
            </value>
            <value>
                <fullName>Reinstate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Expired_Date__c</fullName>
    <description>Expired Date</description>
    <label>Expired Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/is_Expired_F__c.field-meta.xml
<CustomField>
    <fullName>is_Expired_F__c</fullName>
    <formula>if(Expired_Date__c &lt; today(), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>is Expired F</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/IsExpired__c.field-meta.xml
<CustomField>
    <fullName>IsExpired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Survey_ID__c.field-meta.xml
<CustomField>
    <fullName>Survey_ID__c</fullName>
    <label>Survey ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF(IsClosed, ClosedDate - CreatedDate, NOW() - CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (Days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <defaultValue>&quot;CS&quot;</defaultValue>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Named_User__c.field-meta.xml
<CustomField>
    <fullName>Named_User__c</fullName>
    <label>Named User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Received_date__c.field-meta.xml
<CustomField>
    <fullName>Received_date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Received date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/Case_CMU_Change_Owner_Ctrl.cls
public class Case_CMU_Change_Owner_Ctrl {
    public Integer AMFScampaignPeriod = Integer.valueOf(System.Label.CampaignPeriodForDistributionAMFS);
    public Integer uploadedNum {get; set;}
    public Integer validNum {get; set;}
    public Integer invalidNum {get; set;}
    public Integer totalPolicies {get;set;}
    public Integer totalData {get;set;}
    public Integer totalGAP {get;set;}
    public Integer inputValue {get;set;}
    public Integer totalAgents {get;set;}
    public Boolean isMaxRecord {get;set;}
    public Boolean isMethodChoosen{get;set;}
    public String entity {get; set;}
    public String choosen_campaign {get;set;}
    public String choosen_user{get;set;}
    public String prev_user{get;set;}
    public String choosen_method {get; set;}
    public String CollectionTaskArr {get; set;}
    public String url = 'https://'+system.URL.getSalesforceBaseUrl().getHost()+'/apex/TakeSurvey?id=SURVEYID&cId=CONTACTID&caId=none';
    public List<Call_List__c> campaign_list {get;set;}
    public List<Case> CaseList {get;set;}
    public List<SelectOption> optionCampaign_list {get;set;}
    public List<String> invalidPolicyList {get;set;}
    public List<String> invalidPolicyTempList {get;set;}
    public List<User_Detail__c> agentList {get;set;}
    public List<Id> agentIDList {get;set;}
    public List<SelectOption> agentOptList {get; set;}
    public List<SelectOption> distributeOptionList {get; set;}
    public List<String> list_policyNo {get;set;}
    public Map<Id, Call_List__c> map_campaignObj {get;set;}
    public Map<string,Contact> mapContactList {get;set;}
    public Map<string,string> agentMap {get; set;}
    public Map<String, Case> map_callLine {get;set;}
    public Map<String, ID> map_userid {get;set;}
    
    Public Integer checkLoop = 0;
    Public String AMFS = 'AMFS';
    Public Decimal Total_APE {get;set;}
    Public String String_APE {get;set;}
    Public Integer campaignTarget {get;set;}
    public List<User_Detail__c> agentListView {get;set;}
    public List<Agent_Distribution_History__c> finalListAdh {get;set;}
    public map<Id,Agent_Distribution_History__c> mapAgentHistory {get;set;}
    public List<SelectOption> optionUser_list {get;set;}
    public List<SelectOption> prevUser_list {get;set;}
    
    Public List<tempCase> tempCallLineList {get;set;}
    
    Public boolean selectAll {get;set;}

     public List<SelectOption> getNamedUserAlllist(){
         List<SelectOption> options = new List<SelectOption>();
         
         options.add(new SelectOption('All','--All--'));
         options.add(new SelectOption('Queue','Queue'));
         for (Named_User__c nu : [SELECT id, Name FROM Named_User__c WHERE Entity__c = 'AMFS' and Division__c = 'CMU']){
             options.add(new SelectOption(nu.Name,nu.Name));
         }

         return options;   
     }

     public List<SelectOption> getNamedUserlist(){
         List<SelectOption> options = new List<SelectOption>();
         
         map_userid = new map<string,ID>();
         
         options.add(new SelectOption('All','--All--'));
         for (Named_User__c nu : [SELECT id, Name, User__c FROM Named_User__c WHERE Entity__c = 'AMFS' and Division__c = 'CMU' and (Status__c = 'Active' OR Status__c = 'Non Active' OR Status__c = '')]){
             options.add(new SelectOption(nu.Name,nu.Name));
             map_userid.put(nu.Name, nu.User__c);
         }

         return options;   
     }
    
    public Document document {
        get {
            if (document == null){
                document = new Document();
            }
            return document;
        }
        set;
    }
    
    public Case_CMU_Change_Owner_Ctrl(){
        uploadedNum = 0;
        validNum = 0;
        invalidNum = 0;
        totalPolicies = 0;
        selectAll = false;
        map_campaignObj = new Map<Id, Call_List__c>();
        User userObj = [select id, Entity__c from user where id = :UserInfo.getUserId()];
        Entity = userObj.Entity__c;
        String loggedInUser = userObj.id;
        campaign_list = Database.query('SELECT id, Name, Campaign_Name__c, Entity__c, Activity__c, Case_Type__c, Case_Type_Config__c, Survey_ID__c, Call_Line_RecordTypeID__c FROM Call_List__c WHERE Entity__c = :AMFS AND createdby.id = :loggedInUser AND IsExpired__c = false AND Is_Expired_F__c = false order by CreatedDate desc'); //AND Expired_Date__c <= system.today();
        
        optionCampaign_list = new List<SelectOption>();
        optionUser_list = new List<SelectOption>();
        prevUser_list = new List<SelectOption>();
        tempCallLineList = new List<tempCase>();
        
        if (campaign_list.size() > 0){
            for(Call_List__c cl : campaign_list){
                optionCampaign_list.add(new SelectOption(cl.id, cl.Campaign_Name__c));
                map_campaignObj.put(cl.Id, cl);
            }    
        }
        else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'There`s no campaign / call line available'));   
        }    
        // default
        isMaxRecord = FALSE;
        inputValue = 0;
        
    }
   
    public PageReference populateFreshData(){ // untuk collect data agent dan collect data call line yg akan di distribusi
        isMethodChoosen = false;
        
        if (tempCallLineList.size() > 0) tempCallLineList.clear();
        
        checkLoop += 1;
        {
            String query = 'select id, Named_User__c, CaseNumber, Contact.Name, Contact.Policy_No__c, Received_date__c, Age__c, Category__c, Complaint_type__c, Other_Information__c, CHS_Status__c, Complaint__c from Case where Entity_Backup__c = \'AMFS\' AND Type = \'Complaint\' AND Status != \'Closed\'';
            if (prev_user != null) 
                if (prev_user == 'Queue') 
                    query += 'AND Owner.Name = \'AMFS - CMU Queue\' ';
                else if (prev_user != 'All') 
                    query += 'AND Named_User__c = :prev_user';
            
            query += ' order by Received_date__c LIMIT 800';
            
            if (Test.isRunningTest()) query = 'select id, Named_User__c, CaseNumber, Contact.Name, Contact.Policy_No__c, Received_date__c, Age__c, Category__c, Complaint_type__c, Other_Information__c, CHS_Status__c, Complaint__c from Case limit 1';

            CaseList = Database.query(query);
            
            for (Case cl : CaseList){
                tempCase tcl = new tempCase();
                tcl.cl_id = cl.Id;

        tcl.cl_Named_User = cl.Named_User__c;
        tcl.cl_CaseNumber = cl.CaseNumber;
        tcl.cl_Contact_Name = cl.Contact.Name;
        tcl.cl_Contact_Policy_No = cl.Contact.Policy_No__c;
        tcl.cl_Received_date = string.valueof(cl.Received_Date__c);
        tcl.cl_Age = string.valueof(cl.Age__c);
        tcl.cl_Category = cl.Category__c;
        tcl.cl_Complaint_type = cl.Complaint_Type__c;
        tcl.cl_Other_Information = cl.Other_Information__c;
        tcl.cl_CHS_Status = cl.CHS_Status__c;
        tcl.cl_Complaint = cl.Complaint__c;

                tempCallLineList.add(tcl);
            }
                        
            String query2 = 'select id from Case where Call_List__c = :choosen_campaign and isOwnerQueue__c = FALSE and Agent__c= null and Parent_Call_Line__c != NULL';
            if (prev_user != null) query2 += 'AND Agent__c = :prev_user';
                        
        }
        return null;
    }
    
    public PageReference save() {
        List<Case> clUpdate = new list <Case>();
        for (tempCase tcl : tempCallLineList){
            if (tcl.cl_isSelected == true){
                Case ncl = new Case();
                ncl.id = tcl.cl_id;
                ncl.Named_User__c = choosen_user;
                if (map_userid.get(choosen_user) != NULL) {
                    ncl.OwnerId = map_userid.get(choosen_user);
                    ncl.PIC__c = map_userid.get(choosen_user);
                }
                clUpdate.add(ncl);
            }
        } 
        Set<Case> myset = new Set<Case>();
        List<Case> result = new List<Case>();
        myset.addAll(clUpdate);
        result.addAll(myset);
        
        if (result.size() > 0) {
            update result;  
            PageReference tempPage = ApexPages.currentPage();            
            tempPage.setRedirect(true);
            return tempPage;
        }
        else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Please select at least 1 call line'));  
            return null;
        } 
    }
    
    public class tempCase{
        Public id cl_id {get;set;}
        Public String cl_Named_User {get;set;}
        Public String cl_CaseNumber {get;set;}
        Public String cl_Contact_Name {get;set;}
        Public String cl_Contact_Policy_No {get;set;}
        Public String cl_Received_date {get;set;}
        Public String cl_Age {get;set;}
        Public String cl_Category {get;set;}
        Public String cl_Complaint_type {get;set;}
        Public String cl_Other_Information {get;set;}
        Public String cl_CHS_Status {get;set;}
        Public String cl_Complaint {get;set;}
        Public Boolean cl_isSelected {get;set;}

    }
}