force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.ContactId</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/WelcomeCall_Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Schedule_Date__c</fullName>
    <label>Schedule Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NotifyAssignTaskAMFS.cls
public class NotifyAssignTaskAMFS { 
    Public static List<String> SendEmail (String taskId, string typeCase) {  
        List<String> returnEmail = new List<String>();  
 
        List<Messaging.SingleEmailMessage> listEmail = new List<Messaging.SingleEmailMessage>(); 
        EmailTemplate et = new EmailTemplate();
		// EmailTemplate et = [SELECT Id, HtmlValue, Subject FROM EmailTemplate WHERE name = 'ET - AMFS - Reminder Task Welcome Call &  CR'];
        // template email
       if(taskId != NULL && taskId.left(3) == Schema.SObjectType.Call_Line__c.getKeyPrefix()){  
            et = [SELECT Id, name, HtmlValue, Subject FROM EmailTemplate  where name = 'ET - AMFS - Reminder Task Welcome Call &  CR']; 
        } 
        
        if(taskId != NULL && taskId.left(3) == Schema.SObjectType.Case.getKeyPrefix()){ 
            et = [SELECT Id, name, HtmlValue, Subject FROM EmailTemplate WHERE name = 'ET - AMFS - Reminder Task Welcome Call &  CR 2'];
        }
        
        Boolean isAlreadySet = false;
        //replace htmlbody email
        String htmlbody = et.HtmlValue;
        String subject = et.Subject;
                
        string convertDate = '';
        List<string> convertDateArr = new List<string>();
        
        System.debug('convertDateArr:'+convertDateArr);
        string getDate = '';
        string getTime = '';
        
        List<string> getDateArr = new List<string>();
        List<string> getTimeArr = new List<string>();
        
        System.debug('getDateArr:'+getDateArr);
        System.debug('getTimeArr:'+getTimeArr);
        string getDay = '';
        string getMonth = '';
        string getYear = '';
         
        string getHour  = '';
        string getMinute = '';
        
        String convertDateStr = '';
        String convertTimeStr = '';
        
        String receiptMail = '';
        
        DateTime setDateTime = System.now(); 
        
        system.debug('et:'+et); 
          
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'noreply.general@axa-mandiri.co.id'];
        system.debug('owea:'+owea);
        
        List<Case> getDetails = new List<Case>();
        List<Call_Line__c> getDetail = new List<Call_Line__c>();
        if(taskId != NULL && taskId.left(3) == Schema.SObjectType.Call_Line__c.getKeyPrefix()){  
            
            system.debug('taskId:'+taskId);
            if (Test.isRunningTest()) {
                getDetail = [SELECT Id, Name, OwnerId, Owner.Name, owner.Email, case__c, case__r.Createddate, Contact__c, Contact__r.Policy_No__c, createdDate, WelcomeCall_Schedule_Date__c   FROM Call_Line__c Limit 1];
            } else {
                getDetail = [SELECT Id, Name, OwnerId, Owner.Name, owner.Email, case__c, case__r.Createddate, Contact__c, Contact__r.Policy_No__c, createdDate, WelcomeCall_Schedule_Date__c FROM Call_Line__c where id =: taskId limit 1];
            }   
            
            Call_Line__c detailCL = getDetail[0];
            
            receiptMail = detailCL.owner.Email;
            
            if (typeCase == 'Request') { 
                setDateTime = detailCL.case__r.Createddate;
            } else { 
                setDateTime = detailCL.WelcomeCall_Schedule_Date__c;
            }
              
            if (setDateTime != null) { 
                convertDate = String.valueOf(setDateTime);
                convertDateArr = convertDate.split(' ');
                
                System.debug('convertDateArr:'+convertDateArr);
                getDate = convertDateArr[0];
                getTime = convertDateArr[1];
                
                getDateArr = getDate.split('-'); 
                getTimeArr = getTime.split(':');
                
                System.debug('getDateArr:'+getDateArr);
                System.debug('getTimeArr:'+getTimeArr);
                getDay = getDateArr[2];
                getMonth = getDateArr[1];
                getYear = getDateArr[0];
                
                getHour  = getTimeArr[0];
                getMinute = getTimeArr[1];
                
                convertDateStr = getDay+'/'+getMonth+'/'+getYear;
                convertTimeStr = getHour+':'+getMinute; 
                
                
                System.debug('Detail:'+detailCL); 
                System.debug('Owner:'+detailCL.Owner.Name); 
                
                htmlbody = htmlbody.replace('[owner_name]', String.isnotblank(detailCL.Owner.Name) ? detailCL.Owner.Name : '');
                htmlbody = htmlbody.replace('[contact_policy_no]',  String.isnotblank(detailCL.Contact__r.Policy_No__c) ? detailCL.Contact__r.Policy_No__c : '' );
                htmlbody = htmlbody.replace('[callline_datecreated]',  convertDateStr);
                htmlbody = htmlbody.replace('[callline_timecreated]',  convertTimeStr);
                htmlbody = htmlbody.replace('[callline_url]',  System.label.SFDC_URL_AXA+taskId );
                htmlbody = htmlbody.replace('[callline_name]',  String.isnotblank(detailCL.Name) ? detailCL.Name : '' );
                isAlreadySet = true;
                
            }
        }  
        if (isAlreadySet == true) {
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject(subject);
            mail.setHtmlBody(htmlbody);
            mail.setTreatTargetObjectAsRecipient(false);
            mail.setTemplateId(et.Id); 
            mail.setOrgWideEmailAddressId(owea.get(0).Id);                                         
            list<string> toMail = new list<string>();  
            toMail.add(receiptMail);
            mail.setToAddresses(toMail);
            
            /* list<string> ccEmail = new list<string>();
            
            ccEmail.add('tesssmailproject@gmail.com');
            ccEmail.add('Ranggi.rakashiwi@axa-mandiri.co.id'); 
            mail.setCcAddresses(ccEmail);  */
            mail.setSaveAsActivity(false);
            listEmail.add(mail);
            system.debug('listEmail = '+listEmail); 
            
            if(!Test.isRunningTest()) Messaging.sendEmail(listEmail);  
        } 
        
        return returnEmail;
    }  
}