force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Date_When_Customer_Call__c.field-meta.xml
<CustomField>
    <fullName>Date_When_Customer_Call__c</fullName>
    <description>The date when customer call to AXA and available to be called back</description>
    <inlineHelpText>The date when customer call to AXA and available to be called back</inlineHelpText>
    <label>Date When Customer Call</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Expired_Date__c</fullName>
    <formula>IF(ISPICKVAL(Case_Type__c, &apos;TelUW&apos;), DATEVALUE(WelcomeCall_Schedule_Date__c) + 30, if ( and(RecordType.Name == &apos;TeleService&apos;, NOT(ISBLANK(Due_Date__c)) ),  Due_Date__c , Call_List__r.Expired_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expired Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Preferred_Phone__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Phone__c</fullName>
    <label>Preferred Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Used_Phone__c.field-meta.xml
<CustomField>
    <fullName>Used_Phone__c</fullName>
    <label>Used Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Expired_Date__c</fullName>
    <description>Expired Date</description>
    <label>Expired Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/RelatedPolicyControllerTest.cls
@isTest
public class RelatedPolicyControllerTest {
/*
* This test class was edited by Hamfry A. L on Jun 9, 2015 to be re-deployed to production
*
*/
    public static testMethod void testRelatedPolicyController() {
    	Profile profil = [SELECT Id FROM Profile WHERE Name='CMU-AFI'];
    	User usr  = [SELECT id, Entity__c FROM user WHERE ProfileId = :profil.id AND IsActive = true limit 1];
    	
    	System.runAs(usr) {
    		Call_List__c clist = new Call_List__c();
	    	clist.Expired_Date__c = system.today();
	    	insert clist;  	
	    	
	    	Contact c = new Contact();
	    	c.LastName = 'Frys';
	    	c.Policy_No__c = '123-5555';
	    	c.Entity__c = 'AFI';
	    	insert c;
	    	    	
	    	Call_Line__c cl = new Call_Line__c();
	    	cl.Call_List__c = clist.id;
	    	cl.Used_Phone__c = '0811223344';
	    	cl.Preferred_Phone__c = '0822334455';
	    	cl.Date_When_Customer_Call__c = system.today();
	    	cl.Entity__c = 'AFI';
	    	cl.Contact__c = c.Id;
	    	insert cl;
	    	
	    	Related_Policy__c relPol = new Related_Policy__c();
	    	relPol.Call_Back__c = cl.id;
	    	relPol.Contact_ID__c = c.id;
	    	relPol.Customer_Name__c = 'frys';
	    	relPol.Policy_No__c = '123-5555';
	    	insert relPol;
	    	
	    	ApexPages.StandardController sc = new ApexPages.StandardController(cl);
	    	RelatedPolicyController testRelatedPolicyController = new RelatedPolicyController(sc);
	    	List<RelatedPolicyController.RelatedPolicyView> list_rpv = new List<RelatedPolicyController.RelatedPolicyView>();
	        RelatedPolicyController.RelatedPolicyView rpv = new RelatedPolicyController.RelatedPolicyView();
	        rpv.isSelected = true;
	        rpv.customerName = 'testing';
	        rpv.policyNo = '123-666';
	        list_rpv.add(rpv);
	        List<Related_Policy__c> lst_relatedPlc = new List<Related_Policy__c>();
	        testRelatedPolicyController.selectPolicy();
	        testRelatedPolicyController.cancel();
	        testRelatedPolicyController.runclick();
    	}
    }
}