force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No outbound agent has been configured yet</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Outbound Agent</value>
        </filterItems>
        <filterItems>
            <field>$Source.Entity__c</field>
            <operation>equals</operation>
            <valueField>User.Entity__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.Agent__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_DistributeAuto_CallLineALI.cls
global class Batch_DistributeAuto_CallLineALI implements Database.Batchable<sObject>, Database.Stateful{

	public List <Agent_Distribution_History__c> finalListAdhFinal = new List<Agent_Distribution_History__c>();
    public List <Call_Line__c> callLineListFinal = new List<Call_Line__c>();
    public Map<Id,Decimal> mapAA = new Map<Id,Decimal>();
    public Map<Id,Agent_Distribution_History__c> mapAgentHistory = new Map<Id,Agent_Distribution_History__c>();
    public String choosen_campaign;

    global Batch_DistributeAuto_CallLineALI(List<Call_Line__c> callLineList){
        this.callLineListFinal = callLineList;
    }
    
    global List<Call_Line__c> start(Database.BatchableContext BC) {
        return callLineListFinal;
    }
    
    global void execute(Database.BatchableContext BC, List<Call_Line__c> scope){
        
        List<Agent_Distribution_History__c> upsertAdhFinal = new list<Agent_Distribution_History__c>();
        
        string surveyURL = '';
        List<Call_Line__c> tosaveCallLineList = new List<Call_Line__c>();  //added by WK, 20150417
        Call_Line__c tosaveCallLine = null; //added by WK, 20150417
        
        for(Call_Line__c dis : scope){
            dis.ownerId = dis.Agent__c;
            if(dis.Agent__c!=null){
                tosaveCallLine = new Call_Line__c();
                tosaveCallLine.id = dis.id;
                tosaveCallLine.Agent__c = dis.Agent__c;
                tosaveCallLine.ownerId = dis.Agent__c;
                tosaveCallLineList.add(tosaveCallLine); 
            }
        }
        
        Set<call_line__c> myset = new Set<call_line__c>();
        List<call_line__c> result = new List<call_line__c>();
        myset.addAll(tosaveCallLineList);
        result.addAll(myset);
        
        if(test.isRunningTest()==false) update result;
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}