force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contacted_Number__c.field-meta.xml
<CustomField>
    <fullName>Contacted_Number__c</fullName>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Name_1__c.field-meta.xml
<CustomField>
    <fullName>Name_1__c</fullName>
    <description>ALI</description>
    <inlineHelpText>ALI
Exp : ANN MARIE</inlineHelpText>
    <label>Name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Parent_Call_Line__c.field-meta.xml
<CustomField>
    <fullName>Parent_Call_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ALI - Group by</inlineHelpText>
    <label>Parent Call Line</label>
    <referenceTo>Call_Line__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Parent_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Parent_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines (Parent Campaign)</relationshipLabel>
    <relationshipName>Call_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Parent_Name_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Parent_Name_Mobile__c</fullName>
    <formula>NULLVALUE(Name_1__c, &quot;&quot;)&amp;&quot;&quot;&amp;NULLVALUE(Contacted_Number__c, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Name+Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CallLineGroupByAGI.cls
public class CallLineGroupByAGI {
    @future
    public static void CallLine(id choosen_campaign, String entity){
    //public static String CallLine(id choosen_campaign, String entity)

        List<Call_Line__c> ListCLUpdate = new List<Call_Line__c>();
        string temp = '';
        id Parentid; 
        for (Call_Line__c cl : [SELECT id, Policy_No__c, Entity__c, Name, Parent_Name_Mobile__c, Contact__c, Contact__r.Name,
                                Name_1__c, Contacted_Number__c, Call_List__c, Parent_Call_Line__c, Parent_Campaign__c
                               From Call_Line__c WHERE Call_List__c = :choosen_campaign AND Entity__c = :entity 
                                // fix for Parent belum di mapping, 26 feb 2018
                               and Parent_Call_Line__c = NULL and Parent_Campaign__c = NULL
                                ORDER BY Name_1__c, Contacted_Number__c]) {
                                //ORDER BY Contact__r.Name, Name_1__c, Contacted_Number__c])
            if (isNUll(cl.Name_1__c) == '') cl.Name_1__c = cl.Contact__r.Name;
            if (temp != (isNUll(cl.Name_1__c)+''+isNUll(cl.Contacted_Number__c)) ) {
                cl.Parent_Campaign__c = cl.Call_List__c;
                cl.Parent_Call_Line__c = NULL;
                
                temp = isNUll(cl.Name_1__c)+''+isNUll(cl.Contacted_Number__c);
                Parentid = cl.id;
            }
            else {
                cl.Parent_Campaign__c = null;
                cl.Parent_Call_Line__c = Parentid; 
            }
            ListCLUpdate.add(cl);
        }
        system.debug('data update : '+ListCLUpdate.size());
        if (ListCLUpdate.size() > 0) update ListCLUpdate;
        //return null;
    }
    
    public static string isNUll(String param){
        string result ='';
        if (param == NULL) result = '';
        else result = param;
        Return result;
    }
}