force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount NI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/APE_Convert__c.field-meta.xml
<CustomField>
    <fullName>APE_Convert__c</fullName>
    <formula>IF((ISPICKVAL(Call_List__r.Case_Type_Config__c,&apos;Withdrawal&apos;) || ISPICKVAL(Call_List__r.Case_Type_Config__c,&apos;Redemption Konven&apos;))&amp;&amp; Currency__c=&apos;USD&apos;, Amount__c * 14000,
IF((ISPICKVAL(Call_List__r.Case_Type_Config__c,&apos;Withdrawal&apos;) || ISPICKVAL(Call_List__r.Case_Type_Config__c,&apos;Redemption Konven&apos;))&amp;&amp; Currency__c!=&apos;USD&apos;,Amount__c,
IF((ISPICKVAL(Call_List__r.Case_Type_Config__c,&apos;Redemption TM&apos;) || ISPICKVAL(Call_List__r.Case_Type_Config__c,&apos;Lapse TM&apos;))&amp;&amp; Currency__c==&apos;USD&apos;,(APE__c)/12*14000,
IF((ISPICKVAL(Call_List__r.Case_Type_Config__c,&apos;Redemption TM&apos;) || ISPICKVAL(Call_List__r.Case_Type_Config__c,&apos;Lapse TM&apos;))&amp;&amp; Currency__c!=&apos;USD&apos;,APE__c/12,
IF(Currency__c==&apos;USD&apos;,APE__c*14000,APE__c)))))</formula>
    <label>APE / Amount Convert</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/APE_Total_Child__c.field-meta.xml
<CustomField>
    <fullName>APE_Total_Child__c</fullName>
    <label>APE / Amount Total Final</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Call_List__r.Campaign_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Child_Count__c.field-meta.xml
<CustomField>
    <fullName>Child_Count__c</fullName>
    <label>Child Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Parent_Call_Line__c.field-meta.xml
<CustomField>
    <fullName>Parent_Call_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ALI - Group by</inlineHelpText>
    <label>Parent Call Line</label>
    <referenceTo>Call_Line__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AMFS_CallLine_ParentCounter.cls
global class AMFS_CallLine_ParentCounter implements Database.Batchable<Call_Line__c> {
  Public string choosenCampaign;
  Public string userId;
  public List <Call_Line__c> callLineListFinal = new List<Call_Line__c>();
    
  global AMFS_CallLine_ParentCounter(String choosenCampaign, String userId,List<Call_Line__c> callLineListFinal) {
        this.choosenCampaign = choosenCampaign;
      	this.userId = userId;
      	this.callLineListFinal = callLineListFinal;
  }
  
  global List<Call_Line__c> start(Database.BatchableContext BS) {
        return callLineListFinal;
  }
    
  global void execute(Database.BatchableContext BS, List<Call_Line__c> scope) {
      	system.debug('***Choosen Campaign: '+choosenCampaign);
      	system.debug('***User Id: '+userId);
      
        String campaignName = [Select id, Campaign_Name__c from Call_List__c where id = :choosenCampaign limit 1].Campaign_Name__c;
        set<Id> setParent = new set<Id>();
        map<Id,Decimal> mapAPE = new map<Id,Decimal>();
        
      	List<Call_Line__c> updateCallLine = new list <Call_Line__c>(); 
        list<Call_Line__c> listCallLine = [SELECT id, Amount__c, Parent_Call_Line__c,APE_Convert__c FROM Call_Line__C WHERE call_list__c = :choosenCampaign AND Parent_Call_Line__c != null AND Createddate = TODAY AND CreatedById = :userId ORDER BY CreatedDate DESC LIMIT 50000];
        system.debug('***List Call Line Size: '+listCallLine.size());
      	for (Call_Line__c x : listCallLine){
            if (x.Parent_Call_Line__c != null) {                
                setParent.add(x.Parent_Call_Line__c);
                    if (mapAPE.containsKey(x.Parent_Call_Line__c) && x.APE_Convert__c != null){
                            Decimal tempAPE = mapAPE.get(x.Parent_Call_Line__c) + x.APE_Convert__c;
                            mapAPE.put(x.Parent_Call_Line__c,tempAPE); 
                    }
                    else {
                            mapAPE.put(x.Parent_Call_Line__c, x.APE_Convert__c);
                    }
            }
        } 

        map<Id,Integer> mapParent = new Map<Id,Integer>();
        list<Call_Line__c> listCallLineParent = [SELECT Id,Amount__c,APE_Convert__c,APE_Total_Child__c,Child_Count__c, Parent_Call_Line__c FROM Call_Line__c WHERE Id in :setParent];
        system.debug('***List Parent Size: '+listCallLineParent.size());
      	for(Call_Line__c x : listCallLine){
            if (mapParent.containsKey(x.Parent_Call_Line__c)){
                Integer countChild = mapParent.get(x.Parent_Call_Line__c) + 1;
                mapParent.put(x.Parent_Call_Line__c, countChild);
            }
            else {
            mapParent.put(x.Parent_Call_Line__c,1);
            }
        }
   
        for (Call_Line__c x : listCallLineParent){
            Call_Line__c newCl = new Call_Line__c();
            newCl.Id = x.Id;
            newCl.Child_Count__c = 0;
                if (mapParent.get(x.Id) != null){
                    newCl.Child_Count__c = mapParent.get(x.Id)+1; //di tambah diri sendiri
                    if (x.APE_Convert__c != null) {
                     	newCl.APE_Total_Child__c = mapAPE.get(x.Id)+ x.APE_Convert__c; //di tambah APE diri sendiri     
                    }  
                }updateCallLine.add(newCl);
        } update updateCallLine;
  	}
    
    global void finish(Database.BatchableContext BC){
        
    }
}