force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Conservation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Survey Feedback</fullName>
            </value>
            <value>
                <fullName>Complaint Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Call_List__r.Campaign_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <formula>Call_List__r.Campaign_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Case_Type_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Type_Config__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity_Config__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Survey - I Buy</fullName>
            </value>
            <value>
                <fullName>Survey - I Ask</fullName>
            </value>
            <value>
                <fullName>TelUW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>Insured_Name__c</fullName>
    <formula>Contact__r.Insured_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insured Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/recordTypes/TelUW.recordType-meta.xml
<RecordType>
    <fullName>TelUW</fullName>
    <active>true</active>
    <label>TelUW</label>
</RecordType>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Conservation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Survey Feedback</fullName>
            </value>
            <value>
                <fullName>Complaint Case</fullName>
            </value>
            <value>
                <fullName>Customer Segmentation</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Teleservices</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <formula>TEXT(Activity__c) &amp;&apos;-&apos;&amp; TEXT(Case_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/APE_TelUW__c.field-meta.xml
<CustomField>
    <fullName>APE_TelUW__c</fullName>
    <label>APE TelUW</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>Type Campaign for Tel UW</description>
    <label>Campaign Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Currency_TelUW__c.field-meta.xml
<CustomField>
    <fullName>Currency_TelUW__c</fullName>
    <label>Currency TelUW</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Insured_Email__c.field-meta.xml
<CustomField>
    <fullName>Insured_Email__c</fullName>
    <label>Insured Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Insured_Name__c.field-meta.xml
<CustomField>
    <fullName>Insured_Name__c</fullName>
    <label>Insured Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Issued_Date_TelUW__c.field-meta.xml
<CustomField>
    <fullName>Issued_Date_TelUW__c</fullName>
    <description>Tell UW Isued Date</description>
    <label>Issued Date TelUW</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No_Numeric__c.field-meta.xml
<CustomField>
    <fullName>Policy_No_Numeric__c</fullName>
    <externalId>true</externalId>
    <label>Policy No Numeric</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product_Code_Plant_TelUW__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_Plant_TelUW__c</fullName>
    <label>Product Code Plant TelUW</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Gender__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Gender__c</fullName>
    <label>Gender</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CallLineTelUWHelperTest.cls
@isTest
private class CallLineTelUWHelperTest {

    static testMethod void testRequestTelUW() {
        // Setup mock request
        CLTelUWWrapper.Request req = generateMockRequest();
        setAccount();
        Test.startTest();
        CLTelUWWrapper.TelUWCallLineDataResponse response = RestCallLineTelUWSubmit.requestTelUW(req);
        Test.stopTest();

    }
    
    static testMethod void testRequestTelUW2() {
        // Setup mock request
        CLTelUWWrapper.Request req = new CLTelUWWrapper.Request();
        setAccount();
        Test.startTest();
        CLTelUWWrapper.TelUWCallLineDataResponse response = RestCallLineTelUWSubmit.requestTelUW(req);
        Test.stopTest();

    }

    static testMethod void testRescheduleTelUW() {
        // Setup mock request
        CLTelUWWrapper.Request req = generateMockRequest();
        req.policyNo = '521-1610430';
        req.scheduleDate = String.valueOf(DateTime.now().addDays(3));
        req.note = 'Reschedule Note';
        req.source = 'Banca';
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.Response response = RestCallLineTelUWSubmit.rescheduleTelUW(req);
        Test.stopTest();

    }
    
    static testMethod void testRescheduleTelUW2() {
        // Setup mock request
        CLTelUWWrapper.Request req = generateMockRequest();
        req.policyNo = '521-1610430';
        req.scheduleDate = String.valueOf(DateTime.now().addDays(3));
        req.note = 'Reschedule Note';
        req.source = 'Banca';
        setAccount();

        Test.startTest();
        CLTelUWWrapper.Response response = RestCallLineTelUWSubmit.rescheduleTelUW(req);
        Test.stopTest();

    }
    
    static testMethod void testRescheduleTelUW3() {
        // Setup mock request
        CLTelUWWrapper.Request req = generateMockRequest();
        req.policyNo = '521-1610430';
        req.scheduleDate = String.valueOf(DateTime.now().addDays(3));
        req.note = 'Reschedule Note';
        req.source = 'Banca';
        setAllData();

        Test.startTest();
        CLTelUWWrapper.Response response = RestCallLineTelUWSubmit.rescheduleTelUW(req);
        Test.stopTest();

    }
    
    static testMethod void testRescheduleTelUW4() {
        // Setup mock request
        CLTelUWWrapper.Request req = new CLTelUWWrapper.Request();
        setAccount();

        Test.startTest();
        CLTelUWWrapper.Response response = RestCallLineTelUWSubmit.rescheduleTelUW(req);
        Test.stopTest();

    }

    static testMethod void testGetCallLine() {
        CLTelUWWrapper.Request req = generateMockRequest();
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.TelUWCallLineDataResponse response = RestCallLineTelUWCheck.getCallLine(req);
        Test.stopTest();

    }
    
    static testMethod void testGetCallLine2() {
        CLTelUWWrapper.Request req = generateMockRequest();
        setAccount();

        Test.startTest();
        CLTelUWWrapper.TelUWCallLineDataResponse response = RestCallLineTelUWCheck.getCallLine(req);
        Test.stopTest();

    }
    
    static testMethod void testGetCallLine3() {
        CLTelUWWrapper.Request req = new CLTelUWWrapper.Request();
        setAllData();

        Test.startTest();
        CLTelUWWrapper.TelUWCallLineDataResponse response = RestCallLineTelUWCheck.getCallLine(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime() {
        CLTelUWWrapper.Request req = generateMockRequest();
        req.scheduleDate = String.valueOf(Date.today().addDays(1));
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime2() {
        CLTelUWWrapper.Request req = generateMockRequest();
        req.scheduleDate = String.valueOf(Date.today().addDays(2));
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime3() {
        CLTelUWWrapper.Request req = generateMockRequest();
        req.scheduleDate = String.valueOf(Date.today().addDays(3));
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime4() {
        CLTelUWWrapper.Request req = generateMockRequest();
        req.scheduleDate = String.valueOf(Date.today().addDays(4));
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime5() {
        CLTelUWWrapper.Request req = generateMockRequest();
        req.scheduleDate = String.valueOf(Date.today().addDays(5));
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime6() {
        CLTelUWWrapper.Request req = generateMockRequest();
        req.scheduleDate = String.valueOf(Date.today().addDays(6));
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime7() {
        CLTelUWWrapper.Request req = generateMockRequest();
        req.scheduleDate = String.valueOf(Date.today().addDays(7));
        setAllDataResch();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime8() {
        CLTelUWWrapper.Request req = new CLTelUWWrapper.Request();
        req.scheduleDate = String.valueOf(Date.today().addDays(7));
        setAccount();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testGetAvailTime9() {
        CLTelUWWrapper.Request req = new CLTelUWWrapper.Request();
        setAllAccountandContact();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse response = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();

    }
    
    static testMethod void testAvailTimeGenericException() {
        CLTelUWWrapper.Request req = new CLTelUWWrapper.Request();
        req.policyNo = 'POL123456';
        req.scheduleDate = 'invalid-date-format';
        setAllAccountandContact();

        Test.startTest();
        CLTelUWWrapper.CheckTimeAvailabilityResponse res = RestCallLineTelUWCheck.getAvailTime(req);
        Test.stopTest();
    }

    
    static testMethod void testGetAvailTimeNew() {
        setAccount();
        Test.startTest();
        CallLineTeluwHelper callLineTeluwHelper = new CallLineTeluwHelper();
        CallLineTeluwHelper.getAllTimeRescheduleNew();
        Test.stopTest();
    }

    // Helper method to generate mock request
    private static CLTelUWWrapper.Request generateMockRequest() {
        CLTelUWWrapper.Request req = new CLTelUWWrapper.Request();
        req.scheduleDate = String.valueOf(Date.today().addDays(2));
        req.note = 'Test Note';
        req.source = 'Banca';
        
        req.lastName = 'Adi Wijaya';
        req.policyNo = '521-1610430';
        req.policyNoNumeric = '5211610430';
        req.entity = 'AMFS';
        req.phone = '085716222996';
        req.mobilePhone = '085716222996';
        req.email = 'test@example.com';
        req.insuredName = 'Test Insured';
        req.insuredEmail = 'insured@example.com';
        req.policyApp = 'RLS';
        req.productCodePlan = 'M812N2D';
        req.totalPremium = '441379';
        req.premium = '441379';
        req.paymentType = 'M';
        req.gender = 'M';
        req.campaignType = 'TelUW';
        req.issuedDate = String.valueOf(Date.today());
        req.ape = '500000';
        req.contactCurrency = 'RP';
        return req;
    }
    
    private static void setAccount(){
        Account amfsTest = new Account();
        amfsTest.Name = 'Account AMFS';
        amfsTest.Entity__c = 'AMFS';
        insert amfsTest;
    }
    
    private static void setAllData(){
        Account amfsTest = new Account();
        amfsTest.Name = 'Account AMFS';
        amfsTest.Entity__c = 'AMFS';
        insert amfsTest;
        
        Contact cont = new Contact();
        cont.AccountId = amfsTest.Id;
        cont.LastName = 'Adi Wijaya';
        cont.Policy_No__c = '521-1610430';
        cont.Policy_No_Numeric__c = '5211610430';
        cont.Entity__c = 'AMFS';
        cont.Phone = '085716222996';
        cont.MobilePhone = '085716222996';
        cont.Email = 'test@example.com';
        cont.Insured_Name__c = 'Adi Wijaya';
        cont.Insured_Email__c = 'test@example.com';
        cont.PolicyApp__c = 'RLS';
        cont.Product_Code_Plant_TelUW__c = 'M812N2D';
        cont.Total_Premium__c = Decimal.valueOf('441379');
        cont.Premium__c = Decimal.valueOf('441379');
        cont.WelcomeCall_Payment_Type__c = 'M';
        cont.WelcomeCall_Gender__c = 'M';
        cont.Campaign_Type__c = 'TelUW';
        cont.Issued_Date_TelUw__c = Date.valueOf(String.valueOf(Date.today()));
        cont.APE_TelUW__c = Decimal.valueOf('441379');
        cont.Currency_TelUW__c = 'RP';
        insert cont;
    }
    
    private static void setAllAccountandContact(){
        Account amfsTest = new Account();
        amfsTest.Name = 'Account AMFS';
        amfsTest.Entity__c = 'AMFS';
        insert amfsTest;
        
        Contact cont = new Contact();
        cont.AccountId = amfsTest.Id;
        cont.LastName = 'Adi Wijaya';
        cont.Policy_No__c = '521-1610430';
        cont.Policy_No_Numeric__c = '5211610430';
        cont.Entity__c = 'AMFS';
        cont.Phone = '085716222996';
        cont.MobilePhone = '085716222996';
        cont.Email = 'test@example.com';
        cont.Insured_Name__c = 'Adi Wijaya';
        cont.Insured_Email__c = 'test@example.com';
        cont.PolicyApp__c = 'RLS';
        cont.Product_Code_Plant_TelUW__c = 'M812N2D';
        cont.Total_Premium__c = Decimal.valueOf('441379');
        cont.Premium__c = Decimal.valueOf('441379');
        cont.WelcomeCall_Payment_Type__c = 'M';
        cont.WelcomeCall_Gender__c = 'M';
        cont.Campaign_Type__c = 'TelUW';
        cont.Issued_Date_TelUw__c = Date.valueOf(String.valueOf(Date.today()));
        cont.APE_TelUW__c = Decimal.valueOf('441379');
        cont.Currency_TelUW__c = 'RP';
        insert cont;
        
        ID cliId = Schema.SObjectType.Call_List__c.getRecordTypeInfosByName().get('Confirmation AMFS').getRecordTypeId();
        Call_List__c cli = new Call_List__c();
        cli.Activity__c = 'Confirmation';
        cli.Campaign_Name__c = 'TelUW202507Automatic';
        cli.Case_Type_Config__c = 'TelUW';
        cli.Expired_Date__c = Date.valueOf(Date.today().addDays(30));
        cli.Entity__c = 'AMFS';
        cli.RecordTypeId = cliId;
        cli.WelcomeCall_Fg_Automatic__c = true;
        insert cli;
        
        ID wcRtId = Schema.SObjectType.Call_Line__c.getRecordTypeInfosByName().get('TelUW').getRecordTypeId();
        Call_Line__c cl = new Call_Line__c();
        cl.RecordTypeId = wcRtId;
        cl.Contact__c = cont.Id;
        cl.Call_List__c = cli.Id;
        cl.Call_Line_Status_TelUW__c = 'Open';
        cl.WelcomeCall_Call_Line_Status__c = 'Open';
        cl.Case_Type__c = 'TelUW';
        cl.Case_Type_Config__c = 'TelUW';
        cl.Contacted_Number__c = cont.mobilePhone;
        cl.Phone__c = cont.phone;
        cl.Activity__c = cli.Activity__c;
        cl.Policy_no__c = cont.Policy_No__c;
        cl.WelcomeCall_Schedule_Date__c = Date.today().addDays(2);
        cl.call_date__c = Date.today().addDays(2);
        cl.Entity__c = cont.Entity__c;
        insert cl;
    }
    
    private static void setAllDataResch(){
        Account amfsTest = new Account();
        amfsTest.Name = 'Account AMFS';
        amfsTest.Entity__c = 'AMFS';
        insert amfsTest;
        
        Contact cont = new Contact();
        cont.AccountId = amfsTest.Id;
        cont.LastName = 'Adi Wijaya';
        cont.Policy_No__c = '521-1610430';
        cont.Policy_No_Numeric__c = '5211610430';
        cont.Entity__c = 'AMFS';
        cont.Phone = '085716222996';
        cont.MobilePhone = '085716222996';
        cont.Email = 'test@example.com';
        cont.Insured_Name__c = 'Adi Wijaya';
        cont.Insured_Email__c = 'test@example.com';
        cont.PolicyApp__c = 'RLS';
        cont.Product_Code_Plant_TelUW__c = 'M812N2D';
        cont.Total_Premium__c = Decimal.valueOf('441379');
        cont.Premium__c = Decimal.valueOf('441379');
        cont.WelcomeCall_Payment_Type__c = 'M';
        cont.WelcomeCall_Gender__c = 'M';
        cont.Campaign_Type__c = 'TelUW';
        cont.Issued_Date_TelUw__c = Date.valueOf(String.valueOf(Date.today()));
        cont.APE_TelUW__c = Decimal.valueOf('441379');
        cont.Currency_TelUW__c = 'RP';
        insert cont;
        
        ID cliId = Schema.SObjectType.Call_List__c.getRecordTypeInfosByName().get('Confirmation AMFS').getRecordTypeId();
        Call_List__c cli = new Call_List__c();
        cli.Activity__c = 'Confirmation';
        cli.Campaign_Name__c = 'TelUW202507Automatic';
        cli.Case_Type_Config__c = 'TelUW';
        cli.Expired_Date__c = Date.valueOf(Date.today().addDays(30));
        cli.Entity__c = 'AMFS';
        cli.RecordTypeId = cliId;
        cli.WelcomeCall_Fg_Automatic__c = true;
        insert cli;
        
        User adminUser = new User(
            Alias = 'adminusr',
            Email = 'adminuser@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Admin',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'Asia/Jakarta',
            Username = 'adminuser' + DateTime.now().getTime() + '@example.com',
            Entity__c = 'AMFS'
        );
        insert adminUser;

        
        ID wcRtId = Schema.SObjectType.Call_Line__c.getRecordTypeInfosByName().get('TelUW').getRecordTypeId();
        Call_Line__c cl = new Call_Line__c();
        cl.RecordTypeId = wcRtId;
        cl.Contact__c = cont.Id;
        cl.Call_List__c = cli.Id;
        cl.Call_Line_Status_TelUW__c = 'Progress';
        cl.WelcomeCall_Call_Line_Status__c = 'Progress';
        cl.Case_Type__c = 'TelUW';
        cl.Case_Type_Config__c = 'TelUW';
        cl.Contacted_Number__c = cont.mobilePhone;
        cl.Phone__c = cont.phone;
        cl.Activity__c = cli.Activity__c;
        cl.Policy_no__c = cont.Policy_No__c;
        cl.WelcomeCall_Schedule_Date__c = Date.today().addDays(2);
        cl.call_date__c = Date.today().addDays(2);
        cl.Entity__c = cont.Entity__c;
        cl.OwnerId = adminUser.id;
        insert cl;
    }
    
    private static void setAllDataReschAgentFull(){
        Account amfsTest = new Account();
        amfsTest.Name = 'Account AMFS';
        amfsTest.Entity__c = 'AMFS';
        insert amfsTest;
        
        Contact cont = new Contact();
        cont.AccountId = amfsTest.Id;
        cont.LastName = 'Adi Wijaya';
        cont.Policy_No__c = '521-1610430';
        cont.Policy_No_Numeric__c = '5211610430';
        cont.Entity__c = 'AMFS';
        cont.Phone = '085716222996';
        cont.MobilePhone = '085716222996';
        cont.Email = 'test@example.com';
        cont.Insured_Name__c = 'Adi Wijaya';
        cont.Insured_Email__c = 'test@example.com';
        cont.PolicyApp__c = 'RLS';
        cont.Product_Code_Plant_TelUW__c = 'M812N2D';
        cont.Total_Premium__c = Decimal.valueOf('441379');
        cont.Premium__c = Decimal.valueOf('441379');
        cont.WelcomeCall_Payment_Type__c = 'M';
        cont.WelcomeCall_Gender__c = 'M';
        cont.Campaign_Type__c = 'TelUW';
        cont.Issued_Date_TelUw__c = Date.valueOf(String.valueOf(Date.today()));
        cont.APE_TelUW__c = Decimal.valueOf('441379');
        cont.Currency_TelUW__c = 'RP';
        insert cont;
        
        ID cliId = Schema.SObjectType.Call_List__c.getRecordTypeInfosByName().get('Confirmation AMFS').getRecordTypeId();
        Call_List__c cli = new Call_List__c();
        cli.Activity__c = 'Confirmation';
        cli.Campaign_Name__c = 'TelUW202507Automatic';
        cli.Case_Type_Config__c = 'TelUW';
        cli.Expired_Date__c = Date.valueOf(Date.today().addDays(30));
        cli.Entity__c = 'AMFS';
        cli.RecordTypeId = cliId;
        cli.WelcomeCall_Fg_Automatic__c = true;
        insert cli;
        
        User adminUser = new User(
            Alias = 'adminusr',
            Email = 'adminuser@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Admin',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'Asia/Jakarta',
            Username = 'adminuser' + DateTime.now().getTime() + '@example.com',
            Entity__c = 'AMFS'
        );
        insert adminUser;

        
        ID wcRtId = Schema.SObjectType.Call_Line__c.getRecordTypeInfosByName().get('TelUW').getRecordTypeId();
        Call_Line__c cl = new Call_Line__c();
        cl.RecordTypeId = wcRtId;
        cl.Contact__c = cont.Id;
        cl.Call_List__c = cli.Id;
        cl.Call_Line_Status_TelUW__c = 'Progress';
        cl.WelcomeCall_Call_Line_Status__c = 'Progress';
        cl.Case_Type__c = 'TelUW';
        cl.Case_Type_Config__c = 'TelUW';
        cl.Contacted_Number__c = cont.mobilePhone;
        cl.Phone__c = cont.phone;
        cl.Activity__c = cli.Activity__c;
        cl.Policy_no__c = cont.Policy_No__c;
        cl.WelcomeCall_Schedule_Date__c = Date.today().addDays(2);
        cl.call_date__c = Date.today().addDays(2);
        cl.Entity__c = cont.Entity__c;
        cl.OwnerId = adminUser.id;
        insert cl;
        
        Call_Line__c cl2 = new Call_Line__c();
        cl2.RecordTypeId = wcRtId;
        cl2.Contact__c = cont.Id;
        cl2.Call_List__c = cli.Id;
        cl2.Call_Line_Status_TelUW__c = 'Progress';
        cl2.WelcomeCall_Call_Line_Status__c = 'Progress';
        cl2.Case_Type__c = 'TelUW';
        cl2.Case_Type_Config__c = 'TelUW';
        cl2.Contacted_Number__c = cont.mobilePhone;
        cl2.Phone__c = cont.phone;
        cl2.Activity__c = cli.Activity__c;
        cl2.Policy_no__c = cont.Policy_No__c;
        cl2.WelcomeCall_Schedule_Date__c = Date.today().addDays(3);
        cl2.call_date__c = Date.today().addDays(3);
        cl2.Entity__c = cont.Entity__c;
        cl2.OwnerId = adminUser.id;
        insert cl2;
    }
    
}