force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Is_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Is_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatedPolicyController.cls
public class RelatedPolicyController {
    public List<Related_Policy__c> relatedPolicyList {get;set;}
    public List<RelatedPolicyView> relatedPolicyViewList {get;set;}
    public string callLineId {get; set;}
    
    public RelatedPolicyController (ApexPages.StandardController controller) {
        callLineId = controller.getID();
        
        populateList();
    }
    
    public class RelatedPolicyView{
        public boolean isSelected {get; set;}
        public string callLineId {get; set;}
        public string customerName {get; set;}
        public string policyNo {get; set;}      
        public string contactId {get; set;}      
    }
    
    public PageReference selectPolicy(){
        Call_Line__c cl = new Call_Line__c();
        integer selectedCounter = 0;
        for(RelatedPolicyView vw : relatedPolicyViewList){
            if(vw.isSelected){
                selectedCounter++;
                cl.id = vw.callLineId;
                cl.Contact__c = vw.contactId;
                cl.Is_Allowed__c = true;
                cl.Policy_No__c = vw.policyNo;
                break;
            }
        }
        if(selectedCounter>0){
            update cl;
            PageReference clPage = new ApexPages.StandardController(cl).view();
            //PageReference clPage = new PageReference('/'+cl.id+'?isdtp=vw');
            clPage.setRedirect(true);
            return clPage;
        }else{
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You have not selected one policy yet.'));
            return null;
        }
    }

    public PageReference cancel(){
        Call_Line__c cl = new Call_Line__c();
        cl.id = callLineId; 
        PageReference clPage = new ApexPages.StandardController(cl).view();
        clPage.setRedirect(true);
        return clPage;
    }

    
    public PageReference runclick() {
        String contactId = Apexpages.currentPage().getParameters().get('contactId');
        system.debug('>>>> contactId : '+contactId );

        relatedPolicyList = [select id, Call_Back__c, Contact_ID__c, Customer_Name__c, Policy_No__c, Call_Back__r.Contact__c from Related_Policy__c where Call_Back__c = :callLineId];
        
        RelatedPolicyView vw = null;
        relatedPolicyViewList = new List<RelatedPolicyView>();
        for(Related_Policy__c rp : relatedPolicyList){
            vw = new RelatedPolicyView();
            vw.isSelected = false;
            if(rp.Contact_ID__c == contactId){
                vw.isSelected = true;
            }
            vw.callLineId = rp.Call_Back__c;    
            vw.customerName = rp.Customer_Name__c;  
            vw.policyNo = rp.Policy_No__c;  
            vw.contactId = rp.Contact_ID__c;
            
            relatedPolicyViewList.add(vw);  
        }
        return null;
    
    }
    
    private void populateList(){
        relatedPolicyList = [select id, Call_Back__c, Contact_ID__c, Customer_Name__c, Policy_No__c, Call_Back__r.Contact__c from Related_Policy__c where Call_Back__c = :callLineId];
        
        RelatedPolicyView vw = null;
        relatedPolicyViewList = new List<RelatedPolicyView>();
        for(Related_Policy__c rp : relatedPolicyList){
            vw = new RelatedPolicyView();
            vw.isSelected = false;
            if(rp.Contact_ID__c == rp.Call_Back__r.Contact__c){
                vw.isSelected = true;
            }
            vw.callLineId = rp.Call_Back__c;    
            vw.customerName = rp.Customer_Name__c;  
            vw.policyNo = rp.Policy_No__c;  
            vw.contactId = rp.Contact_ID__c;
            
            relatedPolicyViewList.add(vw);  
        }
    }
}