force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Conservation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Survey Feedback</fullName>
            </value>
            <value>
                <fullName>Complaint Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount NI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Call_Status_Config__c</fullName>
    <label>Call Status Config</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Sudah Pay By System</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Cancel By System</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Inforced</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
            <value>
                <fullName>Not eligible contact</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Premium FU</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Survey - I Buy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Expired_Date__c</fullName>
    <formula>IF(ISPICKVAL(Case_Type__c, &apos;TelUW&apos;), DATEVALUE(WelcomeCall_Schedule_Date__c) + 30, if ( and(RecordType.Name == &apos;TeleService&apos;, NOT(ISBLANK(Due_Date__c)) ),  Due_Date__c , Call_List__r.Expired_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expired Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Conservation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Survey Feedback</fullName>
            </value>
            <value>
                <fullName>Complaint Case</fullName>
            </value>
            <value>
                <fullName>Customer Segmentation</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Teleservices</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Collection Task</fullName>
            </value>
            <value>
                <fullName>Reinstate</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Expired_Date__c</fullName>
    <description>Expired Date</description>
    <label>Expired Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/IsExpired__c.field-meta.xml
<CustomField>
    <fullName>IsExpired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/Trigger_CallLines_recalculate_testClass.cls
@isTest
public class Trigger_CallLines_recalculate_testClass {
    @isTest static void test(){
        Test.startTest();
        Profile agentProfileAMFS = [SELECT Id FROM Profile WHERE Name like 'Outbound Agent%AMFS' limit 1];
        UserRole agentRoleAMFS = [SELECT Id FROM UserRole WHERE Name like 'Outbound Agent%AMFS' limit 1];
        
        //List<User> usr = [Select Id From User Where IsActive = true AND UserRoleId = '00E90000001QoEXEA0' AND ProfileId = '00e90000001ypjCAAQ' Limit 2];
        List<User> usr = [Select Id From User Where IsActive = true AND UserRoleId = :agentRoleAMFS.Id AND ProfileId = :agentProfileAMFS.Id Limit 2];
        
        /*
        Profile agentProfileAMFS = [SELECT Id FROM Profile WHERE Name like 'Outbound Agent%AMFS' limit 1];
        UserRole agentRoleAMFS = [SELECT Id FROM UserRole WHERE Name like 'Outbound Agent%AMFS' limit 1];
        
        User us = new User(Alias = 'spv1', Email='spvAMFS@axa.co.id', 
      			EmailEncodingKey='UTF-8', LastName='spvAMFSTEST', LanguageLocaleKey='en_US', 
      			LocaleSidKey='en_US', ProfileId = agentProfileAMFS.Id, Entity__c = 'AMFS', 
      			TimeZoneSidKey='Asia/Jakarta', UserName='spvAMFSTEST@axa.co.id', UserRoleId = agentRoleAMFS.Id);
        insert us;
		*/
        
        //Insert User Detail
        User_Detail__c usrD = new User_Detail__c();
        usrD.Name = 'test';
        usrD.User__c = usr[0].Id;
        usrD.F_Entity__c = 'AMFS';
        Insert usrD;
        
        User_Detail__c usrD2 = new User_Detail__c();
        usrD2.Name = 'test2';
        usrD2.User__c = usr[1].Id;
        usrD2.F_Entity__c = 'AMFS';
        Insert usrD2;
        
        //Insert Campaign
        Call_List__c cmp = new Call_List__c();
        cmp.RecordTypeId = Schema.SObjectType.Call_List__c.getRecordTypeInfosByName().get('Collection AMFS').getRecordTypeId();
        cmp.Activity__c = 'Collection';
        cmp.Case_Type__c = 'Withdrawal';
        cmp.Expired_Date__c = System.today() + 100000;
        cmp.Entity__c = 'AMFS';
        cmp.IsExpired__c = false;
        Insert cmp;
        
        //Insert Account
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Entity__c = 'AMFS';
        Insert acc;
        
        //Insert Contact
        Contact con = new Contact();
        con.LastName = 'test mus';
        con.AccountId = acc.Id;
        Insert con;
        
        //Insert Agent_Distribution_History__c
        Agent_Distribution_History__c adh = new Agent_Distribution_History__c();
        adh.Amount__c = 123456;
        adh.Campaign__c = cmp.Id;
        adh.User_Detail__c = usrD.Id;
        Insert adh;
        
        Agent_Distribution_History__c adh2 = new Agent_Distribution_History__c();
        adh2.Amount__c = 123456;
        adh2.Campaign__c = cmp.Id;
        adh2.User_Detail__c = usrD2.Id;
        Insert adh2;
        
        //Insert Call Line
        Call_Line__c cl = new Call_Line__c();
        cl.Call_Status_Config__c = 'Hold';
        cl.Policy_No__c = '517-8475322';
        cl.Contact__c = con.Id;
        cl.Remark_Hold_Debet__c = 'test';
        cl.Call_List__c = cmp.Id;
        cl.OwnerId = usr[0].Id;
        cl.Agent__c = usr[0].Id;
        cl.APE_Total_Child__c = 1000000;
        cl.Entity__c = 'AMFS';
        cl.Activity__c = 'Collection';
        Insert cl;
        
        Call_Line__c cl2 = new Call_Line__c();
        cl2.Call_Status_Config__c = 'Hold';
        cl2.Policy_No__c = '517-8475321';
        cl2.Contact__c = con.Id;
        cl2.Remark_Hold_Debet__c = 'test2';
        cl2.Call_List__c = cmp.Id;
        cl2.OwnerId = usr[0].Id;
        cl2.Agent__c = usr[0].Id;
        cl2.APE_Total_Child__c = 1000000;
        cl2.Entity__c = 'AMFS';
        //cl2.Activity__c = 'Collection';
        Insert cl2;
        
        Call_Line__c cl3 = new Call_Line__c();
        cl3.Call_Status_Config__c = 'Hold';
        cl3.Policy_No__c = '517-8475321';
        cl3.Contact__c = con.Id;
        cl3.Remark_Hold_Debet__c = 'test2';
        cl3.Call_List__c = cmp.Id;
        cl3.OwnerId = usr[0].Id;
        cl3.Agent__c = usr[0].Id;
        cl3.APE_Total_Child__c = 1000000;
        cl3.Entity__c = 'AMFS';
        //cl2.Activity__c = 'Collection';
        Insert cl3;
        
        //Update Call Line
        cl.OwnerId = usr[1].Id;
        cl.Agent__c = usr[1].Id;
        cl2.OwnerId = usr[1].Id;
        cl2.Agent__c = usr[1].Id;
        List<Call_Line__c> clList = new List<Call_Line__c>();
        clList.add(cl);
        clList.add(cl2);
        Update clList;
        
        //Update Call Line Custom Remark
        System.runAs(usr[1]){
            cl.Call_Status_Config__c = 'N';
            Update cl;
            
            cl.Call_Remarks__c = 'hehheh coba';
            Update cl;
        }
        
        //Update Campaign
        cmp.IsExpired__c = true;
        update cmp;
        
        //Delete Call Line
        Delete clList;
        
        Test.stopTest();
    }
}