force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/job_id__c.field-meta.xml
<CustomField>
    <fullName>job_id__c</fullName>
    <label>job_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CallLineGroupingBatch.cls
//Arief - 3 April 2020 : Add AMFS_CallLine_ParentCounter,choosen_campaign,and userId at the finish of the job to count the child of the parent and APE total
public class CallLineGroupingBatch implements Database.Batchable<Call_Line__c> {
    public List<Call_Line__c> l_ba {get;set;}
    public id userId;
    public string choosen_campaign;
    
    public CallLineGroupingBatch(List<Call_Line__c> ba_l,String choosen_campaign,Id userId) {
        l_ba = ba_l;
        this.choosen_campaign = choosen_campaign;
        this.userId = userId;
    }
    
    public List<Call_Line__c> start(Database.BatchableContext BS) {
        return this.l_ba;
    }
    
    public void execute(Database.BatchableContext BS, List<Call_Line__c> l_ba) {
        //Coba mus
        /*
        if(l_ba.size() > 0){
            Call_List__c clJob = new Call_List__c();
            clJob.Id = l_ba[0].Call_List__c;
            clJob.job_id__c = BS.getJobId();
            Update clJob;
        }
		*/
        //Coba mus
        //userId = userInfo.getUserId();
        try {
          update l_ba;
        } catch (ListException e) {
        }
    }
    
    public void finish(Database.BatchableContext BS) {
        List<Call_List__c> checkEntity = [SELECT Id, Entity__c FROM Call_List__c WHERE Id =: choosen_campaign];
        
        if(checkEntity[0].Entity__c != 'ALI'){
            AMFS_CallLine_ParentCounter jb = new AMFS_CallLine_ParentCounter(choosen_campaign,userId,l_ba);
            Database.executeBatch(jb, 65);
        }
    }
}