force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/WelcomeCall_Call_Line_Status__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Call_Line_Status__c</fullName>
    <label>Call Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/WelcomeCall_Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Schedule_Date__c</fullName>
    <label>Schedule Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_APE__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_APE__c</fullName>
    <formula>IF(CONTAINS( $Label.APE_Product_Unit_Link+&apos;;&apos;+$Label.APE_Product_MDS+&apos;;&apos;+$Label.APE_Product_MDS_Teluw,  WelcomeCall_Product_Code_Plan__c+&apos;;&apos; ), ((	Total_Premium__c* IF(WelcomeCall_Payment_Type__c == &apos;A&apos;,1, IF(WelcomeCall_Payment_Type__c == &apos;S&apos;,2, IF(WelcomeCall_Payment_Type__c == &apos;Q&apos;,4, 12)))
)+( WelcomeCall_Lump_Sum__c *0.1)), 

IF(CONTAINS( $Label.APE_Product_Single_Premium ,WelcomeCall_Product_Code_Plan__c+&apos;;&apos;), 	
(Total_Premium__c+WelcomeCall_Lump_Sum__c )*0.1, 

IF(CONTAINS( $Label.APE_Product_Health ,WelcomeCall_Product_Code_Plan__c+&apos;;&apos;), (	Total_Premium__c + WelcomeCall_Lump_Sum__c ) * IF(WelcomeCall_Payment_Type__c == &apos;A&apos;,1, IF(WelcomeCall_Payment_Type__c == &apos;S&apos;,2, IF(WelcomeCall_Payment_Type__c == &apos;Q&apos;,4, 12))),0
)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Issued_Date__c</fullName>
    <label>Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Product_Code_Plan__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Product_Code_Plan__c</fullName>
    <label>Product Code Plan</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CallLineSPAJtest.cls
@isTest
public class CallLineSPAJtest {
    @isTest static void test1(){
        Id recTypeWC = Schema.SObjectType.Call_Line__c.getRecordTypeInfosByName().get('Welcome Call').getRecordTypeId();
            
        Contact contt = new Contact();
        contt.Policy_No__c = '515-3932503';
        contt.entity__c = 'AMFS'; 
        contt.policyApp__c = 'RLS';
        contt.phone = '45678'; 
        contt.Agent_Code__c = '675849';
        //contt.Welcomecall_Ape__c = 10000000;
        contt.WelcomeCall_Payment_Type__c ='M';
        contt.Premium__c=10000000;
        contt.welcomecall_issued_date__c = date.today();
        contt.welcomecall_product_code_plan__c = 'HONMN';
        contt.email = 'asdasd@gmail.com';
        contt.LastName = 'Telat';
        
        insert contt;
        
        Call_Line__c callL = new Call_Line__c();
        callL.Policy_No__c = contt.Policy_No__c;
        callL.WelcomeCall_Schedule_Date__c = datetime.now();
        callL.WelcomeCall_Call_Line_Status__c = 'Open';
        callL.RecordTypeId = recTypeWC;
        callL.Contact__c = contt.Id;
        
        insert callL;
            
        Test.setMock(HttpCalloutMock.class, new DetailNasabahCtrl_TestMock());
        test.startTest();
        apexpages.StandardController stdCon = new ApexPages.StandardController(callL);
        CallLineSPAJ testDNC = new CallLineSPAJ(stdCon);
         
        
        testDNC.populateDetailNasabah();
        test.stopTest();
    }
    
}