force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Call_Remarks__c</fullName>
    <label>Remarks</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Call_Status_Config__c</fullName>
    <label>Call Status Config</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Sudah Pay By System</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Cancel By System</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Inforced</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
            <value>
                <fullName>Not eligible contact</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Call_List__r.Campaign_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Premium FU</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Survey - I Buy</fullName>
            </value>
            <value>
                <fullName>Redemption TM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <label>Progress</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Status_Config__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Presented</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Reason_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Reason_Status_Config__c</fullName>
    <label>Reason Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Status_Config__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFI - Wrong Number</fullName>
            </value>
            <value>
                <fullName>Agent Personal Closing (Tdk Pernah Setuju)</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
            <value>
                <fullName>Agree - Agree switch to Credit Card</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Redemption</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Withdrawal</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via Autodebet</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via SO or Walk In</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Transfer</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Virtual Account</fullName>
            </value>
            <value>
                <fullName>Agree - Agree Top Up Lumpsum</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to reinstate</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Melengkapi Kekurangan Dokumen</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Menunggu Proses Claim</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi data polis</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi Data Rekening</fullName>
            </value>
            <value>
                <fullName>Agree - Menerima Penjelasan dari Agen</fullName>
            </value>
            <value>
                <fullName>Agree - Mengisi dan Menandatangani SPAJ</fullName>
            </value>
            <value>
                <fullName>Agree - Others</fullName>
            </value>
            <value>
                <fullName>Agree - Quisioner By Phone</fullName>
            </value>
            <value>
                <fullName>Agree - Sudah terima Buku polis</fullName>
            </value>
            <value>
                <fullName>Agree Surat Keluhan</fullName>
            </value>
            <value>
                <fullName>Agree - Tahapan</fullName>
            </value>
            <value>
                <fullName>Agree - Transferred to Other account</fullName>
            </value>
            <value>
                <fullName>Agree - Update Address</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data All</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data more than 1 item</fullName>
            </value>
            <value>
                <fullName>Agree - Update Document</fullName>
            </value>
            <value>
                <fullName>Cancel By System</fullName>
            </value>
            <value>
                <fullName>Sudah Pay By System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Status_has_call__c.field-meta.xml
<CustomField>
    <fullName>Status_has_call__c</fullName>
    <label>Status has call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Todo_Item__c.field-meta.xml
<CustomField>
    <fullName>Todo_Item__c</fullName>
    <label>Todo Item</label>
    <length>999</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Todo_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Todo_Item_Status__c</fullName>
    <label>Todo Item Status</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TodoAgent.cls
public class TodoAgent {
    
    public Boolean checkTasks {get; set;}
    public Boolean checkCl {get; set;}
    public Call_Line__c cl {get; set;}
    public Call_List__c campaign {get; set;}
    public List<TodoListWrapper> todos {get; set;}
    public List<String> items {get; set;}
    public List<String> statuses {get; set;}
    
    public TodoAgent(ApexPages.StandardController controller){
        todos = new List<TodoListWrapper>();

        Id clId = ApexPages.currentpage().getparameters().get('id');

        cl = new Call_Line__c();
        cl = [SELECT Id, Todo_Item__c, Todo_Item_Status__c, Call_List__c, Campaign_Name__c, Call_Remarks__c, Reason_Status_Config__c, Call_Status_Config__c, Status_has_call__c, Progress__c FROM Call_Line__c WHERE Id = :clId];
		campaign = [SELECT Id, Case_Type__c, Todo_List_Config__c FROM Call_List__c WHERE Id = :cl.Call_List__c];

        if (cl != null && campaign != null) {
            loadItems();
            checkTask();   
        }
    }
        
    public void loadItems() {
        Map<Object, List<String>> dependValues = DependentPicklistController.getDependentPicklistValues('Call_List__c', 'Todo_List_Config__c');
        
        items = new List<String>();
        statuses = new List<String>();
        
        if (cl.Todo_Item__c != null && cl.Todo_Item_Status__c != null) {
            items = cl.Todo_Item__c.split(',');
            statuses = cl.Todo_Item_Status__c.split(',');
        }
        
        for (Object key : dependValues.keySet()) {
            if (key == campaign.Case_Type__c) {
                items = dependValues.get(key);
            }
        }
        
        for (Integer i = 0; i < items.size(); i++) {
            Boolean status = (i < statuses.size() && statuses[i] == 'true') ? true : false;
            todos.add(new TodoListWrapper(items[i], status));
        }
    }
    
    public void save(){
        items = new List<String>();
        statuses = new List<String>();
        
        for (TodoListWrapper wrapper : todos) {
            items.add(wrapper.item);
            statuses.add(wrapper.isChecked ? 'true' : 'false');
            if (!wrapper.isChecked) checkTasks = false;
        }
        
        cl.Todo_Item__c = String.join(items,',');
        cl.Todo_Item_Status__c = String.join(statuses,',');
        
        checkTask();
        
        try {
            if (checkCl) update cl;
        } catch (DMLException e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error when save to-do list'));
        }
    }
    
    public void checkTask() {
        checkTasks = true;
        checkCl = true;
        for (TodoListWrapper item : todos) {
            if (!item.isChecked) {
                checkTasks = false;
                break;
            }
        }
        
        if (cl.Call_Status_Config__c == 'Approved' || cl.Call_Status_Config__c == 'Not Approved' || cl.Call_Status_Config__c == 'Sudah Pay By System' || cl.Call_Status_Config__c == 'N' || cl.Call_Status_Config__c == 'Y' || cl.Call_Status_Config__c == 'Cancel By System' || (cl.Progress__c == 'Presented' && cl.Campaign_Name__c.contains('Redemption TM'))){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Cannot edit To-Do List, Call Line is Closed!'));
            checkCl = false;
        }
        
        if (!checkTasks && (cl.Call_Status_Config__c == 'Uncontacted' || cl.Call_Status_Config__c == 'F' || cl.Call_Status_Config__c == 'P' || (cl.Call_Status_Config__c == null && cl.Reason_Status_Config__c == null && String.isBlank(cl.Call_Remarks__c)) || ((cl.Progress__c == 'Not Presented' || cl.Progress__c == null) && cl.Campaign_Name__c.contains('Redemption TM')))) {    
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'To-do list is not finished'));
        }
        
       	if (cl.Call_Status_Config__c == 'Takeout') {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Cannot edit To-Do List, Call Status/Reason Status/Remarks should not be blank!'));
            checkCl = false;
        }
         
        if (checkTasks && cl.Status_has_call__c != 'Closed'){
        	ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'To-Do List successfully done'));  
        } 

    }
    
    public class TodoListWrapper {
        public String item {get; set;}
        public Boolean isChecked {get; set;}
        
        public TodoListWrapper(String item, Boolean isChecked) {
            this.item = item;
            this.isChecked = isChecked;
        }
    }
}