force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No outbound agent has been configured yet</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Outbound Agent</value>
        </filterItems>
        <filterItems>
            <field>$Source.Entity__c</field>
            <operation>equals</operation>
            <valueField>User.Entity__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.Agent__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Parent_Call_Line__c.field-meta.xml
<CustomField>
    <fullName>Parent_Call_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>ALI - Group by</inlineHelpText>
    <label>Parent Call Line</label>
    <referenceTo>Call_Line__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <formula>IF((TEXT(Origin) != &apos;Email&apos; &amp;&amp; TEXT(Type) == &apos;Inquiry&apos; ),TEXT(Owner:User.Entity__c),Text(Entity_Backup__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FCR__c.field-meta.xml
<CustomField>
    <fullName>FCR__c</fullName>
    <defaultValue>true</defaultValue>
    <description>By default is checked as long as the process can be done directly.
In case of any raise ticketing (request/complaint), it will be unchecked</description>
    <label>FCR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Child_Case__c.field-meta.xml
<CustomField>
    <fullName>Last_Child_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Child Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases_del1_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerFuture.cls
global class TriggerFuture{
    @Future
    public static void UpdateParentCase(Id DataId, Id ParentId){
        //try { 

        Case cs = [SELECT id, Last_Child_Case__c, FCR__c FROM Case WHERE id =:ParentId ];

        case[] cs2 = [SELECT id, Last_Child_Case__c, FCR__c FROM Case WHERE id =:ParentId ];
        Approval.UnlockResult[] results = Approval.unlock(cs2, false);

    
        cs.FCR__c = FALSE;
        cs.Last_Child_Case__c = DataId;
        
        update cs;

        
//        } catch (Exception e) {
//            System.debug(e);
//        }
    }    
    
    // for ALI
    @Future
    public static void AgentScheduling(Id DataId){
        Agent_Scheduling__c ags = [SELECT id FROM Agent_Scheduling__c WHERE id =: DataId];
        update ags;
    }

    // for ALI - Update Call Line, set Agent.
    @Future
    public static void CallLineUpdateChild(Id DataId){
        List<call_line__c> listCL = new List<call_line__c>();
        for (call_line__c cl : [select id, Parent_Call_Line__c, agent__c, Parent_Call_Line__r.agent__c from call_line__c 
                                where agent__c = NULL and 
                                    Parent_Call_Line__r.agent__c != NULL and 
                                    //Entity__c = 'ALI' and 
                                    Parent_Call_Line__c != NULL
                                and Call_List__c =: DataId]){
            cl.agent__c = cl.Parent_Call_Line__r.agent__c;
            listCL.add(cl);
        }
        update listCL;
        

    }

    // for ALI - Auto Share to Agent
    @Future
    public static void ShareScoreCard(Id AccountId, Id ParentOwnerId, Id OldParentOwnerId, String AccountAccess){
        try { 
            if (ParentOwnerId <> OldParentOwnerId) {
                list <Score_Card__Share> acs = [SELECT id FROM Score_Card__Share WHERE ParentId =: AccountId and UserOrGroupId =: OldParentOwnerId];
                if (acs.size() > 0 && !Test.isRunningTest()) delete acs;
            }

            Score_Card__Share acctshare = new Score_Card__Share(ParentId = AccountID, UserOrGroupId = ParentOwnerId, AccessLevel = AccountAccess);
            if(!Test.isRunningTest()) upsert acctshare;
        } catch (Exception e) {
            System.debug(e);
        }
    }    

    // for ALI - Auto Share to Agent
    @Future
    public static void ShareAgentPerformance(Id AccountId, Id ParentOwnerId, Id OldParentOwnerId, String AccountAccess){
        try { 
            if (ParentOwnerId <> OldParentOwnerId) {
                list <Agent_Performance__Share> acs = [SELECT id FROM Agent_Performance__Share WHERE ParentId =: AccountId and UserOrGroupId =: OldParentOwnerId];
                if (acs.size() > 0 && !Test.isRunningTest()) delete acs;
            }

            Agent_Performance__Share acctshare = new Agent_Performance__Share(ParentId = AccountID, UserOrGroupId = ParentOwnerId, AccessLevel = AccountAccess);
            if(!Test.isRunningTest()) upsert acctshare;
        } catch (Exception e) {
            System.debug(e);
        }
    }
    
    //--Added by Suryono 31 Jan 2019
    @future
    public static void ShareAgentKPI(Id AccountId, Id ParentOwnerId, Id OldParentOwnerId, String AccountAccess){
        try { 
            if (ParentOwnerId <> OldParentOwnerId || Test.isRunningTest()) {
                List <Agent_KPI__Share> aksList = [SELECT id FROM Agent_KPI__Share WHERE ParentId =: AccountId and UserOrGroupId =: OldParentOwnerId];
                if (aksList.size() > 0 && !Test.isRunningTest()) {
                    delete aksList;
                }
            }

            Agent_KPI__Share accShare = new Agent_KPI__Share(ParentId = AccountID, UserOrGroupId = ParentOwnerId, AccessLevel = AccountAccess);
            if(!Test.isRunningTest()) upsert accShare;
        } catch (Exception e) {
            System.debug(e);
        }
    }
    //--End Added by Suryono 31 Jan 2019

    //--Added by Taufik 12 Feb 2019
    @future
    public static void ShareQualityControl(Id AccountId, Id ParentOwnerId, Id OldParentOwnerId, String AccountAccess){
        try { 
            if (ParentOwnerId <> OldParentOwnerId || Test.isRunningTest()) {
                List <Quality_Control__Share> aksList = [SELECT id FROM Quality_Control__Share WHERE ParentId =: AccountId and UserOrGroupId =: OldParentOwnerId];
                if (aksList.size() > 0 && !Test.isRunningTest()) {
                    delete aksList;
                }
            }

            Quality_Control__Share accShare = new Quality_Control__Share(ParentId = AccountID, UserOrGroupId = ParentOwnerId, AccessLevel = AccountAccess);
            if(!Test.isRunningTest()) upsert accShare;
        } catch (Exception e) {
            System.debug(e);
        }
    }
    //--End Added by Taufik 12 Feb 2019
    
}