force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/WelcomeCall_Call_Line_Status__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Call_Line_Status__c</fullName>
    <label>Call Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/WelcomeCall_Days__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Days__c</fullName>
    <formula>IF(ISNULL(WelcomeCall_First_Call_Date__c), 0,TODAY() - DATEVALUE(WelcomeCall_First_Call_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Freeze_Complaint_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Freeze_Complaint_End_Date__c</fullName>
    <inlineHelpText>The end of freeze date for survey participant. Type: I Complaint</inlineHelpText>
    <label>Freeze Complaint End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_APE__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_APE__c</fullName>
    <formula>IF(CONTAINS( $Label.APE_Product_Unit_Link+&apos;;&apos;+$Label.APE_Product_MDS+&apos;;&apos;+$Label.APE_Product_MDS_Teluw,  WelcomeCall_Product_Code_Plan__c+&apos;;&apos; ), ((	Total_Premium__c* IF(WelcomeCall_Payment_Type__c == &apos;A&apos;,1, IF(WelcomeCall_Payment_Type__c == &apos;S&apos;,2, IF(WelcomeCall_Payment_Type__c == &apos;Q&apos;,4, 12)))
)+( WelcomeCall_Lump_Sum__c *0.1)), 

IF(CONTAINS( $Label.APE_Product_Single_Premium ,WelcomeCall_Product_Code_Plan__c+&apos;;&apos;), 	
(Total_Premium__c+WelcomeCall_Lump_Sum__c )*0.1, 

IF(CONTAINS( $Label.APE_Product_Health ,WelcomeCall_Product_Code_Plan__c+&apos;;&apos;), (	Total_Premium__c + WelcomeCall_Lump_Sum__c ) * IF(WelcomeCall_Payment_Type__c == &apos;A&apos;,1, IF(WelcomeCall_Payment_Type__c == &apos;S&apos;,2, IF(WelcomeCall_Payment_Type__c == &apos;Q&apos;,4, 12))),0
)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Issued_Date__c</fullName>
    <label>Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Payment_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Payment_Type_Name__c</fullName>
    <formula>CASE( WelcomeCall_Payment_Type__c , 
&quot;M&quot;, &quot;Bulan&quot;, 
&quot;Q&quot;, &quot;Triwulan&quot;,
&quot;S&quot;, &quot;Semester&quot;,
&quot;A&quot;, &quot;Tahun&quot;,
&quot;&quot;

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Product_Code_Plan__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Product_Code_Plan__c</fullName>
    <label>Product Code Plan</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/DetailNasabahRMCtrl.cls
public class DetailNasabahRMCtrl {
    public DetailTask dTask {get;set;}
    private Boolean isIncludeRLS = false;
    private Contact ct = new Contact();
    private Call_line__c cl = new Call_line__c();
    
    public DetailNasabahRMCtrl(ApexPages.StandardController controller) {
        try {   
            cl = (Call_Line__c)controller.getRecord();
            cl = [Select id, name, contact__c, createddate, WelcomeCall_Days__c, WelcomeCall_Call_Line_Status__c from Call_Line__c where id =: cl.Id];
            ct =[Select id, name, policy_no__c, entity__c, policyApp__c, phone, Agent_Code__c ,
                         welcomecall_ape__c, welcomecall_issued_date__c, welcomecall_product_code_plan__c, email,
                         WelcomeCall_Payment_Type_Name__c, welcomecall_effective_date__c, MobilePhone,
                         Birthdate, Total_Premium__c, Freeze_Complaint_End_Date__c
                         from contact where id =: cl.Contact__c];
            EIPJson eip = EIPConnector.getPolicyDetails('Policy Details',ct.Entity__c, ct.PolicyApp__c,ct.policy_no__c);
            system.debug('insurancePolicy = '+eip.Body.IcAx_AXAAsiaCustomer_Type.hasPolicyAccount[0]);
            dTask =  new DetailTask(eip.Body.IcAx_AXAAsiaCustomer_Type.hasPolicyAccount[0]);

        }catch(EIPConnector.NoDataException e){
            system.debug(e.getMessage());
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Backend sedang offline.'));
        }catch(EIPConnector.EIPConnectorException e){
            system.debug('unexpected error');
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Ada masalah ketika pengambilan data, silahkan hubungi Admin.'));
        }catch (exception E){
            System.debug('=== ERROR MESSAGE === '+E.getMessage());
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Ada masalah ketika pengambilan data, silahkan hubungi Admin.'));
        }
        
    }
    
    public void loadDataEip(){}
    
    public class DetailTask{
        public Date birthDate {get;set;}
        public Decimal totalPremium {get;set;}
        public Date dueDate {get;set;}

        public DetailTask(EIPJson.EIP_AgSa_InsurancePolicy insurancePolicy){
            system.debug('detail task started...'+ insurancePolicy.premiumAMT);
            totalPremium = CCCUtils.strToDec(insurancePolicy.premiumAMT);
            system.debug('total premium done');
            dueDate = CCCUtils.strToDate(insurancePolicy.policyDueDt,'yyyymmdd');
            system.debug('due date done');
            birthDate = CCCUtils.strToDate(insurancePolicy.hasDetailsOfRisksIn[0].hasPersonalDetailsIn[0].birthDT,'yyyymmdd');
            system.debug('birthDate done');
        }
    }
}