force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Activity_Config__c.field-meta.xml
<CustomField>
    <fullName>Activity_Config__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Conservation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Survey Feedback</fullName>
            </value>
            <value>
                <fullName>Complaint Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No outbound agent has been configured yet</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Outbound Agent</value>
        </filterItems>
        <filterItems>
            <field>$Source.Entity__c</field>
            <operation>equals</operation>
            <valueField>User.Entity__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.Agent__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/APE__c.field-meta.xml
<CustomField>
    <fullName>APE__c</fullName>
    <label>APE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Call_Status_Config__c</fullName>
    <label>Call Status Config</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Sudah Pay By System</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Cancel By System</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Inforced</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
            <value>
                <fullName>Not eligible contact</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Call_List__r.Campaign_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Collection_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Collection_Call_Date__c</fullName>
    <label>Collection Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contacted_Number__c.field-meta.xml
<CustomField>
    <fullName>Contacted_Number__c</fullName>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <formula>IF (ISBLANK(Parent_Call_Line__c), &quot;Parent&quot;, &quot;Child&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent ?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>ALI</description>
    <inlineHelpText>ALI 
Exp : HPE01</inlineHelpText>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Reason_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Reason_Status_Config__c</fullName>
    <label>Reason Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Status_Config__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFI - Wrong Number</fullName>
            </value>
            <value>
                <fullName>Agent Personal Closing (Tdk Pernah Setuju)</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
            <value>
                <fullName>Agree - Agree switch to Credit Card</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Redemption</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Withdrawal</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via Autodebet</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via SO or Walk In</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Transfer</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Virtual Account</fullName>
            </value>
            <value>
                <fullName>Agree - Agree Top Up Lumpsum</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to reinstate</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Melengkapi Kekurangan Dokumen</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Menunggu Proses Claim</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi data polis</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi Data Rekening</fullName>
            </value>
            <value>
                <fullName>Agree - Menerima Penjelasan dari Agen</fullName>
            </value>
            <value>
                <fullName>Agree - Mengisi dan Menandatangani SPAJ</fullName>
            </value>
            <value>
                <fullName>Agree - Others</fullName>
            </value>
            <value>
                <fullName>Agree - Quisioner By Phone</fullName>
            </value>
            <value>
                <fullName>Agree - Sudah terima Buku polis</fullName>
            </value>
            <value>
                <fullName>Agree Surat Keluhan</fullName>
            </value>
            <value>
                <fullName>Agree - Tahapan</fullName>
            </value>
            <value>
                <fullName>Agree - Transferred to Other account</fullName>
            </value>
            <value>
                <fullName>Agree - Update Address</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data All</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data more than 1 item</fullName>
            </value>
            <value>
                <fullName>Agree - Update Document</fullName>
            </value>
            <value>
                <fullName>Cuti Premi</fullName>
            </value>
            <value>
                <fullName>No Pickup/ Mailbox</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Reschedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Reschedule_Date__c</fullName>
    <description>Date/time on which we got reminded of contacting customer</description>
    <label>Reschedule Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Status_has_call__c.field-meta.xml
<CustomField>
    <fullName>Status_has_call__c</fullName>
    <label>Status has call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Status_Retry__c.field-meta.xml
<CustomField>
    <fullName>Status_Retry__c</fullName>
    <label>Status Retry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Callback from CCC</fullName>
            </value>
            <value>
                <fullName>Booking Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/classes/Call_Line_AMFS_Collection.cls
public class Call_Line_AMFS_Collection {
    Public String idparam {get;set;}
    public integer index {get;set;}
    public integer blockSize {get;set;}
    public integer totalRecs {get;set;}
    public integer totalAllRecs {get;set;}
    public Boolean fetchCalled;
    Public String filcampname {get;set;}
    Public String filcallstatus {get;set;}
    Public Profile pro {get;set;}
    PUBLIC String SOQL {get;set;}
    Public String offering {get;set;}
    Public String stapol {get;set;}
    Public String entityUser {get;set;}
    Public boolean campaignCheck {get;set;}
    Public String filretry {get;set;}
    Public String infoPendingSet {get;set;}
    Public String campaignName {get;set;}
    Public String batchNoSet {get; set;}
    
    Public String campName {
        get{
            String campaignNameList = '';
            if(filcampname != Null){
                if(filcampname != 'Collection Pending') {
                	campaignNameList = [select id,Campaign_Name__c from call_list__c where id = :filcampname].Campaign_Name__c;
                    campaignName = campaignNameList;
                } else campaignName = 'Collection Pending';
            }
            return campaignNameList;
        }
        set;
    }
    
    public String sortDir {
        get  { if (sortDir == null) {  sortDir = 'asc'; } return sortDir;  }
        set;
    }
    public void toggleSort() {
        sortDir = sortDir.equals('asc') ? 'desc' : 'asc';
        fetch();
    }
    public String sortField {
        get  { if (sortField == null) {sortField = 'Createddate'; } return sortField;  }
        set;
    }
    public Call_Line_AMFS_Collection(){
        index = 0;
        blockSize = 10;
        idparam = '';
        stapol = '';
        Offering = 'All';
        filcallstatus='No';
        campaignCheck = false;
        pro = [select name from Profile where id=:UserInfo.getProfileId()];
        entityUser = [Select Entity__c From User Where Id = :UserInfo.getUserId()].Entity__c;
	}
    
    public void fetch(){
        DescribeSObjectResult describeResultdp = Call_Line__c.getSObjectType().getDescribe();
        List<String> dpFieldList = new List<String>(describeResultdp.fields.getMap().keySet());
        String dpFields = String.join(dpFieldList, ',');
        String fields = 'Campaign_Name__c, Status_Retry__c, Status_has_call__c, CreatedDate, Name, Policy_No__c, Contact__c, Parent__c, APE__c, Product__c, Agent__c, Collection_Call_Date__c, '
            +'Call_Status_Config__c, Reason_Status_Config__c, Reschedule_Date__c, Contacted_Number__c, Activity_Config__c, Case_Type_Config__c, Call_Line__c.APE_Convert__c, Call_Line__c.Formula_Product__c, '
            +'Call_Line__c.Activity__c, Call_Line__c.Case_Type__c, Call_Line__c.Amount__c, Batch_no__c,Attemp_Call__c,Attempt_call_Day__c';
        
        //String qr = 'SELECT count(id) cid FROM Call_Line__c where Parent_Campaign__c!=null and Is_Expired__c = false ';
        // taufik, khusus untuk Campaign Pending, tapi sudah expired.
        String qr = '';
        qr = 'SELECT count(id) cid FROM Call_Line__c where Parent_Campaign__c!=null and Is_Expired__c = false ';
        if (filcampname == 'Collection Pending')
            qr = 'SELECT count(id) cid FROM Call_Line__c where Parent_Campaign__c!=null and Parent_Campaign__r.IsExpired__c = TRUE and Status_has_call__c = '+'\'Pending\''+' ';
        
        if (filcampname == 'Collection Pending')
	        soql = 'SELECT '+fields+' FROM Call_Line__c where Parent_Campaign__c!=null and Parent_Campaign__r.IsExpired__c = TRUE ';
		else
	        soql = 'SELECT '+fields+' FROM Call_Line__c where Parent_Campaign__c!=null and Is_Expired__c = false ';

        if(filcampname == 'Collection Pending') soql = soql + ' and Status_has_call__c = \'Pending\' ';
        else if(filcampname!=null && filcampname!='') soql = soql + ' and Call_List__c='+'\''+filcampname+'\''+' ';
        
        //if(filcallstatus!=NULL && filcallstatus!='' && filcallstatus != 'All') soql = soql + ' and  Call_Status_Config__c='+'\''+filcallstatus+'\''+' ';
        
        if(filcallstatus!=NULL && filcallstatus!='' && filcallstatus != 'All') {
            String callStatus = '';
            if(filcallstatus == 'Closed'){
                callStatus = ' AND (Call_Status_Config__c = \'Approved\' OR Call_Status_Config__c = \'Not Approved\' OR Call_Status_Config__c = \'N\' OR Call_Status_Config__c = \'Y\''
                    +'OR Call_Status_Config__c = \'Cancel By System\' OR Call_Status_Config__c = \'Cencel\' OR Call_Status_Config__c = \'Inforce\')' +' ';
            } else if(filcallstatus == 'Pending'){
                callStatus = ' AND (Call_Status_Config__c = \'Uncontacted\' OR Call_Status_Config__c = \'F\' OR Call_Status_Config__c = \'P\' OR Call_Status_Config__c = \'Pending\' OR Call_Status_Config__c = \'Retry\')' +' ';
            } else if(filcallstatus == 'Takeout'){
                callStatus = ' AND (Call_Status_Config__c = \'Takeout\')' +' ';
            } else if(filcallstatus == 'Blank'){
                callStatus = ' AND (Call_Status_Config__c = null OR Call_Status_Config__c = \'\')' +' ';
            }
            soql = soql +callStatus +' ';
        }
        
        if(batchNoSet != NULL && batchNoSet != '' && batchNoSet != 'All'){
            String batch = '';
            if(batchNoSet == '(none)'){
                batch = ' AND Batch_No__c = null ';
            } else {
                batch = ' AND Batch_No__c = \'' +batchNoSet +'\' ';
            }
            soql = soql +batch +' ';
        }
        
        if(filcampname!=null && filcampname!=''){
            if(infoPendingSet != Null && infoPendingSet != 'All' && infoPendingSet != ''){
                String pending = ' AND Info_Pendingan__c = \'' +infoPendingSet +'\' ';
                soql = soql + pending + ' ';
            }
        }
                
        if(filretry != null && filretry != 'All') soql = soql + ' AND Status_Retry__c='+'\''+filretry+'\''+' ';
        /*
        if(filcallstatus=='Yes' && filcallstatus!=NULL) soql = soql + ' and Call_Status_Config__c != NULL ' ;
        if(filcallstatus=='No' && filcallstatus!=NULL) soql = soql + ' and Call_Status_Config__c = NULL ';
        if(offering!='All' && offering!= NULL )soql = soql + ' and Offering__c = '+'\''+offering+'\''+' ';
        if(filcallstatus=='Rescheduled'  && filcallstatus!=NULL) soql = soql + ' and Call_Status_Config__c = '+'\''+filcallstatus+'\''+' ';
        if(filcallstatus== 'No Pickup/ Mailbox' && filcallstatus!=NULL ) soql = soql + ' and Reason_Status_Config__c = '+'\''+filcallstatus+'\''+' ';
		*/
        if(stapol!='' && stapol!=null) soql = soql + ' and Status_Polis__c = '+'\''+stapol+'\''+' ';
        system.debug('#query : '+soql);
        if(pro.Name=='System Administrator'){
        
        }
        else{
            qr = qr + ' and agent__c ='+'\''+UserInfo.getUserId()+'\''+' ';
            soql = soql+' and agent__c ='+'\''+UserInfo.getUserId()+'\''+' ';
        }
        AggregateResult ar = Database.query(qr);
        totalAllRecs = Integer.valueOf(ar.get('cid'));
        soql = soql + ' order by '+SortField+' '+sortDir;
        soql = soql + ' limit 40000 ';
        //List<Call_Line__c> listcl = Database.query(soql);
        //totalrecs = listcl.size();     
    }
    
    public List<Call_Line__c> getListCall(){
        List<Call_Line__c> listcl = new List<Call_Line__c>();
        fetch();
        //String dpQuery = soql + ' LIMIT ' + blockSize + ' OFFSET ' + index;
        List<Call_Line__c> listcl2 = new List<Call_Line__c>();

        if(test.isRunningTest()==false){
            listcl2 = Database.query(soql);
            totalrecs = listcl2.size();
            Integer endblock = blockSize + index;
            if(endblock>=totalRecs) endblock = totalRecs;
            for(Integer i = index ; i < endblock ; i++){
                listcl.add(listcl2.get(i));
            }
        }
        else{
            listcl2 = Database.query('select id, name from call_line__c limit 100');
            listcl = listcl2;
        }
        
        if (filcampname != null){
            // Taufik, 14 Mar20, add function collection pending.
            String campaignName = 'Collection Pending';
            if (filcampname != 'Collection Pending')
        		campaignName = [select id,Campaign_Name__c from call_list__c where id = :filcampname].Campaign_Name__c;
                
            if (campaignName.Contains('Withdrawal') || campaignName.contains('Redemption Konven')){
                campaignCheck = true;
            }
            else {
                campaignCheck = false;
            }    
        }
        //system.debug('*query*'+dpquery);
        //listcl = Database.query(dpQuery);
        return listcl;
    }
    
    public void UpdateCallLine(){
        if(idparam!=null){
            try{
                Call_Line__c cl = [select id, name, last_call__c from call_line__c where id=:idparam];
                cl.Last_Call__c = dateTime.now();
                update cl;    
            }
            catch(exception e){
                system.debug(LoggingLevel.DEBUG,'*error*'+e);
            }
            idparam = '';
        }
    }
    
    public List<SelectOption> getStatusRetry(){
        List<SelectOption> options = new List<SelectOption>();
        
        Schema.DescribeFieldResult fieldResult = Call_Line__c.Status_Retry__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('All','All'));
        for( Schema.PicklistEntry f : ple){
        	options.add(new SelectOption(f.getLabel(), f.getValue()));    
        }    
         return options;   
     }
    
     public List<SelectOption> getCampaignlist(){
         List<SelectOption> options = new List<SelectOption>();

         String query;
         String dpQuery = 'SELECT Call_List__c FROM Call_Line__c where (Parent_Campaign__c!=null OR Campaign_Name__c !=null) and Is_Expired__c = false ';
         if(pro.Name=='System Administrator'){
        
         }
         else{
             dpQuery = dpQuery+' and agent__c ='+'\''+UserInfo.getUserId()+'\''+' ';
         }
		 //updated by Fajar Salam 
		 //for ordering and prevent for random value
         if (entityUser == 'AMFS') query = 'SELECT id, Campaign_Name__c  from Call_List__c where recordtype.name = '+'\''+'Collection AMFS'+'\''+' and IsExpired__c = false and id in ('+dpquery+') order by createdDate DESC, Campaign_Name__c';
         options.add(new SelectOption('','--All--'));
         for(Call_List__c ar: Database.query(query)){
             options.add(new SelectOption(AR.id, ar.Campaign_Name__c));
         }
         options.add(new SelectOption('Collection Pending', 'Collection Pending'));
         return options;   
     }
    
    public List<SelectOption> getCallStatus(){
        //List<SelectOption> options = new List<SelectOption>();
        //String opsi = label.cl_callstatus;
        //List<String> listopsi = new List<String>();
        //if(opsi!=null && opsi!='') listopsi = opsi.split(';');
        //Schema.DescribeFieldResult picklistCallStatus = Call_Line__c.Call_Status_Config__c.getDescribe();
        //List<Schema.PicklistEntry> ple = picklistCallStatus.getPicklistValues();
        //if(!picklistCallStatus.isEmpty()){
            //for(Schema.PicklistEntry s : ple){
            //    options.add(new SelectOption(s.getLabel(),s.getLabel()));
            //}options.add(new SelectOption('All','All'));
        //} 
        
        List<SelectOption> options = new List<SelectOption>();
        if (filcampname != null|| Test.isRunningTest()){
            
        	if (campaignName.contains('Lapse Konven') || Test.isRunningTest()) {
                //options.add(new SelectOption('Approved','Approved'));
                
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }        
            if (campaignName.contains('MKP') || Test.isRunningTest()) {
                //options.add(new SelectOption('Not Approved','Not Approved'));
                
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }
            if (campaignName.contains('Cuti Premi') || Test.isRunningTest()) {
                //options.add(new SelectOption('Uncontacted','Uncontacted'));
                
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }
            if (campaignName.contains('RTU') || Test.isRunningTest()) {
                /*
                options.add(new SelectOption('Sudah Pay by System','Sudah Pay by System'));
                options.add(new SelectOption('Reschedule','Reschedule'));
                options.add(new SelectOption('All','All'));
                */
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }
            if (campaignName.contains('Renewal Reminder') || campaignName.contains('TRO Project') || campaignName.contains('Others') || Test.isRunningTest()) {
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }
            if (campaignName.contains('Redemption Konven') || Test.isRunningTest()) {
                //options.add(new SelectOption('F','F'));
                
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }
            if (campaignName.contains('Withdrawal') || Test.isRunningTest()) {
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }
            if (campaignName.contains('Lapse TM') || Test.isRunningTest()) {
                /*
                options.add(new SelectOption('Approved','Approved'));
                options.add(new SelectOption('Not Approved','Not Approved'));
                options.add(new SelectOption('Uncontacted','Uncontacted'));
                options.add(new SelectOption('Sudah Pay by System','Sudah Pay by System'));
                options.add(new SelectOption('Cancel by System','Cancel by System'));
                options.add(new SelectOption('Reschedule','Reschedule'));
                options.add(new SelectOption('All','All'));
                */
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }
            if (campaignName.contains('Redemption TM') || Test.isRunningTest()) {
                options.add(new SelectOption('All','All'));
                options.add(new SelectOption('Blank','Blank (none)'));
                options.add(new SelectOption('Pending','Pending'));
                options.add(new SelectOption('Closed','Closed'));
                options.add(new SelectOption('Takeout','Takeout'));
            }    
        }
        else options.add(new SelectOption('None','None'));
        
        return options;   
     }
    
    public List<SelectOption> getBlock_Size(){
        List<SelectOption> options = new List<SelectOption>();
        String opsi = label.CL_BlockSize;
        List<String> listopsi = new List<String>();
        if(opsi!=null && opsi!='') listopsi = opsi.split(';');
        if(listopsi.size()>0){
            for(String s:listopsi){
                options.add(new SelectOption(s,s));
            }
        }
		return options;   
     }
    
    public List<SelectOption> getOffering_pick(){
        List<SelectOption> options = new List<SelectOption>();
        String opsi = label.CL_Offering;
        List<String> listopsi = new List<String>();
        if(opsi!=null && opsi!='') listopsi = opsi.split(';');
        if(listopsi.size()>0){
            for(String s:listopsi){
                options.add(new SelectOption(s,s));
            }
        }
        return options;   
     }
    
    public List<SelectOption> getStatus_Polis(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','None'));
        String opsi = label.CL_StatusPolis;
        List<String> listopsi = new List<String>();
        if(opsi!=null && opsi!='') listopsi = opsi.split(';');
        if(listopsi.size()>0){
            for(String s:listopsi){
                options.add(new SelectOption(s,s));
            }
        }
        return options;   
     }
    
    public List<SelectOption> infoPendingan{
        get{
            List<SelectOption> options = new List<SelectOption>();
            Schema.DescribeFieldResult fieldResult = Call_Line__c.Info_Pendingan__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            options.add(new SelectOption('All','All'));
            for( Schema.PicklistEntry f : ple)
                options.add(new SelectOption(f.getLabel(), f.getValue()));
            return options;
        }
    }
    
    public List<SelectOption> batchNo{
        get{
            List<SelectOption> options = new List<SelectOption>();
            List<AggregateResult> batchList = [Select Batch_No__c from Call_line__c where Parent_Campaign__c = :filcampname group by Batch_No__c];
            options.add(new SelectOption('All','All'));
            for(AggregateResult bn : batchList){
                String batch = String.ValueOf(bn.get('Batch_No__c'));
                if(batch == Null) batch = '(none)';
                options.add(new SelectOption(batch, batch));
            }
            return options;
        }
    }
    
    public void beginning()
    {
        index = 0;
        fetch();
    }
    
    public void previous()
    {
        index = index - blockSize;
    }
    
    public void next()
    {
        index = index + blockSize;
        system.debug(LoggingLevel.DEBUG, '*index*'+index);
    }
    
    public void end()
    {
        index = totalrecs - math.mod(totalRecs,blockSize);
    }
    
    public boolean getprev()
    {
        if(index == 0)
        return true;
        else
        return false;
    }
    
     public boolean getnxt()
    {
        if((index + blockSize) >= totalRecs)
        return true;
        else
        return false;
    }
}