force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Count_Failed_Upload__c.field-meta.xml
<CustomField>
    <fullName>Count_Failed_Upload__c</fullName>
    <label>Count Failed Upload</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Count_Upload__c.field-meta.xml
<CustomField>
    <fullName>Count_Upload__c</fullName>
    <label>Count Upload</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CallLineUpdateBatch.cls
public class CallLineUpdateBatch implements Database.Batchable<Call_Line__c>{
    public List<Call_Line__c> l_ba {get;set;}
    
    public CallLineUpdateBatch(List<Call_Line__c> ba_l) {
        l_ba = ba_l;
    }
    
    public List<Call_Line__c> start(Database.BatchableContext BS) {
        return this.l_ba;
    }
    
    public void execute(Database.BatchableContext BS, List<Call_Line__c> l_ba) {
        
        list<Call_List__c> cl = [SELECT id, Count_Upload__c, Count_Failed_Upload__c FROM Call_List__c WHERE id =: l_ba[0].Call_List__c];
        try {
            update l_ba;
            
            if (cl[0].Count_Upload__c == NULL) cl[0].Count_Upload__c = 0;
            cl[0].Count_Upload__c += l_ba.size();
            update cl;
        } catch (ListException e) {
            if (cl[0].Count_Failed_Upload__c == NULL) cl[0].Count_Failed_Upload__c = 0;
            cl[0].Count_Failed_Upload__c += l_ba.size();
            update cl;            
        }
    }
    
    public void finish(Database.BatchableContext BS) {
        
    }
}