force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No outbound agent has been configured yet</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Outbound Agent</value>
        </filterItems>
        <filterItems>
            <field>$Source.Entity__c</field>
            <operation>equals</operation>
            <valueField>User.Entity__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.Agent__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.ContactId</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Other_Phone__c.field-meta.xml
<CustomField>
    <fullName>Other_Phone__c</fullName>
    <label>Other Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Mobile_F__c.field-meta.xml
<CustomField>
    <fullName>Mobile_F__c</fullName>
    <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
IF (LEFT(MobilePhone,2)== &quot;62&quot;,&quot;0&quot;&amp;RIGHT(MobilePhone,LEN(MobilePhone)-2),MobilePhone)
, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)
, &quot;/&quot;, &quot;&quot;)
, &quot;;&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile_F</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Other_Phone__c.field-meta.xml
<CustomField>
    <fullName>Other_Phone__c</fullName>
    <label>Other Phone</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>none</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/Redirect_Contact.cls
public class Redirect_Contact {
    List<Contact> listcontact{get;set;}
    Public String urlval{get;set;}
    Public String strval{get;set;}
    Public String ids {get;set;}
    Public String contact_name {get;set;}
    public Redirect_Contact(ApexPages.StandardController controller){
        strval ='';        urlval='';        contact_name='';        ids = ApexPages.CurrentPage().getParameters().get('id');
        system.debug('*ids*'+ids);
    }
    
    public Redirect_Contact(){
        if(test.isRunningTest()){
            strval ='';
            urlval='';
            contact_name='';
            //Log_CTI_Valdo__c lcti =  [select id from Log_CTI_Valdo__c limit 1];
            //ids = lcti.id;
            system.debug('*ids*'+ids);    
        }
    }

    
    public void actionfunction(){
        if(ids!=null || test.isRunningTest()){
            Log_CTI_Valdo__c lcti = new Log_CTI_Valdo__c();
            /*
            if(test.isRunningTest()){
                lcti.sip__c = '703';
                lcti.to__c = '703';
                lcti.from__c = '12345678';
                lcti.Status__c = 'Inbound';
                lcti.Mode__c = 'API Call In';
                insert lcti;
            }
            else{
*/
                lcti = [select sip__c, from__c, to__c, contact__c, case__c, mode__c, call_line__c , agent__c
                        from Log_CTI_Valdo__c 
                        where id=:ids];    
  //          }
            
            if(lcti.SIP__c!=null && lcti.Agent__c==null){
                List<User> listuser = [select id from user where sip__c=:lcti.SIP__c];
                if(listuser.size()>0) lcti.Agent__c = listuser[0].id;
            }
            
            if(lcti.Mode__c=='API Call In'){
                listcontact = [select id, name, phone, homephone, mobilephone, otherphone, assistantphone from contact where Entity__c = 'ALI' and (phone =:lcti.from__c OR 
                               homephone =:lcti.from__c OR mobilephone =:lcti.from__c OR otherphone =:lcti.from__c OR 
                               Mobile_F__c =: lcti.From__c ) limit 2];

//                listcontact = [select id, name, phone, homephone, mobilephone, otherphone, assistantphone from contact where Entity__c = 'ALI' and (phone =:lcti.from__c OR 
//                               homephone =:lcti.from__c OR mobilephone =:lcti.from__c OR otherphone =:lcti.from__c OR assistantphone =:lcti.from__c OR 
//                               Mobile_F__c =: lcti.From__c OR other_phone__c includes (:lcti.From__c) ) limit 10];
                               
                if(listcontact.size()==1){
                    lcti.Contact__c = listcontact[0].id; strval = listcontact[0].id; urlval = '/'+listcontact[0].id; contact_name = listcontact[0].name; 
                }
                else{
                    strval = lcti.From__c;
                    contact_name = lcti.From__c;
                    urlval = '/_ui/search/ui/UnifiedSearchResults?str=';
                    urlval = urlval+lcti.From__c;
                }    
                
            }
            else If(lcti.Mode__c=='API Call Out' && lcti.call_line__c!=null){
                strval = lcti.call_line__c;
                urlval = '/'+lcti.call_line__c;
            }
            update lcti;
            system.debug('*urlval*'+urlval);
        }
    }
}