force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Activity_Result__c.field-meta.xml
<CustomField>
    <fullName>Activity_Result__c</fullName>
    <label>Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Sudah Pay By System</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Cancel By System</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Inforced</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <formula>Call_List__r.Campaign_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Date_Reschedule__c.field-meta.xml
<CustomField>
    <fullName>Date_Reschedule__c</fullName>
    <label>Date Reschedule</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Reschedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Reschedule_Date__c</fullName>
    <description>Date/time on which we got reminded of contacting customer</description>
    <label>Reschedule Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CallLineWithdrawalReschedule.cls
global class CallLineWithdrawalReschedule implements Schedulable {
    global void execute(SchedulableContext sc) {
        Date today = Date.today();

        List<Call_Line__c> callLinesToUpdate = [
            SELECT Id, Reschedule_Date__c
            FROM Call_Line__c
            WHERE Activity_Result__c = 'F'
            AND Date_Reschedule__c = :today
            AND campaign_type__c = 'Collection-Withdrawal'
        ];
        system.debug('callLinesToUpdate ' + callLinesToUpdate.size());
        for (Call_Line__c cl : callLinesToUpdate) {
            //cl.Reschedule_Date__c = CallLineDateHelper.getNextWorkingDay(today);
            cl.Date_Reschedule__c = CallLineDateHelper.getNextWorkingDay(today);
            system.debug('cl.Reschedule_Date__c ' + cl.Reschedule_Date__c);
        }

        if (!callLinesToUpdate.isEmpty()) {
            system.debug('update call line Booking Call');
            update callLinesToUpdate;
        }
    }

}