force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Activity_Result__c.field-meta.xml
<CustomField>
    <fullName>Activity_Result__c</fullName>
    <label>Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Sudah Pay By System</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Cancel By System</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Inforced</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No outbound agent has been configured yet</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Outbound Agent</value>
        </filterItems>
        <filterItems>
            <field>$Source.Entity__c</field>
            <operation>equals</operation>
            <valueField>User.Entity__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.Agent__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Premium FU</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Survey - I Buy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <label>Reason Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity_Result__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFI - Wrong Number</fullName>
            </value>
            <value>
                <fullName>Agent Personal Closing (Tdk Pernah Setuju)</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
            <value>
                <fullName>Agree - Agree switch to Credit Card</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Redemption</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Withdrawal</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via Autodebet</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via SO or Walk In</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Transfer</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Virtual Account</fullName>
            </value>
            <value>
                <fullName>Agree - Agree Top Up Lumpsum</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to reinstate</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Melengkapi Kekurangan Dokumen</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Menunggu Proses Claim</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi data polis</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi Data Rekening</fullName>
            </value>
            <value>
                <fullName>Agree - Menerima Penjelasan dari Agen</fullName>
            </value>
            <value>
                <fullName>Agree - Mengisi dan Menandatangani SPAJ</fullName>
            </value>
            <value>
                <fullName>Agree - Others</fullName>
            </value>
            <value>
                <fullName>Agree - Quisioner By Phone</fullName>
            </value>
            <value>
                <fullName>Agree - Sudah terima Buku polis</fullName>
            </value>
            <value>
                <fullName>Agree Surat Keluhan</fullName>
            </value>
            <value>
                <fullName>Agree - Tahapan</fullName>
            </value>
            <value>
                <fullName>Agree - Transferred to Other account</fullName>
            </value>
            <value>
                <fullName>Agree - Update Address</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data All</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data more than 1 item</fullName>
            </value>
            <value>
                <fullName>Agree - Update Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CallLineAssesmentServiceWecall.cls
public class CallLineAssesmentServiceWecall {

    //@future(callout = true)
    public static void requestWecall(String clid) {
        
        System.debug('CALL LINE WELCOME CALL ASSESSMENT SERVICE');
        
        long startLongTime = system.now().getTime();
        String message = '', statusCode;
        Call_Line__c cl = BaseCoreServiceController.generateCallLine(clid);
        EIPJson addWecallAssmt = new EIPJson();
        
        User user = BaseCoreServiceController.generateUser(cl.Agent__c);
        
        try {
            String sep = '\u001F';
            String description = validateResultCall(cl) + sep + cl.LastModifiedDate.toString() + sep + cl.Owner.Name + sep + cl.Notes__c;
        
            Map<String, String> properties = new Map<String, String>();
            properties.put(EIPConstant.PARAM_MSG_POLICY, cl.Policy_No__c);
            properties.put(EIPConstant.PARAM_ASSMT_SECTION, 'OTH');
            properties.put(EIPConstant.PARAM_ASSESSOR_DTTM, cl.LastModifiedDate.format('yyyyMMddHHmmss', 'Asia/Jakarta'));
            properties.put(EIPConstant.PARAM_LAST_UPD_DTTM, cl.LastModifiedDate.format('yyyyMMddHHmmss', 'Asia/Jakarta'));
            properties.put(EIPConstant.PARAM_ASSMT_DESC, description);
            properties.put(EIPConstant.PARAM_CASE_TYPE, cl.Case_Type__c);
            properties.put(EIPConstant.PARAM_ASSESSOR, user.ID_User_RLS__c);
            system.debug('properties: '+properties);
            addWecallAssmt = EIPConnector.insertAssessmentMaintenance(EIPConstant.OPERATION_INSERT_ASSESMENT, EIPConstant.ENTITY_AMFS, EIPConstant.APP_RLS, properties);
            system.debug('requestAssmt: '+addWecallAssmt);
            
            statusCode = addWecallAssmt.Body.Status;
            String errorMessage = 'Failed to insert assessment, please contact Admin';
            if (statusCode != null && statusCode == '0') message = String.isBlank(addWecallAssmt.Body.exceptionObj.message) || addWecallAssmt.Body.exceptionObj.message == '' ? errorMessage : addWecallAssmt.Body.exceptionObj.message;
            
        } catch (Exception e) {
            System.debug('Assessment Welcome Call Error: '+e.getMessage());
        }
        
        Map<String, String> logProp = new Map<String, String>();
        logProp.put('ObjectId', cl.Id);
        logProp.put('Message', message);
        logProp.put('Report', 'Report Assesment WeCall');
        logProp.put('CaseType', cl.Case_Type__c);
        logProp.put('Request', EIPConnector.getRequestPrettyPrint());
        logProp.put('Response', addWecallAssmt.toStringJson());
        BaseCoreServiceController.insertLog(logProp, startLongTime);
    }
    
    public static String validateResultCall(Call_Line__c cl) {
        String call = cl.Activity_Result__c.trim().toLowerCase();
        String reason = cl.Verification__c.trim().toLowerCase();
        Map<String, Welcome_Call_Result__c> weCallResult = Welcome_Call_Result__c.getAll();
        Welcome_Call_Result__c matched = null;
        
        for (Welcome_Call_Result__c result : weCallResult.values()) {
            if (result.Call_Status__c == null || result.Reason_Status__c == null) continue;
            
            for (String res : result.Reason_Status__c.split(',')) {
                if (res == null) continue;
                if (res.trim().toLowerCase() == reason) {
                    matched = result;
                    break;
                }
            }
            if (matched != null) break;
        }
        
        system.debug('matched: '+matched.Result_Call__c);
        return matched.Result_Call__c;
    }
}