force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>No outbound agent has been configured yet</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Outbound Agent</value>
        </filterItems>
        <filterItems>
            <field>$Source.Entity__c</field>
            <operation>equals</operation>
            <valueField>User.Entity__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.Agent__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Call_Status_Config__c</fullName>
    <label>Call Status Config</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Sudah Pay By System</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Cancel By System</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Inforced</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
            <value>
                <fullName>Not eligible contact</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Call_List__r.Campaign_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Is_Expired__c.field-meta.xml
<CustomField>
    <fullName>Is_Expired__c</fullName>
    <formula>IF(TEXT(Entity__c) == &apos;ALI&apos;,IF(Expired_Date__c &lt; today(), true, false),
IF(Call_List__r.RecordType.Name==&apos;Collection AMFS&apos;,IF(Expired_Date__c &lt; today() || Call_List__r.IsExpired__c==true,true,false),IF(Expired_Date__c &lt;= today(), true, false)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Last_Call__c.field-meta.xml
<CustomField>
    <fullName>Last_Call__c</fullName>
    <description>ALI</description>
    <inlineHelpText>ALI</inlineHelpText>
    <label>Last Call</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Offering__c.field-meta.xml
<CustomField>
    <fullName>Offering__c</fullName>
    <description>ALI</description>
    <formula>IF ( Offering2__c == &apos;&apos;, 
IF (ISBLANK(Old_Result__c), &apos;New&apos;,&apos;Old&apos;)
,Offering2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>ALI</inlineHelpText>
    <label>Offering</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Parent_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Parent_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines (Parent Campaign)</relationshipLabel>
    <relationshipName>Call_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Reason_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Reason_Status_Config__c</fullName>
    <label>Reason Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Status_Config__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFI - Wrong Number</fullName>
            </value>
            <value>
                <fullName>Agent Personal Closing (Tdk Pernah Setuju)</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
            <value>
                <fullName>Agree - Agree switch to Credit Card</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Redemption</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Withdrawal</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via Autodebet</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via SO or Walk In</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Transfer</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Virtual Account</fullName>
            </value>
            <value>
                <fullName>Agree - Agree Top Up Lumpsum</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to reinstate</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Melengkapi Kekurangan Dokumen</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Menunggu Proses Claim</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi data polis</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi Data Rekening</fullName>
            </value>
            <value>
                <fullName>Agree - Menerima Penjelasan dari Agen</fullName>
            </value>
            <value>
                <fullName>Agree - Mengisi dan Menandatangani SPAJ</fullName>
            </value>
            <value>
                <fullName>Agree - Others</fullName>
            </value>
            <value>
                <fullName>Agree - Quisioner By Phone</fullName>
            </value>
            <value>
                <fullName>Agree - Sudah terima Buku polis</fullName>
            </value>
            <value>
                <fullName>Agree Surat Keluhan</fullName>
            </value>
            <value>
                <fullName>Agree - Tahapan</fullName>
            </value>
            <value>
                <fullName>Agree - Transferred to Other account</fullName>
            </value>
            <value>
                <fullName>Agree - Update Address</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data All</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data more than 1 item</fullName>
            </value>
            <value>
                <fullName>Agree - Update Document</fullName>
            </value>
            <value>
                <fullName>No Pickup/ Mailbox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Status_Polis__c.field-meta.xml
<CustomField>
    <fullName>Status_Polis__c</fullName>
    <label>Status Polis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/IsExpired__c.field-meta.xml
<CustomField>
    <fullName>IsExpired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_List__c/recordTypes/ActivityAGI.recordType-meta.xml
<RecordType>
    <fullName>ActivityAGI</fullName>
    <active>true</active>
    <label>ActivityAGI</label>
</RecordType>

force-app/main/default/objects/Call_List__c/recordTypes/ActivityALI.recordType-meta.xml
<RecordType>
    <fullName>ActivityALI</fullName>
    <active>true</active>
    <label>ActivityALI</label>
</RecordType>

force-app/main/default/classes/Call_Line.cls
public class Call_Line {
    Public String idparam {get;set;}
    public integer index {get;set;}
    public integer blockSize {get;set;}
    public integer totalRecs {get;set;}
    public integer totalAllRecs {get;set;}
    public Boolean fetchCalled;
    Public String filcampname {get;set;}
    Public String filcallstatus {get;set;}
    Public Profile pro {get;set;}
    PUBLIC String SOQL {get;set;}
    Public String offering {get;set;}
    Public String stapol {get;set;}
    Public String entityUser {get;set;}
    public String sortDir {
        get  { if (sortDir == null) {  sortDir = 'asc'; } return sortDir;  }
        set;
    }
    public void toggleSort() {
        sortDir = sortDir.equals('asc') ? 'desc' : 'asc';
        fetch();
    }
    public String sortField {
        get  { if (sortField == null) {sortField = 'Createddate'; } return sortField;  }
        set;
    }
    public Call_Line(){
        index = 0;
        blockSize = 10;
        idparam = '';
        stapol = '';
        Offering = 'All';
        filcallstatus='No';
        pro = [select name from Profile where id=:UserInfo.getProfileId()];
        entityUser = [Select Entity__c From User Where Id = :UserInfo.getUserId()].Entity__c;	
	}
    
    public void fetch(){
        DescribeSObjectResult describeResultdp = Call_Line__c.getSObjectType().getDescribe();
        List<String> dpFieldList = new List<String>(describeResultdp.fields.getMap().keySet());
        String dpFields = String.join(dpFieldList, ',');
        String qr = 'SELECT count(id) cid FROM Call_Line__c where Parent_Campaign__c!=null and Is_Expired__c = false ';
        soql = 'SELECT '+dpFields+' FROM Call_Line__c where Parent_Campaign__c!=null and Is_Expired__c = false ';
        if(filcampname!=null && filcampname!='') soql = soql + ' and Call_List__c='+'\''+filcampname+'\''+' ';
        if(filcallstatus=='Yes' && filcallstatus!=NULL) soql = soql + ' and Call_Status_Config__c != NULL ' ;
        if(filcallstatus=='No' && filcallstatus!=NULL) soql = soql + ' and Call_Status_Config__c = NULL ';
        if(offering!='All' && offering!= NULL )soql = soql + ' and Offering__c = '+'\''+offering+'\''+' ';
        if(filcallstatus=='Rescheduled'  && filcallstatus!=NULL) soql = soql + ' and Call_Status_Config__c = '+'\''+filcallstatus+'\''+' ';
        if(filcallstatus== 'No Pickup/ Mailbox' && filcallstatus!=NULL ) soql = soql + ' and Reason_Status_Config__c = '+'\''+filcallstatus+'\''+' ';
        if(stapol!='' && stapol!=null) soql = soql + ' and Status_Polis__c = '+'\''+stapol+'\''+' ';
        if(pro.Name=='System Administrator'){
        
        }
        else{
            qr = qr + ' and agent__c ='+'\''+UserInfo.getUserId()+'\''+' ';
            soql = soql+' and agent__c ='+'\''+UserInfo.getUserId()+'\''+' ';
        }
        AggregateResult ar = Database.query(qr);
        totalAllRecs = Integer.valueOf(ar.get('cid'));
        soql = soql + ' order by '+SortField+' '+sortDir;
        soql = soql + ' limit 40000 ';
        //List<Call_Line__c> listcl = Database.query(soql);
        //totalrecs = listcl.size();
    }
    
    public List<Call_Line__c> getListCall(){
        List<Call_Line__c> listcl = new List<Call_Line__c>();
        fetch();
        //String dpQuery = soql + ' LIMIT ' + blockSize + ' OFFSET ' + index;
        List<Call_Line__c> listcl2 = new List<Call_Line__c>();
        if(test.isRunningTest()==false){
            listcl2 = Database.query(soql);
            totalrecs = listcl2.size();
            Integer endblock = blockSize + index;
            if(endblock>=totalRecs) endblock = totalRecs;
            for(Integer i = index ; i < endblock ; i++){
                listcl.add(listcl2.get(i));
            }
        }
        else{
            listcl2 = Database.query('select id, name from call_line__c limit 100');
            listcl = listcl2;
        }
        //system.debug('*query*'+dpquery);
        //listcl = Database.query(dpQuery);
        return listcl;
    }
    
    public void UpdateCallLine(){
        if(idparam!=null){
            try{
                Call_Line__c cl = [select id, name, last_call__c from call_line__c where id=:idparam];
                cl.Last_Call__c = dateTime.now();
                update cl;    
            }
            catch(exception e){
                system.debug(LoggingLevel.DEBUG,'*error*'+e);
            }
            idparam = '';
        }
    }
    
     public List<SelectOption> getCampaignlist(){
         List<SelectOption> options = new List<SelectOption>();

         String query;
         String dpQuery = 'SELECT Call_List__c FROM Call_Line__c where (Parent_Campaign__c!=null OR Campaign_Name__c !=null) and Is_Expired__c = false ';
         if(pro.Name=='System Administrator'){
        
         }
         else{
             dpQuery = dpQuery+' and agent__c ='+'\''+UserInfo.getUserId()+'\''+' ';
         }
         
         if (entityUser == 'AGI') query = 'SELECT id, Campaign_Name__c  from Call_List__c where recordtype.name = '+'\''+'ActivityAGI'+'\''+' and IsExpired__c = false and id in ('+dpquery+')';
         if (entityUser == 'ALI') query = 'SELECT id, Campaign_Name__c  from Call_List__c where recordtype.name = '+'\''+'ActivityALI'+'\''+' and IsExpired__c = false and id in ('+dpquery+')';
         
         //query = 'SELECT id, Campaign_Name__c  from Call_List__c where recordtype.name = '+'\''+'ActivityALI'+'\''+' and IsExpired__c = false and id in ('+dpquery+')';
         options.add(new SelectOption('','--All--'));
         for(Call_List__c ar: Database.query(query)){
             options.add(new SelectOption(AR.id, ar.Campaign_Name__c));
         }
         return options;   
     }
    
    public List<SelectOption> getCallStatus(){
        List<SelectOption> options = new List<SelectOption>();
        String opsi = label.cl_callstatus;
        List<String> listopsi = new List<String>();
        if(opsi!=null && opsi!='') listopsi = opsi.split(';');
        if(listopsi.size()>0){
            for(String s:listopsi){
                options.add(new SelectOption(s,s));
            }
        }
        return options;   
     }
    
    public List<SelectOption> getBlock_Size(){
        List<SelectOption> options = new List<SelectOption>();
        String opsi = label.CL_BlockSize;
        List<String> listopsi = new List<String>();
        if(opsi!=null && opsi!='') listopsi = opsi.split(';');
        if(listopsi.size()>0){
            for(String s:listopsi){
                options.add(new SelectOption(s,s));
            }
        }
		return options;   
     }
    
    public List<SelectOption> getOffering_pick(){
        List<SelectOption> options = new List<SelectOption>();
        String opsi = label.CL_Offering;
        List<String> listopsi = new List<String>();
        if(opsi!=null && opsi!='') listopsi = opsi.split(';');
        if(listopsi.size()>0){
            for(String s:listopsi){
                options.add(new SelectOption(s,s));
            }
        }
        return options;   
     }
    
    public List<SelectOption> getStatus_Polis(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','None'));
        String opsi = label.CL_StatusPolis;
        List<String> listopsi = new List<String>();
        if(opsi!=null && opsi!='') listopsi = opsi.split(';');
        if(listopsi.size()>0){
            for(String s:listopsi){
                options.add(new SelectOption(s,s));
            }
        }
        return options;   
     }
    
    public void beginning()
    {
        index = 0;
    }
    
    public void previous()
    {
        index = index - blockSize;
    }
    
    public void next()
    {
        index = index + blockSize;
        system.debug(LoggingLevel.DEBUG, '*index*'+index);
    }
    
    public void end()
    {
        index = totalrecs - math.mod(totalRecs,blockSize);
    }
    
    public boolean getprev()
    {
        if(index == 0)
        return true;
        else
        return false;
    }
    
     public boolean getnxt()
    {
        if((index + blockSize) >= totalRecs)
        return true;
        else
        return false;
    }
}