force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Call_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Call_Remarks__c</fullName>
    <label>Remarks</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Collection_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Collection_Call_Date__c</fullName>
    <label>Collection Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Reason_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Reason_Status_Config__c</fullName>
    <label>Reason Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Status_Config__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFI - Wrong Number</fullName>
            </value>
            <value>
                <fullName>Agent Personal Closing (Tdk Pernah Setuju)</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
            <value>
                <fullName>Agree - Agree switch to Credit Card</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Redemption</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Withdrawal</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via Autodebet</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via SO or Walk In</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Transfer</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Virtual Account</fullName>
            </value>
            <value>
                <fullName>Agree - Agree Top Up Lumpsum</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to reinstate</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Melengkapi Kekurangan Dokumen</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Menunggu Proses Claim</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi data polis</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi Data Rekening</fullName>
            </value>
            <value>
                <fullName>Agree - Menerima Penjelasan dari Agen</fullName>
            </value>
            <value>
                <fullName>Agree - Mengisi dan Menandatangani SPAJ</fullName>
            </value>
            <value>
                <fullName>Agree - Others</fullName>
            </value>
            <value>
                <fullName>Agree - Quisioner By Phone</fullName>
            </value>
            <value>
                <fullName>Agree - Sudah terima Buku polis</fullName>
            </value>
            <value>
                <fullName>Agree Surat Keluhan</fullName>
            </value>
            <value>
                <fullName>Agree - Tahapan</fullName>
            </value>
            <value>
                <fullName>Agree - Transferred to Other account</fullName>
            </value>
            <value>
                <fullName>Agree - Update Address</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data All</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data more than 1 item</fullName>
            </value>
            <value>
                <fullName>Agree - Update Document</fullName>
            </value>
            <value>
                <fullName>Tidak Berkenan Dihubungi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Status_has_call__c.field-meta.xml
<CustomField>
    <fullName>Status_has_call__c</fullName>
    <label>Status has call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/mdmid_owner__c.field-meta.xml
<CustomField>
    <fullName>mdmid_owner__c</fullName>
    <label>MDM ID Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CallLineRetentionControllerTest.cls
@isTest
public class CallLineRetentionControllerTest {
    
    @testSetup
    static void initContact() {
        Contact testContact = new Contact(mdmid_owner__c = '77416108', Policy_No__c = '201-5123421', LastName = 'Sholihin');
        insert testContact;
    }
    
    @isTest
    public static void updloadFileFailedTest(){
        CallLineRetentionController controller = new CallLineRetentionController();
        Test.startTest();
        controller.fileContent = Blob.valueOf('201-5123421\n201-5012131');
        controller.fileLines = controller.fileContent.toString().split('\n');
        controller.fileName = 'test.txt';
        controller.uploadFile();
        Test.stopTest();
        System.assertEquals('File is blank or not csv type', ApexPages.getMessages()[0].getSummary());
    }
    
    @isTest
    public static void uploadRecordTakeoutTest(){
        
        CallLineRetentionController controller = new CallLineRetentionController();
        
        controller.contact = [SELECT Id FROM Contact LIMIT 1];
        try {
            String header = 'Policy_No__c, Remark_Description__c, Retention_Status__c\n';
                        
            Test.startTest();
            controller.fileContent = Blob.valueOf(header+ '201-5123421, Req by user, Takeout\n');
			controller.fileName = 'test.csv';
            controller.uploadFile();
            controller.changeRetentionStatus(controller.updatedClr, controller.policy);
            controller.changeCallLine(controller.updatedClr, controller.policy);
            controller.parseCsvRecords(controller.fileLines, controller.contactMap, controller.listClr);
            ApexPages.currentPage().getParameters().put('upload', 'success');
            Test.stopTest();
                        
        } catch (Exception e) {
            System.assertEquals(e.getMessage(), 'An error has occured: '+e);
        }
        
    }

	@isTest
    public static void uploadRecordReleaseTest(){
        
        CallLineRetentionController controller = new CallLineRetentionController();
        
        controller.contact = [SELECT Id FROM Contact LIMIT 1];
        Call_Line_Retention__c clr = new Call_Line_Retention__c();
        try {
            String header = 'Policy_No__c, Remark_Description__c, Retention_Status__c\n';
                        
            Test.startTest();
            controller.fileContent = Blob.valueOf(header+ '201-5123421, Req by admin, Release');
            controller.fileName = 'test.csv';
            controller.uploadFile();
            controller.changeRetentionStatus(controller.updatedClr, controller.policy);
            controller.changeCallLine(controller.updatedClr, controller.policy);
            controller.parseCsvRecords(controller.fileLines, controller.contactMap, controller.listClr);
            ApexPages.currentPage().getParameters().put('upload', 'success');
            
            List<String> records = controller.fileContent.toString().split('/n');
            system.debug('records: '+records);
            List<Call_Line_Retention__c> retentions = new List<Call_Line_Retention__c>();
            for (Integer i = 1; i < records.size(); i++) {
                clr.Contact__c = controller.contact.Id;
                clr.Remark_Description__c = records[1];
                clr.Retention_Status__c = records[2];
                retentions.add(clr);
            }
            insert retentions;
            Test.stopTest();
            
        } catch (Exception e) {
            System.assertEquals(e.getMessage(), 'An error has occured: '+e);
        }
        
    }
    
    @isTest
    public static void policyNotRegisteredTest() {
       
        CallLineRetentionController controller = new CallLineRetentionController();
                
        controller.contact = [SELECT Id, Policy_No__c FROM Contact LIMIT 1];

		String header = 'Policy_No__c, Remark_Description__c, Retention_Status__c\n';
        Test.startTest();
        controller.fileContent = Blob.valueOf(header+ '201-5123420, Req by user, Release\n');
        controller.fileName = 'test.csv';
        controller.uploadFile();
        controller.parseCsvRecords(controller.fileLines, controller.contactMap, controller.listClr);
        Test.stopTest();
    }
    
    @isTest
    public static void remarksBlankTest() {
        CallLineRetentionController controller = new CallLineRetentionController();
                
        controller.contact = [SELECT Id, Policy_No__c FROM Contact LIMIT 1];
        
		String header = 'Policy_No__c, Remark_Description__c, Retention_Status__c\n';
        Test.startTest();
        controller.fileContent = Blob.valueOf(header+ '201-5123421,0,Release\n');
        controller.fileName = 'test.csv';
        controller.uploadFile();
        controller.parseCsvRecords(controller.fileLines, controller.contactMap, controller.listClr);
        CallLineRetentionController.InvalidPolicyNo invalidPolicy = new CallLineRetentionController.InvalidPolicyNo(controller.invalidPolicyText[0], controller.invalidPolicyStatus[0]);
        Test.stopTest();
        
        System.assertEquals(controller.invalidPolicyText[0],'201-5123421');
        System.assertEquals(controller.invalidPolicyStatus[0],'E2');
    }
    
    @isTest
    public static void statusInvalidTest() {
        CallLineRetentionController controller = new CallLineRetentionController();
                
        controller.contact = [SELECT Id, Policy_No__c FROM Contact LIMIT 1];
        
		String header = 'Policy_No__c, Remark_Description__c, Retention_Status__c\n';
        Test.startTest();
        controller.fileContent = Blob.valueOf(header+ '201-5123421, test remarks, Completed\n');
        controller.fileName = 'test.csv';
        controller.uploadFile();
        controller.parseCsvRecords(controller.fileLines, controller.contactMap, controller.listClr);
        CallLineRetentionController.InvalidPolicyNo invalidPolicy = new CallLineRetentionController.InvalidPolicyNo(controller.invalidPolicyText[0], controller.invalidPolicyStatus[0]);
        Test.stopTest();
        
        System.assertEquals(controller.invalidPolicyText[0],'201-5123421');
        System.assertEquals(controller.invalidPolicyStatus[0],'E3');
    }
    
    @isTest
    public static void recordNullTest() {
        CallLineRetentionController controller = new CallLineRetentionController();
                
        controller.contact = [SELECT Id, Policy_No__c FROM Contact LIMIT 1];
        
		String header = 'Policy_No__c, Remark_Description__c, Retention_Status__c\n';
        Test.startTest();
        controller.fileContent = Blob.valueOf(header+ ',test remarks, Takeout\n, , ');
        controller.fileName = 'test.csv';
        controller.uploadFile();
        controller.parseCsvRecords(controller.fileLines, controller.contactMap, controller.listClr);
        CallLineRetentionController.InvalidPolicyNo invalidPolicy = new CallLineRetentionController.InvalidPolicyNo(controller.invalidPolicyText[0], controller.invalidPolicyStatus[0]);
        Test.stopTest();
        
        System.assertEquals(controller.invalidPolicyStatus[0],'E1');
    }
    
    @isTest
    public static void changeCallLineTest() {
        
        CallLineRetentionController controller = new CallLineRetentionController();
		controller.contact = [SELECT Id, Policy_No__c FROM Contact LIMIT 1];
		
        List<Call_Line_Retention__c> clrList = new List<Call_Line_Retention__c>();
		clrList.add(new Call_Line_Retention__c(
        	Contact__c = controller.contact.Id,
            Remark_Description__c = 'Req by admin',
            Retention_Status__c = 'Takeout'
        ));
        List<String> policy = new List<String>();
        policy.add(clrList[0].Policy_No__c);
		insert clrList;
        
        Test.startTest();
        controller.mapClr = new Map<String, Call_Line_Retention__c>();
		controller.changeCallLine(clrList, policy);
        
        for (Call_Line__c cl : controller.listCl) {
            System.assertEquals(controller.mapClr.containsKey(cl.Contact__c), true, 'call line retention is updated');
            System.assertEquals('Takeout', cl.Status_has_call__c, 'call status is not changed');
            System.assertEquals('Tidak Berkenan Dihubungi', cl.Reason_Status_Config__c, 'reason status is not changed');
            System.assertEquals(Datetime.now(), cl.Collection_Call_Date__c, 'date time is different');
            System.assertEquals(clrList[0].Remark_Description__c, cl.Call_Remarks__c, 'remark is different');
        }
        Test.stopTest();
    }
}