force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Conservation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Survey Feedback</fullName>
            </value>
            <value>
                <fullName>Complaint Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Call_List__c.field-meta.xml
<CustomField>
    <fullName>Call_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Call_List__c</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <formula>Call_List__r.Campaign_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Case_Type_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Type_Config__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity_Config__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Survey - I Buy</fullName>
            </value>
            <value>
                <fullName>Survey - I Ask</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Expired_Date__c</fullName>
    <formula>IF(ISPICKVAL(Case_Type__c, &apos;TelUW&apos;), DATEVALUE(WelcomeCall_Schedule_Date__c) + 30, if ( and(RecordType.Name == &apos;TeleService&apos;, NOT(ISBLANK(Due_Date__c)) ),  Due_Date__c , Call_List__r.Expired_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expired Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/Call_List__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <displayFormat>Gen{YY}{MM}{DD}-{000000}</displayFormat>
        <label>Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_List__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Conservation</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
            </value>
            <value>
                <fullName>Survey Feedback</fullName>
            </value>
            <value>
                <fullName>Complaint Case</fullName>
            </value>
            <value>
                <fullName>Customer Segmentation</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Teleservices</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Case_Type_Config__c.field-meta.xml
<CustomField>
    <fullName>Case_Type_Config__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Activity__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Premium Pending</fullName>
            </value>
            <value>
                <fullName>Claim Pending</fullName>
            </value>
            <value>
                <fullName>Welcome Call</fullName>
            </value>
            <value>
                <fullName>Retain Redemption</fullName>
            </value>
            <value>
                <fullName>Retain Withdrawal</fullName>
            </value>
            <value>
                <fullName>Policy Elapse</fullName>
            </value>
            <value>
                <fullName>Debt Failure</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Survey of Claim Service</fullName>
            </value>
            <value>
                <fullName>Survey of ERA/Towing Service</fullName>
            </value>
            <value>
                <fullName>Pending Document POS</fullName>
            </value>
            <value>
                <fullName>Request ERA/Towing</fullName>
            </value>
            <value>
                <fullName>Complaint Follow Up</fullName>
            </value>
            <value>
                <fullName>Update Data</fullName>
            </value>
            <value>
                <fullName>SMS Pull Confirmation</fullName>
            </value>
            <value>
                <fullName>Premium Holiday Passive</fullName>
            </value>
            <value>
                <fullName>Premium Reminder</fullName>
            </value>
            <value>
                <fullName>Grace Period</fullName>
            </value>
            <value>
                <fullName>Welcome Call (NBUW)</fullName>
            </value>
            <value>
                <fullName>Teleclaim</fullName>
            </value>
            <value>
                <fullName>Retain Tahapan</fullName>
            </value>
            <value>
                <fullName>Request Quick Response</fullName>
            </value>
            <value>
                <fullName>Big RTU Complaint</fullName>
            </value>
            <value>
                <fullName>No Claim Bonus</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Birthday greeting</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Collection Task</fullName>
            </value>
            <value>
                <fullName>Reinstate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Expired_Date__c</fullName>
    <description>Expired Date</description>
    <label>Expired Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_List__c/fields/WelcomeCall_Fg_Automatic__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Fg_Automatic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fg Automatic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium__c</fullName>
    <label>Total Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Currency__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Currency__c</fullName>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Issued_Date__c</fullName>
    <label>Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WelcomeCall_Product_Code_Plan__c.field-meta.xml
<CustomField>
    <fullName>WelcomeCall_Product_Code_Plan__c</fullName>
    <label>Product Code Plan</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CampaignWelcomeCall_Test.cls
@isTest(SeeAllData=true)
public class CampaignWelcomeCall_Test {
    static ID rtAgentGroup = Schema.SObjectType.Agent_Group__c.getRecordTypeInfosByName().get('Agent Group').getRecordTypeId();
    static ID wcRtId = Schema.SObjectType.Call_Line__c.getRecordTypeInfosByName().get('Welcome Call').getRecordTypeId();
    static testmethod void testScheduledJob() {
        system.debug('MASUK TEST');
        Test.startTest();
        List<Contact>conlist = new List<Contact>();
        Contact con = new Contact();
        con.LastName = 'Test Name1';
        con.Total_Premium__c =  10000000;
        con.policy_no__c = '513-12345';
        con.MobilePhone = '0813987654';
        con.HomePhone = '';
        con.Phone = '';
        con.OtherPhone = '';
        con.Entity__c = 'AMFS';
        con.WelcomeCall_Currency__c = 'RP';
        con.WelcomeCall_Product_Code_Plan__c = 'MSW';
        con.WelcomeCall_Payment_Type__c = 'A';
        con.WelcomeCall_Issued_Date__c = date.today()-1;
        con.policyApp__c = 'RLS';
        conlist.Add(con);
        insert conlist;
        system.debug('MASUK TEST Insert');
        
        String formatName = 'WelcomeCall';
        String monthNow = Datetime.now().format('yyMM');
        String autoManual = 'Automatic';
        formatName = formatName + monthNow + autoManual;
        Date now = Date.today();
        Date next_month = now.addMonths(1);
        Date expiry_date = Date.valueOf(next_month.year() + '-' + next_month.month() + '-' + System.Label.Welcome_Call_Expired_Days);
            // System.debug(formatName);
        RecordType recId = getRecordTypeId('Confirmation AMFS', 'Call_List__c');
        
        Call_List__c calist = new Call_List__c(Activity__c = 'Confirmation',
                                                       Campaign_Name__c = formatName, 
                                                       Case_Type_Config__c = 'Welcome Call',
                                                       Expired_Date__c = expiry_date,
                                                       Entity__c = 'AMFS',
                                                       RecordTypeId = recId.Id,
                                                       WelcomeCall_Fg_Automatic__c = true);
                
        insert calist;
        
        
        List<Call_line__C> callLineLs = new List<Call_line__C>();
        String caseType = '';
        String caseTypeConfig = '';
        String activity = '';
        Call_List__c[] calis = [select id, name, case_type__c,Case_Type_Config__c, Activity__c from call_list__c where Id = :calist.id];
        for(Call_List__c cal: calis){
            caseType = cal.case_type__c;
            caseTypeConfig = cal.Case_Type_Config__c;
            activity = cal.Activity__c;
        }
        
        Call_Line__c calin = new Call_Line__c(RecordTypeId = wcRtId,
                                                          Contact__c = con.Id,
                                                          Call_List__c =calist.id,
                                                          WelcomeCall_Call_Line_Status__c = 'Open',
                                                          Case_Type__c = caseType,
                                                          Case_Type_Config__c = caseTypeConfig,
                                                          Contacted_Number__c = con.MobilePhone,
                                                          Phone__c = con.Phone,
                                                          Home_Phone__c = con.HomePhone,
                                                          Other_Phone__c = con.OtherPhone,
                                                          Activity__c = activity,
                                                          Policy_no__c = con.policy_no__c,
                                                          Entity__c = con.Entity__c);
        callLineLs.add(calin);
        insert callLineLs;
       
        
        CampaignWelcomeCall testWelcomCall = new CampaignWelcomeCall();
		testWelcomCall.execute(null);
        testWelcomCall.roundRobinDist(true);

        Test.stopTest();
    }
    static RecordType getRecordTypeId(string recordTypeName, string sObjectName)
    {
        RecordType result;
        list <RecordType> recordTypeList = [
          SELECT Id, Name, SObjectType 
          FROM RecordType 
          WHERE SObjectType = :sObjectName ORDER BY Name
        ];
        for(RecordType recordType: recordTypeList)
        {
            if(recordType.Name.equalsIgnoreCase(recordTypeName))
            {
                result = recordType; 
                break;
            }
        }
        
        return result;
    }
	
}