force-app/main/default/objects/AppLog__c/AppLog__c.object-meta.xml
<CustomObject>
    <label>AppLog</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>AppLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppLog__c/fields/end_date__c.field-meta.xml
<CustomField>
    <fullName>end_date__c</fullName>
    <label>end date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/EndLongTime__c.field-meta.xml
<CustomField>
    <fullName>EndLongTime__c</fullName>
    <label>EndLongTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <label>Contact SFID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/start_date__c.field-meta.xml
<CustomField>
    <fullName>start_date__c</fullName>
    <label>start date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/StartLongTime__c.field-meta.xml
<CustomField>
    <fullName>StartLongTime__c</fullName>
    <label>StartLongTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/LogCoreIntegrationController_Test.cls
@isTest
public class LogCoreIntegrationController_Test {

    @testSetup
    static void init(){
        
        Contact con = new Contact();
        con.Lastname = 'someone';
        con.Policy_No__c = '939939';
        con.Entity__c = 'AMFS';
        insert con;
        
        List<AppLog__c> logs = new List<AppLog__c>();
        for (Integer i = 0; i<100; i++){
            logs.add(new AppLog__c(
                Id__c = con.Id, 
                Policy_No__c = con.Policy_No__c, 
                Entity__c = 'AMFS', 
                Report_Name__c = 'DMTM Report',
                Status__c = 'Success',
                StartLongTime__c = system.now().getTime(),
                EndLongTime__c = system.now().getTime()
            ));
        }
        insert logs;
        
        AppLog__c logError = new AppLog__c();
        logError.Id__c = con.Id;
        logError.Policy_No__c = con.Policy_No__c; 
        logError.Entity__c = 'AMFS';
        logError.Report_Name__c = 'AMFS Collection Robot DMTM';
        logError.Status__c = 'Error';
        logError.StartLongTime__c = system.now().getTime();
        logError.EndLongTime__c = system.now().getTime();
        insert logError;
    }
    
    @isTest
    static void controllerTest(){
        LogCoreIntegrationController ctrl = new LogCoreIntegrationController();
        AppLog__c log = [SELECT Id, Name, Policy_No__c, Error_Message__c, Status__c, Report_Name__c, end_date__c, start_date__c, LastModifiedDate FROM AppLog__c WHERE Status__c = 'Error' LIMIT 1];
        
        Test.startTest();
        ctrl.logId = log.Id;
        ctrl.statusOpt = log.Status__c;
        ctrl.reportName = log.Report_Name__c;
        ctrl.startDate = log.LastModifiedDate;
        ctrl.endDate = log.LastModifiedDate.addDays(1);
        ctrl.policy = log.Policy_No__c;
        
        ctrl.entries();
        ctrl.getLogs();
        ctrl.exportLogs();
        ctrl.searchPolicy();
        ctrl.showReport();
        ctrl.updateToInvalid();
        ctrl.filterQueryLog();
        Test.stopTest();
    }
    
    @isTest
    static void paginationTest() {
        Test.startTest();
        LogCoreIntegrationController controller = new LogCoreIntegrationController();
        controller.first();
        controller.last();
        controller.next();
        controller.previous();
        System.assertEquals(25, controller.logList.getPageSize());

        System.assertEquals(1, controller.pageNumber);
        System.assertEquals(0, controller.resultSize);
        
        controller.selectSize = '50';
        controller.logList.setPageSize(50);
        System.assertEquals(Integer.valueof(controller.selectSize), controller.logList.getPageSize());
        
        controller.selectSize = '100';
        controller.logList.setPageSize(100);
        System.assertEquals(100, controller.logList.getPageSize());
        Test.stopTest();
    }
}