force-app/main/default/objects/AppLog__c/AppLog__c.object-meta.xml
<CustomObject>
    <label>AppLog</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>AppLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppLog__c/fields/Log_Call_Line__c.field-meta.xml
<CustomField>
    <fullName>Log_Call_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Line</label>
    <referenceTo>Call_Line__c</referenceTo>
    <relationshipLabel>AppLogs</relationshipLabel>
    <relationshipName>AppLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Log_Case__c.field-meta.xml
<CustomField>
    <fullName>Log_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>AppLogs</relationshipLabel>
    <relationshipName>AppLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Policy_App__c.field-meta.xml
<CustomField>
    <fullName>Policy_App__c</fullName>
    <label>Policy App</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Request_Value__c.field-meta.xml
<CustomField>
    <fullName>Request_Value__c</fullName>
    <label>Request Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RetryCallLineAssesmentRLS.cls
public class RetryCallLineAssesmentRLS {
    
    public static void retryAssesmentRLS(String logId){
        AppLog__c log = (AppLog__c) SOQL.of(AppLog__c.SObjectType)
            .with('Id, Log_Call_Line__c, Log_Case__c, Request_Value__c, Policy_App__c')
            .whereAre(SOQL.Filter.with(AppLog__c.Id).equal(logId))
            .systemMode()
            .toObject();
        
        EIPJson convertReqJson = (EIPJson) JSON.deserialize(log.Request_Value__c, EIPJson.class);
        system.debug('request value: '+convertReqJson.Body.service);
        Map<String, String> requestProp = new Map<String, String>();
        String operation = convertReqJson.Body.operation;
        EIPJson.EIP_AgSa_InsurancePolicy hasPolicy = convertReqJson.Body.Customer.hasPolicyAccount[0];
        
        if (operation == EIPConstant.OPERATION_INSERT_ASSESMENT) {
            
        } else if (operation == EIPConstant.OPERATION_CR_REGISTER) {
            
        } else if (operation == EIPConstant.OPERATION_APP_DETAIL) {
            
        } else if (operation == EIPConstant.OPERATION_NOTIF_REMARK) {
            
        }
    }
}