force-app/main/default/objects/AppLog__c/AppLog__c.object-meta.xml
<CustomObject>
    <label>AppLog</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>AppLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppLog__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <label>Contact SFID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/start_date__c.field-meta.xml
<CustomField>
    <fullName>start_date__c</fullName>
    <label>start date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/StartLongTime__c.field-meta.xml
<CustomField>
    <fullName>StartLongTime__c</fullName>
    <label>StartLongTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/Call_Line__c.object-meta.xml
<CustomObject>
    <label>Call Line</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Call Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Line__c/fields/Call_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Call_Status_Config__c</fullName>
    <label>Call Status Config</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Sudah Pay By System</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>Cancel By System</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Inforced</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Takeout</fullName>
            </value>
            <value>
                <fullName>Not eligible contact</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Entity__c</field>
            <operation>equals</operation>
            <valueField>$User.Entity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Lines</relationshipLabel>
    <relationshipName>Call_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <description>AMFS
AFI
MAGI</description>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>ALI</description>
    <inlineHelpText>ALI
Exp : CC, Saving</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Nilai_Conservation__c.field-meta.xml
<CustomField>
    <fullName>Nilai_Conservation__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nilai Conservation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Nilai_Withdrawal__c.field-meta.xml
<CustomField>
    <fullName>Nilai_Withdrawal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nilai Withdrawal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Offering_Retain__c.field-meta.xml
<CustomField>
    <fullName>Offering_Retain__c</fullName>
    <label>Offering Retain</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retain with withdrawal</fullName>
            </value>
            <value>
                <fullName>Pengurangan Withdrawal</fullName>
            </value>
            <value>
                <fullName>Delete / Change RTU</fullName>
            </value>
            <value>
                <fullName>Delete / Add Rider</fullName>
            </value>
            <value>
                <fullName>Downgrade UP</fullName>
            </value>
            <value>
                <fullName>Change Freq Payment Payment</fullName>
            </value>
            <value>
                <fullName>Change to AFI&apos;s other product</fullName>
            </value>
            <value>
                <fullName>Switch / Change Fund</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <formula>Contact__r.WelcomeCall_Effective_Date__c</formula>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Reason_Status_Config__c.field-meta.xml
<CustomField>
    <fullName>Reason_Status_Config__c</fullName>
    <label>Reason Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Status_Config__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFI - Wrong Number</fullName>
            </value>
            <value>
                <fullName>Agent Personal Closing (Tdk Pernah Setuju)</fullName>
            </value>
            <value>
                <fullName>Agree</fullName>
            </value>
            <value>
                <fullName>Agree - Agree switch to Credit Card</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Redemption</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Cancel Withdrawal</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via Autodebet</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to pay via SO or Walk In</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Transfer</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to Pay via Virtual Account</fullName>
            </value>
            <value>
                <fullName>Agree - Agree Top Up Lumpsum</fullName>
            </value>
            <value>
                <fullName>Agree - Agree to reinstate</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Melengkapi Kekurangan Dokumen</fullName>
            </value>
            <value>
                <fullName>Agree - Bersedia Menunggu Proses Claim</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi data polis</fullName>
            </value>
            <value>
                <fullName>Agree - Koreksi Data Rekening</fullName>
            </value>
            <value>
                <fullName>Agree - Menerima Penjelasan dari Agen</fullName>
            </value>
            <value>
                <fullName>Agree - Mengisi dan Menandatangani SPAJ</fullName>
            </value>
            <value>
                <fullName>Agree - Others</fullName>
            </value>
            <value>
                <fullName>Agree - Quisioner By Phone</fullName>
            </value>
            <value>
                <fullName>Agree - Sudah terima Buku polis</fullName>
            </value>
            <value>
                <fullName>Agree Surat Keluhan</fullName>
            </value>
            <value>
                <fullName>Agree - Tahapan</fullName>
            </value>
            <value>
                <fullName>Agree - Transferred to Other account</fullName>
            </value>
            <value>
                <fullName>Agree - Update Address</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data All</fullName>
            </value>
            <value>
                <fullName>Agree - Update Data more than 1 item</fullName>
            </value>
            <value>
                <fullName>Agree - Update Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Line__c/fields/Selisih__c.field-meta.xml
<CustomField>
    <fullName>Selisih__c</fullName>
    <label>Selisih</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Accident_Place__c.field-meta.xml
<CustomField>
    <fullName>Accident_Place__c</fullName>
    <label>Accident Place</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Agent_Status__c.field-meta.xml
<CustomField>
    <fullName>Agent_Status__c</fullName>
    <label>Agent Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <label>Branch Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Certificate_No__c.field-meta.xml
<CustomField>
    <fullName>Certificate_No__c</fullName>
    <label>Certificate No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_of_Accident__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Accident__c</fullName>
    <label>Date of Accident</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Policy_Effective_Date__c</fullName>
    <label>Policy Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <label>Segment Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/ConservationWithdrawal.cls
public with sharing class ConservationWithdrawal {
    
    //private final Call_Line__c cLine;
    public Call_Line__c cLine {get;set;}
    
    public String contactID {get;set;}
    public string policyNo {get; set;}
    public string entity {get; set;}
    public string policyApp {get; set;}
    public string contactName {get; set;}
    public string certificateNo {get; set;}
    public string sessionID {get; set;}
    
    public List <FundDetail> fundDetailList {get;set;}
    public integer fundDetailLastPageNo {get;set;} 
    public integer fundDetailRowPerPage {get;set;} 
    
    public integer fundHistoryLastPageNo {get;set;} 
    public integer fundHistoryRowPerPage {get;set;}
    
    public integer fundPriceHistoryLastPageNo {get;set;} 
    public integer fundPriceHistoryRowPerPage {get;set;}
    
    public Decimal n_Conservation {get;set;}
    
    public Decimal nilaiConservation {
        get;
        set {
            // when changed nilaiConservation value, recalc newPrice value
            if (value != nilaiConservation) {
                nilaiConservation = value;
                recalcNewPrice();
            }
        }
    }
    
    public Decimal nilaiWithdrawal {
        get;
        set {
            // when changed nilaiWithdrawal value, recalc newPrice value
            if (value != nilaiWithdrawal) {
                nilaiWithdrawal = value;
                recalcNewPrice();
            }
        }
    }
    
    public Decimal selisih {get;set;}
    //public String offeringRetain {get;set;}
    //public List<SelectOption> offeringRetainList {get; set;}
    
    
    //EIP FUND INFO (Update 12 April 2020)
    
    
    /* Fund Details
     * base on End to End Document
     * by Doddy 2016
     */
    public class  FundDetail{
        public string FundCode {get; set;}
        public decimal FundAllocation {get; set;}
        public decimal FundPrice {get; set;}
        public decimal TotalUnitFund {get; set;}
        public decimal TotalFundAmount {get; set;}
        public date NAVDate {get; set;}
        public decimal FundAmount {get; set;}
        public string FundUnit {get; set;}
        public decimal FundTotal {get; set;}
        public date FundNAVDate {get; set;}

        public FundDetail(){
        }       
    }  
    
    
    public void initFundInfo () {

        DateTime dtStart = DateTime.now();
        
        //
        system.debug ('>>> initFundInfo is begin ..');
        initMain();
        fundHistoryLastPageNo = 0;
        fundDetailLastPageNo = 0;
        fundPriceHistoryLastPageNo = 0;
        
        // get Row Per Page
        fundHistoryRowPerPage = CCCUtils.getRowPerPage('Backend', entity, PolicyApp, 'Fund History', 'FundInfoPage');
        fundDetailRowPerPage = CCCUtils.getRowPerPage('Backend', entity, PolicyApp, 'Fund Details', 'FundInfoPage');
        fundPriceHistoryRowPerPage = CCCUtils.getRowPerPage('Backend', entity, PolicyApp, 'Fund Price History', 'FundInfoPage');
        //fundHistoryLastDate = Date.today();
        
        cLine = [SELECT Id, Name, Contact__c, Contact__r.Name, Contact__r.Entity__c, Nilai_Conservation__c, Nilai_Withdrawal__c, Selisih__c, Offering_Retain__c, Call_Status_Config__c, Reason_Status_Config__c FROM Call_Line__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        
        contactID = cLine.Contact__c;
        system.debug('contactID: '+contactID);
        system.debug('Contact (Name): '+cLine.Contact__r.Name);
        
        system.debug('Call Line (Nilai_Conservation__c): '+cLine.Nilai_Conservation__c);
        
        sessionID = contactID.substring(0,15) + '-'+ CCCUtils.getSessionID();
        system.debug('sessionID (new): '+sessionID);
        
        system.debug ('>>> sessionID : ' + sessionID );
        preparingPageData(sessionID, 'FundInfoPage');
        
        DateTime dtEnd = DateTime.now();
        long d =  dtEnd.getTime() - dtStart.getTime() ;
        
        if(n_Conservation != null && (cLine.Nilai_Conservation__c == null || cLine.Nilai_Conservation__c == 0) && cLine.Nilai_Conservation__c != n_Conservation){ this.nilaiConservation = n_Conservation; system.debug('this.nilaiConservation (not NULL) (1): '+ this.nilaiConservation); } 
        else if(n_Conservation != null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0) && cLine.Nilai_Conservation__c != n_Conservation){ this.nilaiConservation = cLine.Nilai_Conservation__c; system.debug('this.nilaiConservation (not NULL) (2): '+ this.nilaiConservation); } 
        else if(n_Conservation != null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0) && cLine.Nilai_Conservation__c == n_Conservation){ this.nilaiConservation = cLine.Nilai_Conservation__c; system.debug('this.nilaiConservation (not NULL) (3): '+ this.nilaiConservation); } 
        else if(n_Conservation == null && (cLine.Nilai_Conservation__c == null && cLine.Nilai_Conservation__c == 0)){ this.nilaiConservation = 0; system.debug('this.nilaiConservation (NULL) (4): '+ this.nilaiConservation); } 
        else if(n_Conservation == null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0)){ this.nilaiConservation = cLine.Nilai_Conservation__c; system.debug('this.nilaiConservation (NULL) (5): '+ this.nilaiConservation); }
        
        this.nilaiWithdrawal = 0;
        system.debug('this.nilaiWithdrawal: '+ this.nilaiWithdrawal);
        //offeringRetainList = new List<SelectOption>();
        
        system.debug ('.');system.debug ('.');
        system.debug ('=========== PAGE LOAD ====================== ');
        system.debug ('=========== FUND INFO PAGE =========== ');
        system.debug ('=========== Page Initiation Starting at : ' + dtStart + ' ('+ dtStart.addHours(7) +')');
        system.debug ('=========== Page Ready at               : ' + dtEnd + ' ('+ dtEnd.addHours(7) +')');
        system.debug ('=========== Total Duration              : ' + d + ' milliseconds'); 
        system.debug ('======= *** Page is already *** ==============================================================================================================');
        system.debug ('----------------------------------------------------------------------------------------------------------------------------------------------');                   
    }
    
    
    public void initMain(){ 
        List<AppLog__c> logList = new List<AppLog__c>();        
        AppLog__c applogWs = new AppLog__c();
        AppLog__c applogScreen = new AppLog__c();
        applogScreen.id__c = contactId;
        applogScreen.method__c = 'load police detatil screen ';
        //applogScreen.start_date__c = system.now();
        applogScreen.StartLongTime__c = system.now().getTime();
    
        //List<Contact> contactList = [SELECT Id, Policy_No__c, Entity__c, PolicyApp__c FROM Contact WHERE ID =: contactId];      system.debug('contactList: ' +contactList);
        List<Contact> contactList = [SELECT Id, name, Policy_No__c, Entity__c, PolicyApp__c, Certificate_No__c, Phone, MobilePhone, HomePhone, Policy_Status__c, Policy_Effective_Date__c, Agent_Name__c, Agent_Code__c, Agent_Status__c, Premium__c, Segment_Name__c, Branch_Name__c, Branch_Code__c, Date_of_Accident__c, Driver__c, Accident_Place__c, Detail_of_Damage__c, Production_Year__c, Licence_Number__c, Machine_No__c, Chassis_no__c, Vehicle_Type__c, Color__c, Machine_Capacity__c, Agent_Profile_No__c FROM Contact WHERE ID =: contactId];      
        system.debug('contactList: ' +contactList);
        Contact contactRec = null;
        
        if(contactList.size()>0){ contactRec = contactList[0]; policyNo = contactRec.Policy_No__c; contactName = contactRec.name; certificateNo = contactRec.Certificate_No__c; entity = contactRec.Entity__c; policyApp = contactRec.PolicyApp__c;
            
            system.debug (' *** policyNo      : ' + policyNo );
            system.debug (' *** contactName   : ' + contactName );
            system.debug (' *** certificateNo : ' + certificateNo );
            system.debug (' *** entity        : ' + entity );
            system.debug (' *** policyApp     : ' + policyApp );
            
        }
    }
    
    
    public String fundDetailJSON{
        get{
            return fundDetailJSON;
        }
        set{
            system.debug('>>> on fundDetailJSON ');
            String jsonStr = value.unescapeHtml4();
            system.debug('>>> ensure jsonStr : '+ jsonStr);
            
            fundDetailList = new List<FundDetail>();
            //fundDetailList = null;
            
            fundDetailJSON = jsonStr;
            if(jsonStr!=''){
                system.debug('>>> jsonStr : '+ jsonStr);

                Map<String, Object> packageData = new Map<String, Object>();
                packageData = CCCUtils.getMapPackageFromJSON(jsonStr);
                
                string status = (string) packageData.get('status');  
                string service = (string) packageData.get('service');
                string operation = (string) packageData.get('operation');               
     
     
                // Get Map Data
                Map<String, Object> mapData = new Map<String, Object>();
                
                if (status == '1') {
                    try {
                        mapData = (Map<String, Object>) packageData.get('mapData');
                        List<Object> objList  = (List<Object>) CCCUtils.getListDataOnMap(mapData, 'Body::AgSa_InsurancePolicy_Type::hasAccountDetailsIn');

                        integer numberOfRecords = integer.valueOf(CCCUtils.getStringDataOnMap(mapData, 'Body::AXAAsiaPagination_Type::numberOfRecords'));
                        integer pageNumber = integer.valueOf(CCCUtils.getStringDataOnMap(mapData, 'Body::AXAAsiaPagination_Type::pageNumber'));


                        if (objList.size() < numberOfRecords) { fundHistoryLastPageNo = pageNumber; }
                        system.debug('== fundDetailLastPageNo :' + fundDetailLastPageNo );
                        
                              
                        List <FundDetail> fundDetailListTMP = new List <FundDetail>();
                        
                        //system.debug ('objList size : ' + objList.size());
                        for (Object oo : objList) {
                            Map<String, Object> mapRec = (Map<String, Object>) oo; 
                                
                            FundDetail dataRec = new FundDetail();
                            
                        /*
                            public class  FundDetail{
                                public string FundCode {get; set;}
                                public decimal FundAllocation {get; set;}
                                public decimal FundPrice {get; set;}
                                public decimal TotalUnitFund {get; set;}
                                public decimal TotalFundAmount {get; set;}
                                public date NAVDate {get; set;}
                                public decimal FundAmount {get; set;}
                                public string FundUnit {get; set;}
                                public decimal FundTotal {get; set;}
                                public date FundNAVDate {get; set;}

                                public FundDetail(){
                                }       
                            }
                            */
                            dataRec.FundCode     = CCCUtils.getStringDataOnMap(mapRec, 'hasInvestmentFundDetailsIn::investmentFundCd');
                            dataRec.FundAllocation   = CCCUtils.strToDec( CCCUtils.getStringDataOnMap(mapRec, 'hasInvestmentFundDetailsIn::fundAllocation'));
                            dataRec.FundPrice    = CCCUtils.strToDec( CCCUtils.getStringDataOnMap(mapRec, 'hasInvestmentFundDetailsIn::unitPrice'));
                            dataRec.TotalUnitFund    = CCCUtils.strToDec( CCCUtils.getStringDataOnMap(mapRec, 'hasInvestmentFundDetailsIn::totalUnits'));
                            dataRec.TotalFundAmount  = CCCUtils.strToDec( CCCUtils.getStringDataOnMap(mapRec, 'hasInvestmentFundDetailsIn::totalFundAmount'));
                            dataRec.NAVDate  = CCCUtils.strToDate( CCCUtils.getStringDataOnMap(mapRec, 'hasInvestmentFundDetailsIn::navDt'), 'yyyymmdd');   
                                            
                            fundDetailListTMP.add(dataRec);             
                        }

                        if (fundDetailListTMP.size()==1 && fundDetailListTMP[0].FundCode=='') { fundDetailLastPageNo = pageNumber-1; }
                        system.debug('== fundDetailLastPageNo :' + fundDetailLastPageNo );
                                                
                        
                        fundDetailList = fundDetailListTMP;
                        system.debug('====== value of fundDetailList : ' + fundDetailList);
                        
                    }
                    catch  (Exception e) { 
                            system.debug ('================ ERROR mapping (' + service + ' - ' + operation + ')' + e.getMessage());
                        }
                }
                // :: if the response is failed
                else if (status == '-1') {
                    system.debug ('================ JSON is unrecognized (' + service + ' - ' + operation + ')');
                    system.debug ('================ DeserializeUntyped process get Error. jsonStr : ' + jsonStr);
                    ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR, operation + ' data cannot be retrieved. Please contact administrator.'); 
                    ApexPages.addMessage(errMsg);
                    
                }
                else if (status == '0') {
                    //default - no result from json (maybe error)
                    string exceptionCode = (string) packageData.get('exceptionCode');
                    if (CCCUtils.isNoDataError(exceptionCode)) {
                        system.debug ('================ JSON status is 0 with Exception Code is ' + exceptionCode +  ' (No Data) - (' + service + ' - ' + operation + ')');
                    }
                    else {
                        system.debug ('================ JSON Response is Failed (' + service + ' - ' + operation + ')');
                        system.debug ('================ Exception Message : ' + (string) packageData.get('exceptionMessage'));
                        ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR, operation + ' data cannot be retrieved. Please contact administrator.'); 
                        ApexPages.addMessage(errMsg);
                    }
                }
                
            }
            
            if(fundDetailList.size() > 0){
                n_Conservation = fundDetailList[0].totalFundAmount;
            	system.debug('n_Conservation: '+n_Conservation);
            }
            
        }
    }
    
    
    public void preparingPageData (string sessionID, string pageName) {
        /* ----------------------------------- */
        /* Load Data for page                  */
        /* ----------------------------------- */
        system.debug ('.'); system.debug ('.');
        system.debug ('======= *** PREPARING OF PAGE DATA *** ==========================================================================================================');
        
        DateTime dtStart = DateTime.now();
        system.debug ('=========== Starting at : ' + dtStart + ' ('+ dtStart.addHours(7) +')');
        
        
        //string pageName='PolicyInfoPage';
        //List<Session_data__c> sessionDataList = [select data_name__c, service__c, operation__c, classType__c, refNo__c, session_id__c, page_name__c, data__c, data_request__c from session_data__c where Entity__c = 'AFI' AND service__c = 'getFundDetail' AND Operation__c = 'Fund' order by  sequenceNo__c , order__C];
        
        List<Session_data__c> sessionDataList = [select data_name__c, service__c, operation__c, classType__c, refNo__c, session_id__c, page_name__c, data__c, data_request__c from session_data__c where Entity__c = 'AFI' AND service__c = 'getFundDetail' AND Operation__c = 'Fund' AND session_id__c=:sessionID order by  sequenceNo__c , order__C];
        Session_data__c sessionDataRec = null;
        // select data_name, data from session_data__c where session_id__c='userid-customerid-20170106-abcde12345' and data_name__c='Policy Details' and page_name__c='PolicyInfoPage';
        integer dataNo=0;
        if(sessionDataList.size()>0){
            for(Integer i = 0; i < sessionDataList.size(); i++){  
                sessionDataRec = sessionDataList[i];
                
                sessionID = sessionDataRec.session_id__c;
                
                dataNo=i+1;
                system.debug ('.'); 
                system.debug('== :: DATA NO      : #' + dataNo + ' << ');
                system.debug('== :: SERVICE      : ' + sessionDataRec.service__c);
                system.debug('== :: OPERATION    : ' + sessionDataRec.operation__c);
                system.debug('== :: Entity       : ' + entity);
                system.debug('== :: App          : ' + policyApp);
                system.debug('== :: JSON Request : ' + sessionDataRec.data_request__c);
                

                setJSONVariable(sessionDataRec.service__c +'::'+sessionDataRec.operation__c, sessionDataRec.data__c );
            }           
        }
        
        system.debug ('.');system.debug ('.');system.debug ('.');
        system.debug ('=========== Starting at : ' + dtStart + ' ('+ dtStart.addHours(7) +')');
        DateTime dtEnd = DateTime.now();
        system.debug ('=========== Finish at   : ' + dtEnd + ' ('+ dtEnd.addHours(7) +')');
        long d =  dtEnd.getTime() - dtStart.getTime() ;
        system.debug ('=========== Duration    : ' + d + ' milliseconds'); 
        system.debug ('======= *** Preparing of Page data is Done *** ==================================================================================================');
        system.debug ('----------------------------------------------------------------------------------------------------------------------------------------------');
        system.debug ('.');
    }
    
    
    public void setJSONVariable (string code, string value) {
        system.debug('----- mapping for  : ' + code);
        system.debug('----- value        : ' + value);
        
        if (value!= null) {
            // :: getFundDetail
            if (code == 'getFundDetail::Fund') { 
                fundDetailJSON = value;
            }
        }
    }
    //END - EIP FUND INFO (Update 12 April 2020)
    
    
    public ConservationWithdrawal() {
        
        /*this.nilaiConservation = n_Conservation;
        system.debug('this.nilaiConservation: '+ this.nilaiConservation);
        this.nilaiWithdrawal = 0;
        system.debug('this.nilaiWithdrawal: '+ this.nilaiWithdrawal);
        //offeringRetainList = new List<SelectOption>();
        cLine = [SELECT Id, Name, Contact__c, Contact__r.Entity__c, Nilai_Conservation__c, Nilai_Withdrawal__c, Selisih__c, Offering_Retain__c, Call_Status_Config__c, Reason_Status_Config__c FROM Call_Line__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        
        contactId = cLine.Contact__c;*/
    }
    
    private void recalcNewPrice() {
        if(n_Conservation != null && (cLine.Nilai_Conservation__c == null || cLine.Nilai_Conservation__c == 0) && cLine.Nilai_Conservation__c != n_Conservation){ nilaiConservation = n_Conservation; system.debug('nilaiConservation (1): '+ this.nilaiConservation); } 
        else if(n_Conservation != null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0) && cLine.Nilai_Conservation__c != n_Conservation){ nilaiConservation = cLine.Nilai_Conservation__c; system.debug('nilaiConservation (2): '+ this.nilaiConservation); } 
        else if(n_Conservation != null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0) && cLine.Nilai_Conservation__c == n_Conservation){ nilaiConservation = cLine.Nilai_Conservation__c; system.debug('nilaiConservation (3): '+ this.nilaiConservation); } 
        else if(n_Conservation == null && (cLine.Nilai_Conservation__c == null && cLine.Nilai_Conservation__c == 0)){ nilaiConservation = 0; system.debug('nilaiConservation (4): '+ this.nilaiConservation); } 
        else if(n_Conservation == null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0)){ nilaiConservation = cLine.Nilai_Conservation__c; system.debug('nilaiConservation (5): '+ this.nilaiConservation); }
        
        
        selisih = (null == nilaiConservation ? 0 : nilaiConservation) 
                 - (null == nilaiWithdrawal ? 0 : nilaiWithdrawal);
    }
    
    public PageReference save() {
        if(n_Conservation != null && (cLine.Nilai_Conservation__c == null || cLine.Nilai_Conservation__c == 0) && cLine.Nilai_Conservation__c != n_Conservation){ cLine.Nilai_Conservation__c = n_Conservation; system.debug('FINAL nilaiConservation (1): '+ this.nilaiConservation); } 
        else if(n_Conservation != null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0) && cLine.Nilai_Conservation__c != n_Conservation){ cLine.Nilai_Conservation__c = cLine.Nilai_Conservation__c; system.debug('FINAL nilaiConservation (2): '+ this.nilaiConservation); } 
        else if(n_Conservation != null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0) && cLine.Nilai_Conservation__c == n_Conservation){ cLine.Nilai_Conservation__c = cLine.Nilai_Conservation__c; system.debug('FINAL nilaiConservation (3): '+ this.nilaiConservation); } 
        else if(n_Conservation == null && (cLine.Nilai_Conservation__c == null && cLine.Nilai_Conservation__c == 0)){ cLine.Nilai_Conservation__c = 0; system.debug('FINAL nilaiConservation (4): '+ this.nilaiConservation); } 
        else if(n_Conservation == null && (cLine.Nilai_Conservation__c != null && cLine.Nilai_Conservation__c != 0)){ cLine.Nilai_Conservation__c = cLine.Nilai_Conservation__c; system.debug('FINAL nilaiConservation (5): '+ this.nilaiConservation); }
        
        
        //cLine.Nilai_Conservation__c = nilaiConservation;
        cLine.Nilai_Withdrawal__c = nilaiWithdrawal;
        //if(cLine.Call_Status_Config__c == 'Contacted' && cLine.Reason_Status_Config__c.substring(0,5) == 'Agree'){
            cLine.Selisih__c = selisih;
        //} else {
        //    cLine.Selisih__c = 0;
        //}
        cLine.Offering_Retain__c = cLine.Offering_Retain__c;
        
        system.debug('Nilai_Conservation__c: '+cLine.Nilai_Conservation__c);
        system.debug('Nilai_Withdrawal__c: '+cLine.Nilai_Withdrawal__c);
        system.debug('Selisih__c: '+cLine.Selisih__c);
        system.debug('Offering_Retain__c: '+cLine.Offering_Retain__c);
        
        update cLine;
        return new pagereference('/'+cLine.Id);
    }
    
    public PageReference cancel() {
        return new pagereference('/'+cLine.Id);
    }
    
}