force-app/main/default/objects/AppLog__c/AppLog__c.object-meta.xml
<CustomObject>
    <label>AppLog</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>AppLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppLog__c/fields/id__c.field-meta.xml
<CustomField>
    <fullName>id__c</fullName>
    <label>Contact SFID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Log_Call_Line__c.field-meta.xml
<CustomField>
    <fullName>Log_Call_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Line</label>
    <referenceTo>Call_Line__c</referenceTo>
    <relationshipLabel>AppLogs</relationshipLabel>
    <relationshipName>AppLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Log_Case__c.field-meta.xml
<CustomField>
    <fullName>Log_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>AppLogs</relationshipLabel>
    <relationshipName>AppLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Policy_App__c.field-meta.xml
<CustomField>
    <fullName>Policy_App__c</fullName>
    <label>Policy App</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Request_Value__c.field-meta.xml
<CustomField>
    <fullName>Request_Value__c</fullName>
    <label>Request Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AppLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchCoreServiceNotification.cls
global class SchCoreServiceNotification implements Schedulable {
    
    global void execute(SchedulableContext sc){
        
        Map<String, List<AppLog__c>> reportMapSuccess = new Map<String, List<AppLog__c>>();
        Map<String, List<AppLog__c>> reportMapError = new Map<String, List<AppLog__c>>();
        
        DateTime current = DateTime.now();
        DateTime ends = DateTime.newInstance(current.year(), current.month(), current.day(), current.hour(), 0, 0);
        DateTime start = ends.addHours(-1);
        
        system.debug('[SchCoreServiceNotification] Schedulable Execute: '+sc);
        String jobName = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE Id = :sc.getTriggerId()].CronJobDetail.Name;
        
        if (jobName == 'SchNotificationServiceError') {
            
            List<AppLog__c> errorLogs = [SELECT Id, LastModifiedDate, id__c, Report_Name__c, Status__c, Log_Call_Line__c, Log_Case__c, Request_Value__c, Policy_App__c FROM AppLog__c WHERE Status__c = 'Error' ORDER BY LastModifiedDate LIMIT :Integer.valueOf(Label.Limit_Batch_Service)];
            collectDataMap(reportMapError, errorLogs, 'ET - AMFS - Notification Service DMTM-RLS Error', 'Error', start, DateTime.now());
            rescheduleJob(errorLogs);
        }
        
        if (jobName == 'SchNotificationServiceSuccess') {
            
            List<AppLog__c> successLogs = [SELECT Id, LastModifiedDate, id__c, Report_Name__c, Status__c FROM AppLog__c WHERE Status__c = 'Success' AND LastModifiedDate > :start AND LastModifiedDate < :ends];
            
            system.debug('size of logs: '+successLogs.size());
            collectDataMap(reportMapSuccess, successLogs, 'ET - AMFS - Notification Service DMTM-RLS Success', 'Success', start, ends);
        }
    }
    
    private void collectDataMap(Map<String, List<AppLog__c>> mapLogs, List<AppLog__c> logs, String subject, String status, DateTime startTime, DateTime endTime) {
        if (logs.size() > 0) {
            
            for (AppLog__c log : logs) {
                if (!mapLogs.containsKey(log.Report_Name__c)) {
                    mapLogs.put(log.Report_Name__c, new List<AppLog__c>());
                }
                mapLogs.get(log.Report_Name__c).add(log);
            }

            sendNotificationReport(mapLogs, subject, status, startTime.toString(), endTime.toString());
        }
    }
    
    public void sendNotificationReport(Map<String, List<AppLog__c>> reportMap, String templateName, String status, String start, String ends) {
        List<Messaging.SingleEmailMessage> listEmail = new List<Messaging.SingleEmailMessage>();
        EmailTemplate et = [SELECT Id, Name, HtmlValue, Subject, Body FROM EmailTemplate WHERE Name = :templateName];
        
        String htmlBody = et.HtmlValue;
        String subject = et.Subject;
        
        OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'noreply.general@axa-mandiri.co.id'];
        
        for (String report : reportMap.keySet()) {
            String modHtmlBody = htmlBody;
            String modSubject = subject;
            modSubject = subject.replace('[report_name]', report);
            modHtmlBody = modHtmlBody.replace('[report_name]', report);
            if (status == 'Success') modHtmlBody = modHtmlBody.replace('[report_url]', Label.SFDC_URL_AXA_VF+'apex/ExportServiceRevamp?report='+report+'&status='+status+'&start='+start+'&ends='+ends);
            else modHtmlBody = modHtmlBody.replace('[report_url]', Label.SFDC_URL_AXA_VF+'apex/ExportServiceRevamp?report='+report+'&status='+status);
            modHtmlBody = modHtmlBody.replace('[date_created]', DateTime.valueOfGmt(ends).format());
            modHtmlBody = modHtmlBody.replace('[date_started]', DateTime.valueOfGmt(start).format());
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject(modSubject);
            mail.setHtmlBody(modHtmlBody);
            mail.setTreatTargetObjectAsRecipient(false);
            mail.setTemplateId(et.Id); 
            mail.setOrgWideEmailAddressId(owea.get(0).Id);    
            
            if (report.contains('Collection') && reportMap.get(report).size() > 0) mail.setToAddresses(Label.Email_Collection_Recipient.split(','));
            if (report.contains('Correspondence') && reportMap.get(report).size() > 0) mail.setToAddresses(Label.Email_Correspondence_Recipient.split(','));   
            if (report.contains('Inbound') && reportMap.get(report).size() > 0) mail.setToAddresses(Label.Email_Inbound_Recipient.split(','));   
            system.debug(reportMap.get(report).size());
            mail.setSaveAsActivity(false);
            listEmail.add(mail);
            
        }
        
        if(!Test.isRunningTest()) Messaging.sendEmail(listEmail);
    }
    
    public void rescheduleJob(List<AppLog__c> errorLogs) {
        CronTrigger schJob = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'SchNotificationServiceError' LIMIT 1];
        
        if (schJob != null) System.abortJob(schJob.Id);
        
        if (errorLogs.size() > 0) {
            //String sch = '0 '+String.valueOf(DateTime.now().addMinutes(Integer.valueOf(System.Label.SchNotificationServiceError_Minute)).minute())+' '+System.Label.SchNotificationServiceError_Hour.toString();
            //System.schedule('SchNotificationServiceError', sch, new SchCoreServiceNotification());   
            
            //Database.executeBatch(new LogCoreIntegrationServiceBatch(errorLogs), 20);
            System.enqueueJob(new LogCoreIntegrationServiceQueue(errorLogs));
        }
    }
}