force-app/main/default/objects/Contact/fields/Cust_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Cust_Segmentation__c</fullName>
    <inlineHelpText>Customer Segmentation for AMFS Only</inlineHelpText>
    <label>Cust Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>Priority</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Regular, Nasabah Aceh</fullName>
            </value>
            <value>
                <fullName>Priority, Nasabah Aceh</fullName>
            </value>
            <value>
                <fullName>Private, Nasabah Aceh</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
            <value>
                <fullName>Priorit</fullName>
                <isActive>false</isActive>
                <label>Priorit</label>
            </value>
            <value>
                <fullName>Privaate</fullName>
                <isActive>false</isActive>
                <label>Privaate</label>
            </value>
            <value>
                <fullName>Privat</fullName>
                <isActive>false</isActive>
                <label>Privat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/resetCustSegmentationCtrl.cls
public class resetCustSegmentationCtrl {
	Integer totalRecs = 0;
   	Integer count= 0;
   	Integer LimitSize {get; set;}
    
    public resetCustSegmentationCtrl(ApexPages.StandardController controller){
        //totalRecs =[SELECT Count() from Contact where Entity__c = 'AMFS' and Cust_Segmentation__c != 'Regular'];
        
    }
                                
    public void resetValueToRegular(){
        try{
            UpdateContactBatchable be = new UpdateContactBatchable(null, false, UserInfo.getUserId(), null);
			database.executeBatch(be, 1000);
        } catch(Exception e){
            System.debug('System Error '+e);
        }
    }
}