force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/CallPageTesterController.cls
public class CallPageTesterController{
public String currentRecordId {get;set;}
public Contact contactRec {get;set;}
public String token {get;set;}

 
    public CallPageTesterController(ApexPages.StandardController controller) {
        currentRecordId  = controller.getID();
        contactRec = [Select Policy_No__c, PolicyApp__c, Entity__c, Id from Contact where id =:currentRecordId ];
        
        CreateToken ct = new CreateToken();
        token = ct.getToken();
    }
}