force-app/main/default/objects/Contact/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFI</fullName>
            </value>
            <value>
                <fullName>MAGI</fullName>
            </value>
            <value>
                <fullName>AMFS</fullName>
            </value>
            <value>
                <fullName>ALI</fullName>
            </value>
            <value>
                <fullName>AGI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/mdmid_owner__c.field-meta.xml
<CustomField>
    <fullName>mdmid_owner__c</fullName>
    <label>MDM ID Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Policy_No__c.field-meta.xml
<CustomField>
    <fullName>Policy_No__c</fullName>
    <label>Policy No</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/PolicyApp__c.field-meta.xml
<CustomField>
    <fullName>PolicyApp__c</fullName>
    <label>PolicyApp</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/Trigger_ContactPolicyTakeoutTest.cls
@isTest
public class Trigger_ContactPolicyTakeoutTest {
    
    @testSetup
    static void initContact(){
        Contact contact = new Contact();
        contact.Policy_No__c = '410-7654321';
        contact.LastName = 'Abdullah';
        contact.mdmid_owner__c = '74123234';
        contact.Entity__c = 'AMFS';
        contact.PolicyApp__c = 'RLS';
        insert contact; 
    }
    
    @isTest
    static void contactTakeoutTest_Success() {
        Test.startTest();
       	Contact contact = [SELECT Id FROM Contact LIMIT 1];
        Call_Line_Retention__c cl = new Call_Line_Retention__c();
       	cl.Contact__c = contact.Id;
        cl.Remark_Description__c = 'Req by user';
        cl.Retention_Status__c = 'Takeout';
        insert cl;
        
		Contact contact2 = new Contact();
        contact2.Policy_No__c = '410-1234567';
        contact2.LastName = 'Ali';
        contact2.mdmid_owner__c = '74123234';
        contact2.PolicyApp__c = 'RLS';
        contact2.Entity__c = 'AMFS';
        insert contact2;
        
        Test.stopTest();
    }
    
    @isTest
    static void contactReleaseTest_Success(){
		Test.startTest();
       	Contact contact = [SELECT Id FROM Contact LIMIT 1];
        Call_Line_Retention__c cl = new Call_Line_Retention__c();
       	cl.Contact__c = contact.Id;
        cl.Remark_Description__c = 'Req by user';
        cl.Retention_Status__c = 'Release';
        insert cl;
        
		Contact contact2 = new Contact();
        contact2.Policy_No__c = '410-1234567';
        contact2.LastName = 'Ali';
        contact2.mdmid_owner__c = '74123234';
        contact2.PolicyApp__c = 'RLS';
        contact2.Entity__c = 'AMFS';
        insert contact2;
        
        List<Call_Line_Retention__c> listclr = [SELECT Id, mdmid_owner__c, Policy_No__c, Retention_Status__c FROM Call_Line_Retention__c WHERE mdmid_owner__c = :contact2.mdmid_owner__c];
        System.assertEquals(1, listclr.size(), 'release status should be cannot inserted to object call line retention');
        Test.stopTest();        
    }
}